export const englishTime = {
transmittance: [
 'Multiply the remaining fractions','How much remains when light reaches layer i?',
 [
  ['Think of each layer as a partially covering sheet','An alpha of 0.2 means this layer covers 20%, leaving 80% to continue. This transparency model builds intuition; the actual scene need not consist of glass.'],
  ['Apply the next layer only to what remains','If layer 2 also covers 20%, it takes 20% of the remaining 80%, not 20% of the original amount.'],
  ['Repeat the rule','Before layer i, we have passed through i−1 layers. The ∏ symbol multiplies all their remaining fractions.'],
  ['Why does the training code prepend a 1?','cumprod computes prefix products. We need the product before the current layer, so prepend 1 and remove the final entry.'],
 ],
 'With two alphas of 0.5, layer 2 receives 0.5 and the background receives 0.25.',
 [['Sort alpha near to far, then take cumprod along the Gaussian dimension. [:, :-1] selects transmittance before each current layer.','Ti ↔ transmittance; dim=1 ↔ Gaussian dimension']],
 'Ti does not include the current layer’s alpha. Including it would make the layer occlude itself again.',
 'If the first alpha is 1, what are all subsequent Ti values?','They are zero. The shader caps individual alpha at 0.99, so one layer alone never produces an exact zero in practice.',
],
composite: [
 'Weighted sum + telescoping sum','How do layers and background form the final pixel?',
 [
  ['Begin with one layer and a background','The current layer contributes alpha of its color; the remaining fraction reveals the background. Apply the same operation independently to RGB.'],
  ['Replace the background with the composited tail','For two layers, first composite layer 2 with the background to form B1. Place B1 behind layer 1 and expand the brackets.'],
  ['Generalize to N layers','Reaching layer i requires passing through the previous i−1 layers, giving color weight Ti αi. Background weight is TN+1, the fraction passing through all layers.'],
  ['Check the sum of weights for missing terms','Ti αi=Ti−Ti+1. The intermediate terms cancel in the sum, leaving 1−TN+1. Add the background weight to obtain exactly 1.'],
 ],
 'Red in front, blue behind, both alphas 0.5, and a black background.',
 [['The code sums T*alpha*color along the Gaussian dimension. The background is black, so its zero contribution is omitted.','C ↔ return value; N ↔ tensor dimension 1']],
 'Changing layer order changes color. Center-depth sorting is an implementation approximation; intersecting large Gaussians may not have correct per-pixel occlusion.',
 'Why might the weights appear not to sum to 1?','Gaussian weights alone sum to 1−remaining transmittance. Include the background weight to obtain 1.',
],
premultiplied: [
 'The same composition written for GPU blending','Why output RGB×alpha while using One as the source blend factor?',
 [
  ['Define premultiplied color','Multiply color by coverage in advance and call the result c̃. This gives transparent and opaque color storage a consistent interpretation.'],
  ['Treat the already-rendered tail as destination','Draw distant layers first. The current nearer layer is the source: it contributes its premultiplied color and hides an alpha fraction of the destination.'],
  ['Map the equation to the hardware’s two factors','Hardware computes src×srcFactor + dst×dstFactor. Set srcFactor=One and dstFactor=OneMinusSrcAlpha. The alpha channel also follows the over rule.'],
  ['Cross-check the near-to-far formula','Draw distant blue first, then nearer red. Expanding gives red 0.5 and blue 0.25, just as before. Different evaluation order, same algebraic result.'],
 ],
 'If the shader already outputs red (0.5,0,0), using SrcAlpha=0.5 multiplies it a second time incorrectly.',
 [['Returning vec4(rgb*alpha,alpha) explicitly produces premultiplied output.','c̃s ↔ input.color_opacity.rgb*alpha'],
  ['PREMULTIPLIED_ALPHA_BLENDING matches that output. StgPass sorts far to near, and transparent splats do not write depth.','over ↔ blend state; order ↔ exact radix depth sort']],
 'Gaussian depth writes should generally be disabled for transparent composition. Testing against opaque-scene depth is a separate decision.',
 'Does premultiplied color still need Ti?','Sequential hardware over already implements occlusion implicitly. A handwritten near-to-far accumulator still needs to multiply by the incoming Ti.',
],
'volume-bridge': [
 'Thin-layer limit; not exact GS ray integration','Why does continuous density produce exponential transmittance?',
 [
  ['Divide a path into N thin layers','Density σ is extinction strength per unit length. For sufficiently small Δs, the transmitted fraction is approximately 1−σΔs. Split total length l equally.'],
  ['Make the layers progressively thinner','Use (1+a/N)ᴺ→eᵃ with a=−σl. Constant density gives exponential transmittance; the covered fraction is 1−T.'],
  ['Multiply separate factors for varying density','Take logarithms to turn products into sums. Use ln(1−ε)≈−ε, then take the limit of the finely subdivided sum to obtain an integral.'],
  ['Return to discrete rendering segments','Assume constant density within each segment and use its length Δsi to obtain alpha. Remaining fractions multiply between segments, connecting to the previous composition model.'],
 ],
 'Let σ=2 per meter and segment length be 0.5 meter. The product σΔs is dimensionless.',
 [['The renderer computes opacity times a projected Gaussian kernel; it does not integrate σ along each ray. This formula only explains the relation between transparent composition and volume rendering.','σ and Δs have no corresponding fields in the current STG-Lite shader']],
 'Learned opacity is not physical extinction density σ. Their parameters, units, and integration procedures differ.',
 'Does splitting a constant-density segment in half change total transmittance?','No. e^(−σl/2)×e^(−σl/2)=e^(−σl).',
],
'time-domain': [
 'Unit conversion','How do video seconds, frame indices, and model time line up?',
 [
  ['Choose a time origin and scale','Subtract origin s0 from physical time s to get elapsed seconds, then divide by D seconds for dimensionless model time t. D must follow the training convention.'],
  ['Align with each Gaussian’s own center time','τ is the model time at which that Gaussian is most active. Motion coefficients are expanded around τ, so evaluation uses Δt=t−τ.'],
  ['Match the frame-index denominator','If training uses t=j/N at frame rate fps, then s−s0=j/fps and D=N/fps. The final frame has t=(N−1)/N, not 1. Using j/(N−1) instead requires a different D.'],
  ['Find where time is converted in the code','The host converts seconds to t using the verified checkpoint duration. For the legacy browser API it passes t×10, which Rust divides by 10; this does not make the clip ten seconds long. Native StgPass accepts normalized_time directly.'],
 ],
 'With 100 frames at 25fps and the j/N convention, frame 50 has model time 0.5.',
 [['The current LOOP_SECONDS is 10. Playback uses rem_euclid and divides by this value; this only specifies playback speed.','s ↔ time_seconds; D ↔ LOOP_SECONDS'],
  ['Native integration supplies normalized time explicitly; prepare checks the range 0..1.','t ↔ normalized_time → camera.scene.x']],
 'The 32-float PLY contains neither fps nor capture duration. Do not infer physical seconds from the model alone.',
 'Must motion coefficients change to play the same model at double speed?','No. Change how quickly input t advances with real time. If redefining the model-time coordinate itself, however, convert the coefficients accordingly.',
],
'temporal-rbf': [
 'Choice of temporal kernel','Why does this temporal Gaussian omit the factor 1/2?',
 [
  ['Define distance from the active time','Δt=t−τ and ρ controls width. Divide by width and square so time units cancel. STG-Lite chooses exp(−distance²) as its visibility envelope.'],
  ['Guarantee positive width with log-width','PLY stores ℓτ rather than ρ. Decode with exp, as for spatial scale. The paper writes a different coefficient sτ before the squared offset; the two forms convert directly.'],
  ['Compare with a standard Gaussian','To describe the same curve, the coefficients of the squared offset must match. In this parameterization, ρ is not the standard deviation σt.'],
  ['Multiply base opacity by temporal weight','Base opacity gives the peak visibility, and the temporal kernel attenuates it. At the center w=1; one width ρ away, w=e⁻¹.'],
 ],
 'Let τ=0.5, ρ=0.25, t=0.75, and β=0.',
 [['temporal_opacity has no 0.5 in its exponent. The fragment shader’s spatial power is the one that includes −0.5.','ρ ↔ temporal_scale; w ↔ temporal_opacity; o(t) ↔ opacity']],
 'Do not copy the 1/2 from one exponent to the other for visual consistency. Temporal width is not the total recording duration.',
 'If ρ doubles at the same Δt, what happens to the squared term in the exponent?','It becomes one quarter as large, making the temporal envelope wider.',
],
trajectory: [
 'Polynomial model','Represent a moving center with a small set of stored coefficients.',
 [
  ['Start with a stationary model','If we store only μ0, position never changes. Here μ0 is the center at t=τ, which need not be the first video frame.'],
  ['Add linear motion','Each model-time unit adds m1. In 3D, each coefficient contains three numbers for x,y,z.'],
  ['Add curvature and more flexible changes','The quadratic term makes velocity vary; the cubic term makes acceleration vary. This is a finite-order modeling choice, not a claim that real motion must be cubic.'],
  ['Evaluate each coordinate with ordinary arithmetic','For x, square and cube Δt, multiply by each coefficient, and add. Repeat for y and z. Horner evaluation can reduce multiplications, but the current shader computes dt2 directly for reuse.'],
 ],
 'Take μ0=(1,2,10), m1=(2,0,0), m2=(0,4,0), m3=(0,0,8), and Δt=0.5.',
 [['The nine motion floats cross vec4 boundaries, so quadratic and cubic vectors must be reconstructed.','m1 ↔ r2.xyz; m2 ↔ (r2.w,r3.x,r3.y); m3 ↔ (r3.z,r3.w,r4.x)'],
  ['The CPU uses the same trajectory for culling and sorting, while the GPU uses it to place the quad. Both evaluations must agree.','μ(t) ↔ position / center']],
 'm2 is not acceleration itself, and m3 is not the third derivative itself. Differentiation introduces additional factors.',
 'At Δt=0, where is the center even if motion coefficients are large?','It is still μ0 because every higher-order term is multiplied by zero.',
],
velocity: [
 'Polynomial differentiation + units','How do stored coefficients differ from physical velocity and acceleration?',
 [
  ['Verify square and cube rules using difference quotients','The foundations expanded the differences to show that the derivatives of t² and t³ are 2t and 3t². With fixed τ, the derivative of Δt with respect to t is 1.'],
  ['Differentiate each term and add','μ0 is constant, so its derivative is zero. Vector coefficients remain fixed; apply the same operation independently to each component.'],
  ['Differentiate once more','At Δt=0, acceleration is 2m2; the third derivative is 6m3. Taylor coefficients written from velocity, acceleration, and jerk therefore include 1/2 and 1/6.'],
  ['Convert model time to seconds','Since t=(s−s0)/D, dt/ds=1/D. The chain rule divides velocity by D and acceleration by D².'],
 ],
 'At Δt=0.5 in the previous example, model-time velocity is (2,4,6). If D=10 seconds and space is measured in meters:',
 [['The renderer evaluates position, not an explicit velocity output. Derive diagnostic velocity or motion vectors from these motion fields; the current pass does not already output them.','Derivative inputs ↔ motion_linear/quadratic/cubic']],
 'Without a documented spatial unit, say world units per second rather than meters per second.',
 'If D doubles with the model unchanged, what happens to physical velocity at the same normalized time?','It halves.',
],
'rotation-time': [
 'Four-dimensional coefficient model + normalization','Why add coefficients and then normalize to animate rotation?',
 [
  ['Move along a line in four-dimensional coefficient space','q0 and ω each have four components. Evaluate u=q0+Δtω componentwise. Here ω is a quaternion-coefficient change, not a 3D physical angular velocity.'],
  ['A line does not stay on the unit sphere','Even if q0 has unit length, u usually does not. For example, (1,0,0,0)+(0,0,0,0.5) has length √1.25.'],
  ['Divide by length to recover a unit quaternion','Dividing every component by the same length makes the sum of squares equal 1. This requires u≠0. Feed the normalized result into the rotation matrix above.'],
  ['Understand why angular speed is not constant','Normalization projects a straight coefficient path onto the unit sphere, so angle usually changes nonlinearly. This is neither SLERP nor automatically a solution of the rigid-body angular-velocity equation.'],
 ],
 'At Δt=0.5, q≈(0.894427,0,0,0.447214), representing a rotation of about 53.13° around z.',
 [['normalize(splat.r6 + dt*splat.r7) performs exactly these steps. Finite-value checks in the loader do not guarantee nonzero u at every time; the asset must satisfy that condition.','q0 ↔ r6; ω ↔ r7; q ↔ quaternion']],
 'The current shader does not define a valid rotation for u=0. Always state the nonzero-norm condition rather than treating normalize as unconditionally safe.',
 'Does rotation change over time if ω=0?','No. It stays at normalize(q0), provided q0 is nonzero.',
],
'normalization-gradient': [
 'Differentiate components, then assemble a matrix','Why does the normalize gradient subtract qqᵀ?',
 [
  ['Give the length a short name','Let r=||u||. Since r²=∑uj², differentiating both sides with respect to uj gives 2r ∂r/∂uj=2uj.'],
  ['Apply the quotient rule to qi=ui/r','δij is 1 when i=j and 0 otherwise. It is simply the derivative of ui with respect to uj.'],
  ['Replace ui/r and uj/r with qi and qj','Arrange the entries into a 4×4 matrix. The δij entries form I; the qiqj entries form the outer product qqᵀ.'],
  ['Connect the time derivative','Because u=q0+(t−τ)ω, du/dt=ω. Multiply the Jacobian by ω to obtain dq/dt. A change exactly along q is removed entirely by normalization.'],
 ],
 'For u=(2,0,0,0), r=2 and q=(1,0,0,0).',
 [['GPU normalize performs only the forward calculation. This derivative explains training-side autodiff; the repository’s toy trainer keeps rotation fixed and does not train q or ω.','Forward q ↔ quaternion; backward Jacobian ↔ teaching numerical checks']],
 'When r approaches zero, the denominator amplifies gradients. Mathematical differentiability does not mean this rendering pass has a backward kernel.',
 'Does q change if all of u is multiplied by a slightly larger positive number?','No. I−qqᵀ removes the radial component of change.',
],
};
