export const englishScreen = {
'covariance-proof': [
 'Proof from the definition of an average','Why does covariance need the linear transform on both sides?',
 [
  ['Find the new mean','Y=AX+b. An average distributes over addition, and constant A and b can move outside it. For finite samples, verify this by writing out the sum.'],
  ['Subtract the new mean from each new sample','The same translation b cancels. Covariance describes shape relative to the center, so it does not depend on where that center moves.'],
  ['Take the outer product and then its expectation','Transposition reverses multiplication order, giving Aᵀ on the right. Move the constant matrices outside the expectation; what remains is the original covariance.'],
  ['Translate the matrix expression back into scalars','The joint variation of output components i and j adds contributions from every pair of input components. This is the preceding matrix equation written entry by entry, not an extra theorem.'],
 ],
 'Let the 2D covariance of X be diag(1,4), stretch x by 2, and shrink y by half.',
 [['The teaching example has Σ=0.12²I, so JΣJᵀ simplifies to 0.12²*(J@Jᵀ). You cannot make this simplification for an arbitrary anisotropic Σ.','A ↔ jacobian; @ ↔ matrix multiplication; transpose(-1,-2) ↔ transpose the final two dimensions']],
 'This identity is exact for a fixed linear or affine transform. Perspective division is nonlinear, so the next formula needs an approximation first.',
 'If a 1D length scale triples, how much does the variance grow?','By 9: deviations are multiplied by 3 before being squared.',
],
'projected-covariance': [
 'First-order approximation + linear identity','Why is the GS screen ellipse described by J R Σ Rᵀ Jᵀ?',
 [
  ['Transform both center and shape into camera coordinates','The center needs rotation and translation; shape needs only rotation. Apply the covariance identity from the previous formula.'],
  ['Replace curved projection locally with its tangent','A derivative describes how a very small change propagates. Write a 3D point as center plus offset, keep the first-order change in each output, and omit second-order and higher terms.'],
  ['The translation term does not change variance','In the linear approximation, π(μc) is constant and J is the fixed matrix evaluated at the center. Screen covariance is JΣcJᵀ. Adding εI supplies extra isotropic screen-space variance.'],
  ['Rewrite the matrix product using three small vectors','If Σ=∑ak akᵀ, define dk=JRcw ak. Distributing the products gives a sum of three projected-axis outer products. This is the shader’s computation.'],
  ['Check the approximation’s limits','When a Gaussian is thick in depth relative to its center depth, or is near the camera, J varies substantially across it and the approximation becomes less accurate. Adding 0.3 is a filtering choice, not a constant required by perspective geometry.'],
 ],
 'Use the previous J and Σc=diag(1,4,9): project axes of lengths 1,2,3 separately, then add their outer products.',
 [['The shader keeps the three independent entries cov_a,cov_b,cov_c rather than first allocating a 3×3 covariance matrix.','dk ↔ d0,d1,d2; ε ↔ +0.3']],
 'Adding 0.3 to standard deviation is different from adding 0.3 to variance. This implementation adds variance and does not apply an associated integral-energy compensation.',
 'Why do cx and cy not appear in C?','They only translate the projected center. Their derivatives are zero, so they do not affect local shape.',
],
'homogeneous-derivative': [
 'Common denominators → directional derivative','WGSL does not explicitly write fx/z. How can we verify that it computes the same Jacobian?',
 [
  ['Append different final coordinates to the center and direction','The center is h=PV[μ,1]; an axis direction is δh=PV[a,0]. Moving a small amount η along that axis gives h+ηδh in clip coordinates because matrix multiplication is linear.'],
  ['Subtract and use a common denominator','The hx hw terms cancel. Both remaining terms contain η, which cancels the η in the difference quotient.'],
  ['Let η approach zero; repeat for y','This requires nonzero hw. Combining the x and y results gives the shader’s vector numerator and denominator.'],
  ['Convert NDC displacement into pixels','NDC spans −1 to +1 horizontally, or 2 units across width W, so multiply by W/2. With WebGPU’s top-left screen origin, downward pixel y uses −H/2. The shader instead uses an internal upward screen coordinate and +H/2. Reflect the entire ellipse and offset using F; the quadratic distance is unchanged.'],
  ['Why multiply by w when returning a vertex to clip space?','To add δn after perspective division, add δn·hw to clip.xy first. Dividing by hw then leaves δn. All four billboard corners share center w, so perspective interpolation of local on this billboard is linear.'],
 ],
 'Let hx=2, hw=4, δhx=1, δhw=0.5, and W=800.',
 [['Every term appears by name in projected_axis. max(w²,1e−8) is a numerical guard; the CPU separately rejects centers behind the camera.','h ↔ center_clip; δh ↔ axis_clip'],
  ['pixel_offset becomes ndc_offset, which is multiplied by center_clip.w before being added to clip.xy.','δn ↔ ndc_offset']],
 'Do not mix downward pixel coordinates with upward projected axes halfway through the calculation. A basis change must act consistently on center, offset, and covariance.',
 'Why is the homogeneous coordinate of an axis 0?','It is a direction, not a point. The zero prevents camera translation from being added to the axis.',
],
conic: [
 'Solve two pairs of linear equations','Derive a 2×2 inverse without memorizing a shortcut.',
 [
  ['Treat the first inverse column as two unknowns','C times the first column of its inverse must be (1,0). This gives two linear equations.'],
  ['Eliminate one unknown','Multiply the first equation by c and the second by b, then subtract to get (ac−b²)u=c. Eliminate u similarly to solve for v. Call ac−b², D.'],
  ['Solve the second column and assemble the matrix','Replace the right-hand side with (0,1). The same elimination gives (−b/D,a/D). Put the two columns together to obtain Q.'],
  ['Understand the positive-definite condition','Complete the square in ax²+2bxy+cy². For a positive value in every nonzero direction, we need a>0 and c−b²/a>0, equivalently D>0.'],
 ],
 'For C=[[4,1],[1,2]], D=8−1=7.',
 [['PyTorch explicitly inverts covariance with linalg.inv. The GPU obtains the equivalent distance in eigen-axis local coordinates, explained next.','Q ↔ inverse; D ↔ det(C)']],
 'A small D amplifies numerical error through division. Arbitrary a,b,c values do not necessarily describe a valid ellipse.',
 'What is the inverse of C=diag(4,9)?','Q=diag(1/4,1/9), not diag(−4,−9).',
],
'pixel-weight': [
 'Equivalent ellipse coordinate systems','How does CPU dᵀQd become WGSL dot(local,local)?',
 [
  ['Express a pixel relative to the center','Pixel p and projected center must use the same screen coordinate system. World distance is not a substitute for screen distance.'],
  ['Expand the matrix multiplication completely','Because Q is symmetric, the two mixed terms are equal and combine into 2Q12 dxdy; neither contribution can be omitted.'],
  ['Measure along the ellipse’s own principal axes','Write C=U diag(λ₁,λ₂)Uᵀ, with perpendicular unit axes as U’s columns. First rotate with Uᵀ, then divide by standard deviations √λ to obtain local.'],
  ['Let two triangles interpolate local for us','Place vertices at the corners of the rectangle extending ±3σ along each principal axis, and assign local=corner×3. Each fragment receives its continuous local coordinates, so dot(local,local) gives r² directly.'],
  ['Include the actual branches','The shader caps alpha at 0.99 and discards values below 1/255. No fragments exist outside the rectangle. local corresponds exactly to the original C only when axis-length limits are inactive.'],
 ],
 'Take C=diag(4,1), pixel offset (2,1), and o=0.8.',
 [['There is no inv(C) here: the inverse transformation is implicit in the vertex local coordinates and their interpolation.','local ↔ l; power ↔ −r²/2'],
  ['major_axis and minor_axis form U; sigma_major/minor are √λ.','corner*3 ↔ l at each vertex']],
 'local is neither texture UV nor world coordinates. It measures distance in standard-deviation units, with zero at the center.',
 'Must alpha equal 1 at local=(0,0)?','No. The spatial kernel is 1, but it is still multiplied by temporal weight and base opacity, then capped at 0.99.',
],
eigenvalues: [
 'Quadratic equation + coordinate transformation','Recover the ellipse’s major and minor axes from a,b,c.',
 [
  ['Find a vector whose direction survives the transform','If Cv=λv, v keeps its direction and is scaled by λ. This defines an eigenvector and eigenvalue. Move the right side to the left.'],
  ['Determine when a nonzero solution exists','The two equations must not be independent, or v=0 is the only solution. In 2D this requires determinant zero. Expanding gives an ordinary quadratic equation.'],
  ['Solve by completing the square','Substitute s=a+c and p=ac−b² into the quadratic formula from the foundations. The discriminant simplifies to (a−c)²+4b².'],
  ['Solve for a direction and normalize it','The first row is (a−λ)vx+bvy=0, satisfied by (vx,vy)=(b,λ−a). Divide by its length for a unit axis; the other axis is perpendicular. If b=0, select a coordinate axis according to a and c.'],
  ['Take the square root of variance to get length','In the eigenbasis the quadratic form is ξ₁²/λ₁+ξ₂²/λ₂. Setting it to k² gives semiaxis lengths k√λ.'],
 ],
 'For C=[[4,1],[1,2]], λ±=3±√2.',
 [['discriminant and lambda_major/minor implement this quadratic solution. The GPU also floors λ at 0.1 and caps σ at 192 pixels as implementation guards.','λ± ↔ lambda_major/minor; u± ↔ major_axis/minor_axis']],
 'If C=aI, both axes have equal length and any orthonormal directions work. Do not normalize the zero vector (b,λ−a).',
 'For C=diag(9,4), how long are the 3σ semiaxes?','9 and 6 pixels: take square roots to get 3 and 2, then multiply by 3.',
],
support: [
 'Solve an exponential inequality','How far can we truncate weights below the alpha threshold?',
 [
  ['Write the condition for retaining a pixel','Let αmin>0, initially ignoring the cap. o is peak opacity at the current time, and r² is nonnegative.'],
  ['First check whether any solution exists','The kernel is at most 1. If o<αmin, even the center is below threshold and the entire Gaussian can be skipped. Otherwise divide by the positive value o.'],
  ['Take logarithms, then multiply by a negative number','ln is increasing, so it preserves the inequality. Multiplying by −2 reverses the inequality.'],
  ['Distinguish theoretical support from the actual rectangle','The exact threshold boundary is a circle of radius rmax in local coordinates, or an ellipse on screen. The shader draws a rectangle extending ±3σ along each principal axis, then discards fragments by alpha. These supports are not identical.'],
 ],
 'At local=(3.1,0), alpha is still above threshold, but the point lies outside the ±3 quad and produces no fragment. This exposes the actual truncation approximation.',
 [['corner×3 defines the geometric coverage; it is not computed from the threshold equation above.','±3σ ↔ the 3.0 in pixel_offset'],
  ['Discarding alpha below threshold further restricts coverage. Both decisions determine what is finally drawn.','αmin ↔ 0.0039215686']],
 '“3σ contains every relevant pixel” is false. With sufficiently high opacity, it cuts off tails still above threshold.',
 'If o equals αmin exactly, which points pass the mathematical threshold?','Only the center r=0; the pixel grid may contain no sample exactly at that center.',
],
};
