import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { collectMessages } from './i18n-catalog.mjs';
import { geometryLessons } from './lessons-geometry.mjs';
import { screenLessons } from './lessons-screen.mjs';
import { timeLessons } from './lessons-time.mjs';
import { familyLessons } from './lessons-families.mjs';
import { trainingLessons } from './lessons-training.mjs';
import { englishLessons } from './english-lessons.mjs';
import { englishScreen } from './english-screen.mjs';
import { englishTime } from './english-time.mjs';
import { englishFamilies } from './english-families.mjs';
import { englishTraining } from './english-training.mjs';
import { shTranslations } from './sh-content.mjs';
import { trainingTranslations } from './training-content.mjs';

export async function translations() {
  const dictionary = {
    ...JSON.parse(await readFile(new URL('./english-static.json', import.meta.url), 'utf8')),
    ...JSON.parse(await readFile(new URL('./english-dynamic.json', import.meta.url), 'utf8')),
    ...shTranslations,
    ...trainingTranslations,
  };
  const zh = { ...geometryLessons, ...screenLessons, ...timeLessons, ...familyLessons, ...trainingLessons };
  const en = { ...englishLessons, ...englishScreen, ...englishTime, ...englishFamilies, ...englishTraining };
  const add = (a,b) => {
    if (typeof b !== 'string' || !b.trim()) throw new Error('Missing English translation: ' + a);
    if (dictionary[a] && dictionary[a] !== b) throw new Error('Conflicting translation: ' + a);
    dictionary[a] = b;
  };
  for (const [id,l] of Object.entries(zh)) {
    const e = en[id];
    if (!e || e.length !== 8 || e[2].length !== l.steps.length || e[4].length !== l.code.length) throw new Error('Incomplete English lesson: ' + id);
    add(l.kind,e[0]); add(l.goal,e[1]);
    l.steps.forEach((s,i) => { add(s.title,e[2][i][0]); add(s.why,e[2][i][1]); });
    add(l.example[0],e[3]);
    l.code.forEach((c,i) => { add(c.explanation,e[4][i][0]); add(c.symbols,e[4][i][1]); });
    add(l.pitfall,e[5]); add(l.question,e[6]); add(l.answer,e[7]);
  }
  return dictionary;
}
export function resolve(text,dictionary) {
  if (dictionary[text]) return dictionary[text];
  const direct = dictionary[createHash('sha256').update(text).digest('hex').slice(0,12)];
  if (direct) return direct;
  let m;
  if ((m = text.match(/^复制 (.+) 的 LaTeX$/)) && resolve(m[1],dictionary)) return 'Copy LaTeX: ' + resolve(m[1],dictionary);
  if ((m = text.match(/^(.+)，较长公式可横向滚动$/)) && resolve(m[1],dictionary)) return resolve(m[1],dictionary) + '; scroll horizontally for long equations';
  if ((m = text.match(/^(\d+) · (.+)$/)) && resolve(m[2],dictionary)) return m[1] + ' · ' + resolve(m[2],dictionary);
  if ((m = text.match(/^(\d+) 步 · 数字算例 · 源码 · 自测$/))) return m[1] + ' steps · Worked example · Code · Check';
  if ((m = text.match(/^停下来想一想：(.+)$/)) && dictionary[m[1]]) return 'Pause and think: ' + dictionary[m[1]];
  if ((m = text.match(/^(.+) ↗$/)) && resolve(m[1],dictionary)) return resolve(m[1],dictionary) + ' ↗';
  if ((m = text.match(/^(.+) · 数学源码$/))) return m[1] + ' · Math source';
  if ((m = text.match(/^第 (\d+) 行$/))) return 'Line ' + m[1];
  return undefined;
}
export async function buildTranslations(html, output) {
  const dictionary = await translations();
  const messages = collectMessages(html);
  const missing = [];
  for (const {zh} of messages) {
    const en = resolve(zh,dictionary);
    if (en) dictionary[zh] = en; else missing.push(zh);
  }
  if (missing.length) throw new Error('Untranslated math messages (' + missing.length + '):\n' + missing.join('\n'));
  // Hash keys make the editorial catalog compact. Runtime keys are source text.
  const runtime = Object.fromEntries(Object.entries(dictionary).filter(([key]) => !/^[a-f0-9]{12}$/.test(key)));
  await writeFile(new URL('en.json',output),JSON.stringify(runtime,null,2)+'\n');
  await writeFile(new URL('en.mjs',output),'// Generated by scripts/build-math.mjs; edit scripts/math/english-*.mjs or .json.\nexport default '+JSON.stringify(runtime)+';\n');
  return messages.length;
}
