import { lesson as L, step as S, codeLink as C } from './lesson-format.mjs';

export const screenLessons = {
  'covariance-proof': L('从平均值定义证明', '为什么一个线性变换要在协方差左右各乘一次？', ['statistics','matrices'], [
    S('写出新均值', 'Y=AX+b；平均可以分配到加法，也可以把不变的 A、b 提到外面。有限样本时逐项求和就能验证。', "\\mu_Y=\\mathbb E[AX+b]=A\\mu_X+b"),
    S('新样本减去新均值', '同一个平移 b 被减掉了。协方差描述相对中心的形状，所以不关心中心平移到哪里。', "Y-\\mu_Y=AX+b-(A\\mu_X+b)=A(X-\\mu_X)"),
    S('按定义做外积，再求平均', '转置会倒转乘法顺序，所以右侧出现 Aᵀ 而不是 A。把固定矩阵移到期望号外面，内部就是原协方差。', "\\begin{aligned}\\operatorname{Cov}(Y)&=\\mathbb E[(Y-\\mu_Y)(Y-\\mu_Y)^T]\\\\&=\\mathbb E[A(X-\\mu_X)(X-\\mu_X)^TA^T]\\\\&=A\\Sigma_XA^T\\end{aligned}"),
    S('把矩阵语言翻回标量', '第 i、j 个输出的共同变化来自所有输入分量对的贡献。下面就是上一行的逐项展开，不是另加的一条定理。', "(\\Sigma_Y)_{ij}=\\sum_k\\sum_l A_{ik}(\\Sigma_X)_{kl}A_{jl}"),
  ], ['X 的二维协方差为 diag(1,4)，x 放大两倍、y 缩小一半。', "A=\\operatorname{diag}(2,1/2),\\qquad A\\Sigma_XA^T=\\operatorname{diag}(4,1)"],
  [C('toy-project','教学例子 Σ=0.12²I，因此 JΣJᵀ 可简化成 0.12²*(J@Jᵀ)。任意各向异性 Σ 不能这样简化。','A ↔ jacobian；@ ↔ 矩阵乘法；transpose(-1,-2) ↔ 转置最后两个维度')],
  '只有固定线性或仿射变换才精确。透视除法不是线性变换，下一式要先近似。', '一维尺度放大 3 倍，方差放大几倍？', '9 倍，因为偏移先乘 3，再平方。'),
  'projected-covariance': L('一阶近似 + 线性恒等式', '为什么 GS 屏幕椭圆是 J R Σ Rᵀ Jᵀ？', ['derivatives','statistics','matrices'], [
    S('先把中心和形状都转到相机坐标', '中心需要旋转加平移，形状只需要旋转。使用上一节的协方差恒等式。', "\\mu_c=R_{cw}\\mu+t_{cw},\\qquad \\Sigma_c=R_{cw}\\Sigma R_{cw}^T"),
    S('用中心附近的切线替代弯曲投影', '导数告诉我们很小的变化怎样传播。把三维点 X 写成中心加偏移；对每个输出保留一次变化，丢掉二次及更高阶变化。', "\\pi(X)=\\pi(\\mu_c)+J(X-\\mu_c)+O(\\|X-\\mu_c\\|^2)"),
    S('平移项不改变方差', '在线性近似里，π(μc) 是常数，J 是在中心算好的固定矩阵。因此屏幕形状用 JΣcJᵀ。再加 εI 表示额外的各向同性屏幕方差。', "C\\approx J\\Sigma_cJ^T+\\varepsilon I_2,\\qquad \\varepsilon=0.3\\ {\\rm pixel}^2"),
    S('把矩阵乘法改写成三个小向量', '若 Σ=∑ak akᵀ，令 dk=JRcw ak。分配乘法后，C 等于三条投影轴的外积之和。这正是 shader 的计算路线。', "C=\\sum_{k=1}^3\\mathbf d_k\\mathbf d_k^T+\\varepsilon I_2,\\quad a=\\sum d_{k,x}^2+\\varepsilon,\\quad b=\\sum d_{k,x}d_{k,y},\\quad c=\\sum d_{k,y}^2+\\varepsilon"),
    S('检查近似的边界', '当 Gaussian 的深度厚度相对中心深度很大，或靠近相机时，J 在整团内变化明显，一阶椭圆近似会变差。加 0.3 是过滤策略，不是透视几何必然出现的常数。', "\\mathbf d_1=(10,0)^T,\\quad\\mathbf d_2=(0,20)^T,\\quad\\mathbf d_3=(-3,-6)^T"),
  ], ['用前面的 J 和 Σc=diag(1,4,9)，分别投影长度为 1、2、3 的轴，再累加。', "C=\\begin{bmatrix}100+9+0.3&18\\\\18&400+36+0.3\\end{bmatrix}=\\begin{bmatrix}109.3&18\\\\18&436.3\\end{bmatrix}"],
  [C('covariance','shader 保留 cov_a、cov_b、cov_c 三个独立元素，没有先分配一个 3×3 矩阵。','dk ↔ d0,d1,d2；ε ↔ +0.3')],
  '屏幕上“标准差增加 0.3”和“方差增加 0.3”完全不同。当前实现是后者，也没有配套做积分能量补偿。', '为什么主点 cx、cy 不出现在 C 里？', '它们只平移投影中心，求导后为 0，不改变局部形状。'),
  'homogeneous-derivative': L('分式通分 → 方向导数', 'WGSL 没写 fx/z，怎样确认它算的仍是同一个 Jacobian？', ['derivatives','matrices'], [
    S('给中心和方向加上不同的末位', '中心 h=PV[μ,1]；轴方向 δh=PV[a,0]。沿轴走一个小量 η 后，clip 坐标就是 h+ηδh，因为矩阵乘法是线性的。', "h(\\eta)=h+\\eta\\delta h,\\qquad n_x(\\eta)=\\frac{h_x+\\eta\\delta h_x}{h_w+\\eta\\delta h_w}"),
    S('先相减再通分', '分子里的 hx hw 抵消；剩下两项都含 η，和差商分母中的 η 约掉。', "\\frac{n_x(\\eta)-n_x(0)}{\\eta}=\\frac{(h_x+\\eta\\delta h_x)h_w-h_x(h_w+\\eta\\delta h_w)}{\\eta h_w(h_w+\\eta\\delta h_w)}=\\frac{\\delta h_xh_w-h_x\\delta h_w}{h_w(h_w+\\eta\\delta h_w)}"),
    S('把 η 缩到 0，y 同理', '这里需要 hw 非零。把 x、y 两个结果拼成向量，就是 shader 的分子与分母。', "D(h_{xy}/h_w)[\\delta h]=\\frac{\\delta h_{xy}h_w-h_{xy}\\delta h_w}{h_w^2}"),
    S('从 NDC 换到像素', 'NDC 横向从 −1 到 +1 跨 2 个单位，对应宽度 W，故乘 W/2。WebGPU 屏幕原点在左上，实际向下的像素 y 要乘 −H/2；shader 采用向上的内部屏幕坐标，乘 +H/2。两种坐标用 F 翻转转换，整个椭圆和偏移一起翻转，二次型不变。', "\\mathbf d_{\\uparrow}=\\operatorname{diag}(W/2,H/2)\\delta\\mathbf n,\\quad F=\\operatorname{diag}(1,-1),\\quad C_{\\downarrow}=FC_{\\uparrow}F^T,\\quad \\mathbf d_{\\downarrow}=F\\mathbf d_{\\uparrow}"),
    S('顶点回到 clip 坐标时为什么又乘 w', '想让透视除法后的 NDC 多 δn，就在 clip.xy 里加 δn·hw；除以 hw 后恰好剩 δn。中心 w 对四个角相同，local 的透视插值在这张 billboard 内也就是线性插值。', "\\frac{h_{xy}+\\delta n\\,h_w}{h_w}=\\frac{h_{xy}}{h_w}+\\delta n"),
  ], ['hx=2、hw=4、δhx=1、δhw=0.5、W=800。', "\\delta n_x=\\frac{1\\cdot4-2\\cdot0.5}{16}=\\frac3{16},\\qquad d_x=400\\cdot\\frac3{16}=75\\ {\\rm pixel}"],
  [C('projected-axis','公式的每一项在 projected_axis 中都有同名值。max(w²,1e−8) 是数值保护，中心背面的剔除另由 CPU 完成。','h ↔ center_clip；δh ↔ axis_clip'), C('quad','pixel_offset 先变成 ndc_offset，再乘 center_clip.w 加回 clip.xy。','δn ↔ ndc_offset')],
  '符号不能一半使用向下的像素坐标，一半使用向上的投影轴。坐标换基需要同时作用于中心、偏移、协方差。', '轴的齐次末位为什么是 0？', '它是方向，不是点。末位为 0 才不会把相机平移重复加进轴向量。'),
  conic: L('解两组二元一次方程', '不背口诀，也能得到 2×2 逆矩阵。', ['matrices'], [
    S('把逆矩阵的第一列设成未知数', 'C 乘逆矩阵的第一列应得到 (1,0)。这就是两条一次方程。', "\\begin{bmatrix}a&b\\\\b&c\\end{bmatrix}\\begin{bmatrix}u\\\\v\\end{bmatrix}=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\quad\\Longrightarrow\\quad au+bv=1,\\quad bu+cv=0"),
    S('消元解出第一列', '第一式乘 c，第二式乘 b，相减得到 (ac−b²)u=c。类似消掉 u 可解出 v。令 D=ac−b²。', "D=ac-b^2,\\qquad u=\\frac cD,\\qquad v=-\\frac bD"),
    S('解第二列，再拼回去', '右侧换成 (0,1)，同样消元得到 (−b/D,a/D)。现在把两列排在一起，就得到 Q。', "Q=\\frac1D\\begin{bmatrix}c&-b\\\\-b&a\\end{bmatrix},\\qquad CQ=\\frac1D\\begin{bmatrix}ac-b^2&0\\\\0&ac-b^2\\end{bmatrix}=I"),
    S('为什么要求正定', '把 ax²+2bxy+cy² 配方；要让任何非零方向都为正，需要 a>0 且 c−b²/a>0，也就是 D>0。', "ax^2+2bxy+cy^2=a\\left(x+\\frac ba y\\right)^2+\\frac Da y^2"),
  ], ['C=[[4,1],[1,2]]，D=8−1=7。', "Q=\\frac17\\begin{bmatrix}2&-1\\\\-1&4\\end{bmatrix}"],
  [C('toy-kernel','PyTorch 使用 linalg.inv 显式求逆；GPU 通过特征轴局部坐标得到相同距离，下一节解释这条连接。','Q ↔ inverse；D ↔ det(C)')],
  'D 很小时数值误差会被除法放大。不是任何三个数 a,b,c 都能作为有效椭圆。', 'C=diag(4,9) 的逆是什么？', 'Q=diag(1/4,1/9)，不是 diag(−4,−9)。'),
  'pixel-weight': L('椭圆换坐标的等价式', 'CPU 的 dᵀQd 怎样变成 WGSL 的 dot(local,local)？', ['vectors','matrices','exp'], [
    S('把像素改写为离中心的偏移', '像素位置 p 与投影中心必须用同一个屏幕坐标系。离中心远近不能直接用世界距离。', "\\mathbf d=\\mathbf p-\\mu_{2D},\\qquad r^2=\\mathbf d^TQ\\mathbf d"),
    S('先把矩阵乘法完全展开', 'Q 对称，所以中间两项相同，可以合并为 2Q12 dxdy；不是只剩一项。', "r^2=Q_{11}d_x^2+2Q_{12}d_xd_y+Q_{22}d_y^2"),
    S('在椭圆自己的两条主轴上计量', 'C=U diag(λ₁,λ₂)Uᵀ，U 的列是互相垂直的单位轴。先用 Uᵀ 转到主轴坐标，再除以标准差 √λ；得到 local。', "\\mathbf l=\\operatorname{diag}(\\lambda_1^{-1/2},\\lambda_2^{-1/2})U^T\\mathbf d,\\qquad \\mathbf l^T\\mathbf l=\\mathbf d^TU\\operatorname{diag}(\\lambda_1^{-1},\\lambda_2^{-1})U^T\\mathbf d=\\mathbf d^TC^{-1}\\mathbf d"),
    S('让两个三角形替我们插值 local', '顶点放在主轴各 ±3σ 的矩形角上，并赋 local=corner×3。光栅化后，每个片元收到自己的连续局部坐标，所以直接 dot(local,local) 就能得到 r²。', "\\mathbf d=U\\operatorname{diag}(\\sqrt{\\lambda_1},\\sqrt{\\lambda_2})\\mathbf l,\\qquad \\alpha=o(t)e^{-\\|\\mathbf l\\|^2/2}"),
    S('再把实际分支写清楚', 'shader 把 alpha 截到 0.99，低于 1/255 时丢弃；矩形外没有片元。只有未触发轴长度限幅时，这个 local 才精确对应原始 C。', "\\alpha_{\\rm cap}=\\min(0.99,\\alpha),\\qquad \\alpha_{\\rm cap}<1/255\\Rightarrow\\text{discard}"),
  ], ['C=diag(4,1)，像素偏移 (2,1)，o=0.8。', "\\mathbf l=(2/2,1/1)=(1,1),\\quad r^2=2,\\quad \\alpha=0.8e^{-1}\\approx0.294304"],
  [C('fragment','这里没有 inv(C)，因为逆变换已经隐含在顶点给出的 local 和片元插值中。','local ↔ l；power ↔ −r²/2'), C('quad','major_axis、minor_axis 构成 U，sigma_major/minor 是 √λ。','corner*3 ↔ 顶点处 l')],
  'local 不是 UV 纹理坐标，也不是世界坐标。它的单位是标准差，中心为 0。', 'local=(0,0) 时 alpha 一定等于 1 吗？', '不一定。空间核为 1，但仍要乘时间权重和基础 opacity，并受 0.99 上限限制。'),
  eigenvalues: L('二次方程 + 换坐标', '从 a,b,c 求出椭圆的长短轴。', ['quadratic','matrices'], [
    S('寻找变换后方向不变的向量', '若 Cv=λv，v 的方向不变，只拉伸 λ 倍；这就是特征向量和特征值的定义。把右侧移到左侧。', "(C-\\lambda I)\\mathbf v=0,\\qquad C-\\lambda I=\\begin{bmatrix}a-\\lambda&b\\\\b&c-\\lambda\\end{bmatrix}"),
    S('什么时候有非零的解', '两条方程必须不独立，否则只能 v=0；二维时条件就是行列式为 0。展开后得到普通二次方程。', "(a-\\lambda)(c-\\lambda)-b^2=0\\quad\\Longrightarrow\\quad\\lambda^2-(a+c)\\lambda+(ac-b^2)=0"),
    S('使用配方法求根', '把上一式的 s=a+c、p=ac−b² 代入基础课求根公式。判别式化简为 (a−c)²+4b²。', "\\lambda_\\pm=\\frac{a+c\\pm\\sqrt{(a+c)^2-4(ac-b^2)}}2=\\frac{a+c\\pm\\sqrt{(a-c)^2+4b^2}}2"),
    S('解出方向并归一化', '第一行是 (a−λ)vx+bvy=0，取 (vx,vy)=(b,λ−a) 恰好满足。除以长度得到单位轴；另一轴垂直于它。b=0 时按 a、c 的大小选坐标轴。', "\\mathbf u_+=\\frac{(b,\\lambda_+-a)^T}{\\sqrt{b^2+(\\lambda_+-a)^2}},\\qquad \\mathbf u_-=(-u_{+,y},u_{+,x})^T"),
    S('方差开平方才是长度', '在特征轴坐标中二次型是 ξ₁²/λ₁+ξ₂²/λ₂。令它等于 k²，就得到椭圆半轴长度 k√λ。', "\\frac{\\xi_1^2}{\\lambda_1}+\\frac{\\xi_2^2}{\\lambda_2}=k^2\\qquad\\Rightarrow\\qquad r_1=k\\sqrt{\\lambda_1},\\quad r_2=k\\sqrt{\\lambda_2}"),
  ], ['C=[[4,1],[1,2]]；λ±=3±√2。', "\\lambda_+\\approx4.414214,\\quad\\lambda_-\\approx1.585786,\\quad (3\\sigma_+,3\\sigma_-)\\approx(6.303009,3.777840)"],
  [C('ellipse','discriminant、lambda_major/minor 按这一求根式计算。GPU 还把 λ 下限设为 0.1、σ 上限设为 192 像素，属于实现保护。','λ± ↔ lambda_major/minor；u± ↔ major_axis/minor_axis')],
  '若 C=aI，两条轴一样长，任何正交方向都成立。此时不要归一化零向量 (b,λ−a)。', 'C=diag(9,4)，3σ 椭圆半轴多长？', '9 和 6 像素：先开平方得到 3、2，再乘 3。'),
  support: L('解指数不等式', 'alpha 小到可以忽略时，到底能截掉多远？', ['exp'], [
    S('写出保留像素的条件', '设阈值 αmin>0，先忽略 clamp。o 是当前时间的峰值 opacity，r² 非负。', "o\\,e^{-r^2/2}\\ge\\alpha_{\\mathrm{min}}"),
    S('先检查有没有解', '核的最大值为 1，因此若 o<αmin，连中心都达不到阈值，整个 Gaussian 可跳过。否则除以正数 o。', "o\\ge\\alpha_{\\mathrm{min}}>0\\quad\\Longrightarrow\\quad e^{-r^2/2}\\ge\\frac{\\alpha_{\\mathrm{min}}}o"),
    S('取对数，再乘负数', 'ln 单调递增，不等号不变；乘 −2 时不等号要反向。', "-\\frac{r^2}{2}\\ge\\ln\\frac{\\alpha_{\\mathrm{min}}}o\\quad\\Longrightarrow\\quad r^2\\le2\\ln\\frac o{\\alpha_{\\mathrm{min}}}"),
    S('区分理论支持域和实际矩形', '精确阈值边界在 local 空间是半径 rmax 的圆，回到屏幕是椭圆。当前 shader 画的是每个主轴 ±3σ 的矩形，再在片元里按 alpha 丢弃，因此两者并不相等。', "o=0.8,\\ \\alpha_{\\mathrm{min}}=1/255:\\quad r_{\\mathrm{max}}=\\sqrt{2\\ln204}\\approx3.261303"),
  ], ['轴向 local=(3.1,0) 的 alpha 仍超过阈值，但超出当前 ±3 的 quad，没有片元；这显示真实的截断近似。', "0.8e^{-3.1^2/2}\\approx0.006551>1/255\\approx0.003922"],
  [C('quad','corner×3 确定实际几何覆盖范围；它不是上述阈值公式的计算结果。','±3σ ↔ pixel_offset 中的 3.0'), C('fragment','alpha 低于阈值后 discard，两个判断共同决定最终覆盖。','αmin ↔ 0.0039215686')],
  '“3σ 包含所有有效像素”不成立。大 opacity 下仍可能裁掉高于阈值的尾部。', 'o 正好等于 αmin 时，数学上哪里还能保留？', '只有 r=0 的中心；实际像素网格可能没有采样点正好落在中心。'),
};
