import { lesson as L, step as S, codeLink as C } from './lesson-format.mjs';

export const timeLessons = {
  transmittance: L('剩余比例的连乘', '光到达第 i 层时，还剩下多少？', ['vectors'], [
    S('把每层理解为覆盖一部分的薄片', 'alpha 为 0.2，就有 20% 被这层覆盖，80% 继续往后。先用这个透明合成模型建立直觉，它不要求场景真的是玻璃。', "T_1=1,\\qquad T_2=1-\\alpha_1"),
    S('下一层只作用于上一层剩下的部分', '若第二层也覆盖 20%，它覆盖的不是原始光的 20%，而是剩余 80% 的 20%。', "T_3=(1-\\alpha_1)(1-\\alpha_2)"),
    S('重复这一规则', '到达第 i 层之前已经穿过 i−1 层；∏ 是把这些剩余比例全部相乘。', "T_{i+1}=T_i(1-\\alpha_i),\\qquad T_i=\\prod_{j<i}(1-\\alpha_j)"),
    S('解释训练代码为什么先补一个 1', 'cumprod 得到前缀连乘。需要的是当前层之前的连乘，因此数组前面补 1，再丢掉最后一项。', "[\\alpha_1,\\alpha_2]=[0.2,0.5]\\Rightarrow[T_1,T_2,T_3]=[1,0.8,0.4]"),
  ], ['两层 alpha 都是 0.5，第二层得到的光为 0.5，背景得到 0.25。', "T_2=0.5,\\qquad T_3=0.5\\cdot0.5=0.25"],
  [C('toy-composite','先近后远排列 alpha，沿 Gaussian 维度 cumprod；[:, :-1] 取到当前层之前的透射率。','Ti ↔ transmittance；dim=1 ↔ Gaussian 维')],
  'Ti 不含当前层 alpha；否则会把当前层遮挡自己一次。', '若第一层 alpha=1，后面的 Ti 是多少？', '全部为 0；当前 shader 把单层 alpha 限到 0.99，因此实际不会由单层直接得到精确的 0。'),
  composite: L('加权相加 + 望远镜求和', '每层与背景怎样一起组成最终像素？', ['vectors'], [
    S('先看一层和背景', '当前层占 alpha，其余部分透出背景。RGB 三个通道分别做同样的运算。', "\\mathbf C=\\alpha_1\\mathbf c_1+(1-\\alpha_1)\\mathbf c_{\\rm bg}"),
    S('把背景换成后面的一整幅合成结果', '两层时先用第二层和背景合成 B1，再把 B1 放到第一层后面。展开括号。', "\\mathbf C=\\alpha_1\\mathbf c_1+(1-\\alpha_1)\\alpha_2\\mathbf c_2+(1-\\alpha_1)(1-\\alpha_2)\\mathbf c_{\\rm bg}"),
    S('推广到 N 层', '第 i 层之前必须穿过前 i−1 层，所以颜色权重为 Ti αi；背景的权重是穿过全部层的 TN+1。', "\\mathbf C=\\sum_{i=1}^N T_i\\alpha_i\\mathbf c_i+T_{N+1}\\mathbf c_{\\rm bg}"),
    S('用权重和检查有没有漏项', 'Ti αi=Ti−Ti+1；求和时中间项抵消，只剩 1−TN+1。加上背景正好为 1。', "\\sum_i T_i\\alpha_i+T_{N+1}=\\sum_i(T_i-T_{i+1})+T_{N+1}=T_1=1"),
  ], ['红在前、蓝在后，两层 alpha=0.5，黑色背景。', "\\mathbf C=0.5(1,0,0)+0.25(0,0,1)+0.25(0,0,0)=(0.5,0,0.25)"],
  [C('toy-composite','代码对 T*alpha*color 沿 Gaussian 维求和，背景为黑，所以省略了数值为 0 的背景项。','C ↔ return；N ↔ 张量 dim=1')],
  '交换层次会改变颜色。中心深度排序只是该实现的近似；相交的大 Gaussian 不保证每个像素的遮挡都准确。', '为什么权重不一定加起来等于 1？', '如果只看 Gaussian 权重，和为 1−剩余透射率；把背景权重加进去才等于 1。'),
  premultiplied: L('同一合成式的 GPU 写法', '为什么 fragment 输出 RGB×alpha，混合状态却用 One？', ['vectors'], [
    S('定义预乘颜色', '把颜色与它的覆盖率先乘好，记作 c̃。这样透明黑和普通黑在存储时也有一致的含义。', "\\widetilde{\\mathbf c}=\\alpha\\mathbf c"),
    S('把后面已经画好的结果当 destination', '远处先画，当前较近的一层为 source。它留下自己的预乘颜色，并遮掉 destination 的 alpha 比例。', "\\widetilde{\\mathbf c}_{\\rm out}=\\widetilde{\\mathbf c}_s+(1-\\alpha_s)\\widetilde{\\mathbf c}_{\\rm dst}"),
    S('映射到固定混合硬件的两个乘数', '硬件计算 src×srcFactor + dst×dstFactor。于是 srcFactor=One，dstFactor=OneMinusSrcAlpha。alpha 通道也按 over 规则累积。', "\\alpha_{\\rm out}=\\alpha_s+(1-\\alpha_s)\\alpha_{\\rm dst}"),
    S('与近到远公式核对', '先画远处蓝，再画近处红；展开正好得到上一式的红 0.5、蓝 0.25。顺序不同，代数结果一致。', "\\widetilde{\\mathbf c}_{\\rm blue}=0.5(0,0,1),\\quad \\widetilde{\\mathbf c}_{\\rm out}=0.5(1,0,0)+0.5\\,\\widetilde{\\mathbf c}_{\\rm blue}"),
  ], ['若 shader 已输出红色 (0.5,0,0)，却又配置 SrcAlpha=0.5，会错误地再乘一次。', "0.5\\times0.5=0.25\\ne0.5"],
  [C('fragment','返回值 vec4(rgb*alpha,alpha) 明确是预乘。','c̃s ↔ input.color_opacity.rgb*alpha'), C('blend','PREMULTIPLIED_ALPHA_BLENDING 与这份输出匹配；StgPass 按远到近排序，透明 splat 不写深度。','over ↔ blend state；顺序 ↔ sort_unstable_by')],
  '透明混合一般要禁用 Gaussian 自身的深度写入。与不透明场景的深度测试是另一个独立开关。', '预乘颜色仍要乘 Ti 吗？', '逐层 GPU over 已经隐式完成遮挡；若在手写近到远累积器里，则仍需乘到达该层的 Ti。'),
  'volume-bridge': L('薄层极限，非精确 GS 射线积分', '连续密度为什么会产生指数透射率？', ['integral','exp'], [
    S('把一段路切成 N 个薄层', '密度 σ 表示单位长度上的消光强度；薄层厚 Δs 足够小时，透过比例约为 1−σΔs。把总长度 l 平分。', "T_N=\\left(1-\\sigma\\frac lN\\right)^N"),
    S('让薄层越来越薄', '基础极限 (1+a/N)ᴺ→eᵃ，取 a=−σl。常密度下就得到指数透过率；被覆盖比例是 1−T。', "T=e^{-\\sigma l},\\qquad \\alpha=1-e^{-\\sigma l}"),
    S('密度沿路径变化时分别连乘', '取对数把乘法变加法，利用 ln(1−ε)≈−ε，再把细分求和变成积分。', "\\ln T\\approx-\\sum_j\\sigma(s_j)\\Delta s\\ \\longrightarrow\\ -\\int_{s_0}^s\\sigma(u)\\,du"),
    S('回到离散渲染的每一段', '每段内部假定密度固定，就用该段长度 Δsi 得到 alpha。相邻段按剩余比例相乘，因此和前面的合成模型接上。', "T(s)=\\exp\\left[-\\int_{s_0}^s\\sigma(u)\\,du\\right],\\qquad \\alpha_i=1-e^{-\\sigma_i\\Delta s_i}"),
  ], ['σ=2 /米，一段长 0.5 米，乘积 σΔs 没有单位。', "T=e^{-1}\\approx0.367879,\\qquad \\alpha=1-e^{-1}\\approx0.632121"],
  [C('fragment','对照源码可见，当前 renderer 直接计算 opacity*投影 Gaussian 核，没有沿每条光线积分 σ。这里只解释透明合成与体渲染的关系。','本式 σ、Δs：当前 STG-Lite shader 没有对应字段')],
  '不能把 learned opacity 当作物理消光密度 σ；两者参数、单位和积分过程不同。', '若把一段恒密度路程平分两半，总透过率会变吗？', '不会。e^(−σl/2)×e^(−σl/2)=e^(−σl)。'),
  'time-domain': L('单位换算', '视频的秒、帧号、模型时间如何对齐？', ['derivatives'], [
    S('先确定时间起点和尺度', '物理时刻 s 减去起点 s0，得到经过的秒数；除以 D 秒，得到无单位的模型时间 t。D 必须来自训练约定。', "t=\\frac{s-s_0}{D},\\qquad s=s_0+Dt"),
    S('再对齐每个 Gaussian 自己的中心时刻', 'τ 是该 Gaussian 最活跃的模型时间。运动系数围绕 τ 展开，所以实际使用 Δt=t−τ。', "\\Delta t=\\frac{s-s_0}{D}-\\tau"),
    S('帧号需要匹配分母约定', '若训练器定义 t=j/N，帧率为 fps，则 s−s0=j/fps，与 D=N/fps 对齐；最后一帧 t=(N−1)/N，不等于 1。若定义 j/(N−1)，D 则不同。', "\\frac{j/fps}{N/fps}=\\frac jN"),
    S('沿代码找到时间只被换算一次', '浏览器 baseline 的 10 秒循环是播放约定，不能据此认定数据真实时长为 10 秒。原生 StgPass 直接接收 normalized_time，不做秒数推断。', "s=2,\\ s_0=0,\\ D=10,\\ \\tau=0.5\\Rightarrow t=0.2,\\ \\Delta t=-0.3"),
  ], ['若有 100 帧、25fps，并采用 j/N，第 50 帧的模型时间为 0.5。', "D=100/25=4\\ {\\rm s},\\qquad t=(50/25)/4=0.5"],
  [C('browser-time','当前 LOOP_SECONDS=10，用 rem_euclid 后除以它；这只描述播放器速度。','s ↔ time_seconds；D ↔ LOOP_SECONDS'), C('host-camera','原生接入显式传归一化时间；prepare 检查 0..1。','t ↔ normalized_time → camera.scene.x')],
  'PLY 的 32 个浮点字段没有 fps 和 capture duration，不能只看模型文件猜秒数。', '同一个模型以两倍播放速度播放，运动系数需要改吗？', '不需要；改变输入 t 随真实时间推进的速度即可。若重新定义模型时间坐标本身，则系数必须换算。'),
  'temporal-rbf': L('时间核的模型选择', '为什么有的时间 Gaussian 指数没有 1/2？', ['exp'], [
    S('定义到活跃时刻的相对距离', 'Δt=t−τ；ρ 是宽度。先除以宽度再平方，时间单位约掉。STG-Lite 采用 exp(−距离²) 作为可见性包络。', "r_t=\\frac{t-\\tau}{\\rho},\\qquad w(t)=e^{-r_t^2}"),
    S('用 log-width 保证宽度为正', 'PLY 保存 ℓτ，不是 ρ 本身。与空间 log-scale 类似，先 exp 解码。官方论文用另一种系数 sτ 乘在平方前，二者可直接换算。', "\\rho=e^{\\ell_\\tau},\\qquad w=e^{-\\Delta t^2/\\rho^2}=e^{-s_\\tau\\Delta t^2},\\qquad s_\\tau=\\rho^{-2}"),
    S('和标准 Gaussian 的宽度比较', '两个指数表示相同曲线时，平方项系数必须相等。注意这里的 ρ 不等于标准差 σt。', "\\frac1{\\rho^2}=\\frac1{2\\sigma_t^2}\\quad\\Longrightarrow\\quad\\sigma_t=\\frac{\\rho}{\\sqrt2}"),
    S('把基础不透明度乘上时间权重', '基础 opacity 表示最高可见程度；时间核只把它衰减。在中心时刻 w=1，离开中心一倍 ρ 时 w=e⁻¹。', "o(t)=\\operatorname{sigmoid}(\\beta)w(t),\\quad w(\\tau)=1,\\quad w(\\tau+\\rho)=e^{-1}"),
  ], ['τ=0.5，ρ=0.25，t=0.75，β=0。', "\\Delta t=0.25,\\qquad w=e^{-1}\\approx0.367879,\\qquad o(t)=0.5w\\approx0.183940"],
  [C('activation','注意 temporal_opacity 的指数没有 0.5；fragment 的空间 power 才有 −0.5。','ρ ↔ temporal_scale；w ↔ temporal_opacity；o(t) ↔ opacity')],
  '两个指数的 1/2 不能为了统一外观而互相抄。时间宽度字段也不是训练录像的总时长。', '把 ρ 加倍，在同样 Δt 下指数平方项变成几分之一？', '四分之一；时间包络因此变宽。'),
  trajectory: L('多项式模型', '把随时间移动的中心拆成可存储的系数。', ['vectors'], [
    S('从静止模型开始', '如果只保存 μ0，任意时刻位置都相同。这里 μ0 表示 t=τ 时的中心，并非一定是视频第一帧的位置。', "\\mu(\\tau)=\\mu_0"),
    S('加上一次运动', '每经过一个模型时间单位，增加 m1。三维中每个系数都是 x、y、z 三个数。', "\\mu(t)=\\mu_0+\\mathbf m_1\\Delta t"),
    S('加上弯曲和更灵活的变化', '二次项让速度随时间变，三次项让加速度随时间变。这是有限阶模型选择；不要求真实运动必然是三次曲线。', "\\mu(t)=\\mu_0+\\mathbf m_1\\Delta t+\\mathbf m_2\\Delta t^2+\\mathbf m_3\\Delta t^3"),
    S('逐坐标代数计算', '对 x 分量先平方、立方，再乘各自系数，最后相加；y、z 一样。三次轨迹也可用 Horner 顺序少做乘法，但当前 shader 直接算 dt2 方便复用。', "\\mu_x(t)=\\mu_{0x}+\\Delta t\\big(m_{1x}+\\Delta t(m_{2x}+\\Delta t\\,m_{3x})\\big)"),
  ], ['μ0=(1,2,10)，m1=(2,0,0)，m2=(0,4,0)，m3=(0,0,8)，Δt=0.5。', "\\mu=(1,2,10)+(1,0,0)+(0,1,0)+(0,0,1)=(2,3,11)"],
  [C('motion','9 个 motion 浮点跨越 vec4 边界，所以 quadratic 和 cubic 要重新拼接。','m1 ↔ r2.xyz；m2 ↔ (r2.w,r3.x,r3.y)；m3 ↔ (r3.z,r3.w,r4.x)'), C('cpu-sample','CPU 使用同一轨迹来剔除和排序；GPU 使用它来摆放 quad，两边必须一致。','μ(t) ↔ position / center')],
  'm2 不是加速度本身，m3 也不是三阶导数本身；还差求导产生的倍数。', 'Δt=0 时 motion 再大，中心是什么？', '仍是 μ0，因为所有非零阶项都乘了 0。'),
  velocity: L('多项式求导 + 单位换算', '运动系数和实际速度、加速度差在哪？', ['derivatives','chain'], [
    S('从差商验证平方、立方规则', '基础课已经用展开证明：t² 的导数是 2t，t³ 是 3t²。τ 固定时，Δt 对 t 的导数为 1。', "\\frac{d\\Delta t}{dt}=1,\\qquad \\frac{d\\Delta t^2}{dt}=2\\Delta t,\\qquad \\frac{d\\Delta t^3}{dt}=3\\Delta t^2"),
    S('每一项分别求导后相加', 'μ0 是常数，导数为 0；向量系数不变，对每个分量独立做相同运算。', "\\frac{d\\mu}{dt}=\\mathbf m_1+2\\mathbf m_2\\Delta t+3\\mathbf m_3\\Delta t^2"),
    S('再求一次导数', '在中心时刻 Δt=0，加速度为 2m2；三阶导数为 6m3。因此若从速度、加速度、jerk 写 Taylor 系数，会出现 1/2 和 1/6。', "\\frac{d^2\\mu}{dt^2}=2\\mathbf m_2+6\\mathbf m_3\\Delta t,\\qquad \\frac{d^3\\mu}{dt^3}=6\\mathbf m_3"),
    S('从模型时间换成秒', 't=(s−s0)/D，因此 dt/ds=1/D。链式法则告诉我们速度除以 D；加速度除以 D²。', "\\frac{d\\mu}{ds}=\\frac1D\\frac{d\\mu}{dt},\\qquad \\frac{d^2\\mu}{ds^2}=\\frac1{D^2}\\frac{d^2\\mu}{dt^2}"),
  ], ['上一例 Δt=0.5，模型时间速度为 (2,4,6)。若 D=10 秒且空间是米：', "\\frac{d\\mu}{ds}=(0.2,0.4,0.6)\\ {\\rm m/s}"],
  [C('motion','renderer 只求位置，没有显式求 velocity。需要运动矢量或诊断速度时，应从这些 motion 字段按本式计算；不要声称当前 pass 已输出速度。','导数来源 ↔ motion_linear/quadratic/cubic')],
  '空间单位不明确时只能说“世界单位/秒”，不能直接说米/秒。', 'D 加倍、模型不变，同一归一化时刻的物理速度怎样变？', '减半。'),
  'rotation-time': L('四维系数模型 + 归一化', '旋转随时间变化时，为什么先相加再 normalize？', ['vectors'], [
    S('先在四维系数空间里走直线', 'q0、ω 都有四个数，按分量计算 u=q0+Δtω。这里 ω 是四元数系数的变化，不是三维物理角速度。', "u_j(t)=q_{0j}+\\Delta t\\,\\omega_j,\\qquad j\\in\\{w,x,y,z\\}"),
    S('直线不保证仍在单位球面上', '即使 q0 是单位长度，相加后的 u 一般也不是。例如 (1,0,0,0)+(0,0,0,0.5) 的长度是 √1.25。', "\\|u\\|=\\sqrt{u_w^2+u_x^2+u_y^2+u_z^2}"),
    S('除以长度，回到单位四元数', '每项都除以同一个数，平方和就变成 1。要求 u≠0；归一化后送进前面的旋转矩阵。', "q=\\frac u{\\|u\\|},\\qquad \\|q\\|^2=\\frac{\\sum_j u_j^2}{\\|u\\|^2}=1"),
    S('理解角度速度不恒定', '归一化把系数直线投到单位球面，因此角度一般非线性变化。这个模型不是 SLERP，也不自动满足刚体角速度微分方程。', "q_0=(1,0,0,0),\\ \\omega=(0,0,0,1):\\quad q(t)=\\frac{(1,0,0,\\Delta t)}{\\sqrt{1+\\Delta t^2}}"),
  ], ['Δt=0.5 时 q≈(0.894427,0,0,0.447214)，对应绕 z 旋转约 53.13°。', "\\theta=2\\arctan(0.5)\\approx53.130^\\circ"],
  [C('activation','normalize(splat.r6 + dt*splat.r7) 正是这两步。loader 的有限值检查并不保证所有时刻 u 的范数非零；资产需满足这个前提。','q0 ↔ r6；ω ↔ r7；q ↔ quaternion')],
  '当前 shader 没有为 u=0 定义有效旋转。解释这个公式必须写出非零范数条件，不能只说 normalize 永远安全。', 'ω=0 时旋转会随时间变化吗？', '不会；始终是 normalize(q0)，前提 q0≠0。'),
  'normalization-gradient': L('逐分量求导，再组成矩阵', 'normalize 的梯度为什么会减掉 qqᵀ？', ['derivatives','chain','vectors'], [
    S('先给长度一个短名字', '令 r=||u||。因为 r²=∑uj²，两边对某个 uj 求偏导：2r ∂r/∂uj=2uj。', "\\frac{\\partial r}{\\partial u_j}=\\frac{u_j}{r}"),
    S('对 qi=ui/r 使用商法则', 'δij 在 i=j 时为 1，否则为 0。这只是 ui 对 uj 的偏导，不是神秘函数。', "\\frac{\\partial q_i}{\\partial u_j}=\\frac{\\delta_{ij}}r-\\frac{u_i}{r^2}\\frac{u_j}r=\\frac{\\delta_{ij}}r-\\frac{u_i u_j}{r^3}"),
    S('用 qi、qj 替换 ui/r、uj/r', '把所有 i,j 的项排成一张 4×4 表；对角的 δij 组成 I，qiqj 组成外积 qqᵀ。', "\\frac{\\partial q}{\\partial u}=\\frac{I-qq^T}{r}"),
    S('把时间这条链接上', 'u=q0+(t−τ)ω，所以 du/dt=ω。右乘 ω 得到 q 的时间变化率。若变化正好沿着 q，归一化会把它完全消掉。', "\\frac{dq}{dt}=\\frac{I-qq^T}{r}\\omega,\\qquad (I-qq^T)q=q-q(q^Tq)=0"),
  ], ['u=(2,0,0,0)，r=2，q=(1,0,0,0)。', "\\frac{\\partial q}{\\partial u}=\\operatorname{diag}(0,1/2,1/2,1/2)"],
  [C('activation','GPU 的 normalize 只有前向计算。此导数用于理解训练端自动微分，本仓库 toy trainer 固定旋转，未训练 q 或 ω。','前向 q ↔ quaternion；反向 Jacobian ↔ 教学数值检查')],
  'r 接近 0 时分母放大梯度。数学上可导不意味着当前渲染 pass 有 backward kernel。', '只把 u 整体乘一个略大的正数，q 会变吗？', '不会。沿径向的变化被 I−qqᵀ 消掉。'),
};
