import { formula, inline } from './lesson-format.mjs';
import { esc } from './notation.mjs';

// Keep each new explanation beside its English edition. The site-wide language
// switch uses this catalog without replacing controls, canvases, or formulas.
export const shTranslations = {};
const B = (zh,en) => { shTranslations[zh]=en; return esc(zh); };
const P = (zh,en) => '<p>'+B(zh,en)+'</p>';
const H = (zh,en) => '<h4>'+B(zh,en)+'</h4>';
const S = (zh,en,body) => '<li>'+H(zh,en)+body+'</li>';
const chapter = (id,zh,en,body,open=false) => '<details class="sh-chapter" id="'+id+'"'+(open?' open':'')+'><summary>'+B(zh,en)+'</summary><div>'+body+'</div></details>';
const viewControls = prefix => '<div class="sh-orbit-controls" id="'+prefix+'-view-controls" role="group" aria-label="'+B('3D 观察视角','3D viewing angle')+'"><div class="sh-orbit-presets">'+[
  ['reset','重置视角','Reset view'],['front','正面 −Y','Front −Y'],['side','侧面 +X','Side +X'],['top','顶部 +Z','Top +Z'],
].map(([value,zh,en])=>'<button type="button" data-view-preset="'+value+'">'+B(zh,en)+'</button>').join('')+'</div><label for="'+prefix+'-view-zoom">'+B('图示缩放','Plot zoom')+'<input id="'+prefix+'-view-zoom" type="range" min="0.6" max="1.5" step="0.05" value="1"></label><output id="'+prefix+'-view-status" data-i18n-dynamic></output></div>';
const formulae = [
  '\\frac{1}{\\sqrt{4\\pi}}',
  '-\\sqrt{\\frac{3}{4\\pi}}y', '\\sqrt{\\frac{3}{4\\pi}}z', '-\\sqrt{\\frac{3}{4\\pi}}x',
  '\\sqrt{\\frac{15}{4\\pi}}xy', '-\\sqrt{\\frac{15}{4\\pi}}yz', '\\sqrt{\\frac{5}{16\\pi}}(3z^2-1)',
  '-\\sqrt{\\frac{15}{4\\pi}}xz', '\\sqrt{\\frac{15}{16\\pi}}(x^2-y^2)',
  '-\\sqrt{\\frac{35}{32\\pi}}y(3x^2-y^2)', '\\sqrt{\\frac{105}{4\\pi}}xyz',
  '-\\sqrt{\\frac{21}{32\\pi}}y(5z^2-1)', '\\sqrt{\\frac{7}{16\\pi}}z(5z^2-3)',
  '-\\sqrt{\\frac{21}{32\\pi}}x(5z^2-1)', '\\sqrt{\\frac{105}{16\\pi}}z(x^2-y^2)',
  '-\\sqrt{\\frac{35}{32\\pi}}x(x^2-3y^2)',
];
const rows = formulae.map((f,k) => {
  const l=Math.floor(Math.sqrt(k)), m=k-l*l-l;
  return '<tr><td><code>'+k+'</code></td><td>'+inline('('+l+','+m+')')+'</td><td>'+inline(f)+'</td></tr>';
}).join('');

const coefficientControls = '<div class="sh-coefficient-controls"><h4 id="sh-coefficient-title" data-i18n-dynamic></h4><div class="sh-controls">'+['R','G','B'].map((ch,index)=>'<label for="sh-a-'+index+'">'+ch+'<output id="sh-a-value-'+index+'"></output><input id="sh-a-'+index+'" type="range" min="-2" max="2" step="0.01" value="0"></label>').join('')+'</div><button type="button" id="sh-zero">'+B('把这个基的 RGB 系数归零','Zero this basis\'s RGB coefficients')+'</button><p id="sh-inactive" class="sh-small" data-i18n-dynamic></p></div>';
const channelPlots = '<div class="sh-channel-grid">'+['R','G','B'].map((ch,index)=>
  '<figure class="sh-channel-card sh-channel-'+ch.toLowerCase()+'"><h5>'+B(ch+' 通道',ch+' channel')+'</h5><canvas id="sh-channel-'+index+'" width="360" height="320" role="img" tabindex="0" aria-describedby="sh-orbit-help sh-channel-help" aria-label="'+B('可旋转的 '+ch+' 通道方向球','Rotatable '+ch+' channel directional sphere')+'"></canvas><figcaption><output id="sh-channel-value-'+index+'" class="sh-channel-value"></output><span id="sh-channel-steps-'+index+'" class="sh-channel-steps" data-i18n-dynamic></span></figcaption></figure>'
).join('')+'<figure class="sh-channel-card sh-channel-combined"><h5>'+B('→ RGB 合成','→ RGB combined')+'</h5><canvas id="sh-color-canvas" width="360" height="320" role="img" tabindex="0" aria-describedby="sh-orbit-help sh-channel-help" aria-label="'+B('可旋转的 RGB 合成方向球','Rotatable combined RGB directional sphere')+'"></canvas><figcaption><span class="sh-combined-sample"><i id="sh-channel-swatch" aria-hidden="true"></i><output id="sh-combined-value" class="sh-channel-value"></output></span><span class="sh-channel-steps">'+B('把同一方向的 R、G、B 组成一个颜色','Combine R, G, and B from the same direction into one color')+'</span></figcaption></figure></div>';

export const shContent = '<div class="sh-deep-dive" id="sh-guide">'+
  '<div class="sh-intro"><span class="eyebrow">SPHERICAL HARMONICS / A VISUAL WORKSHOP</span><h3>'+B('球谐：给每个观察方向配一种颜色。','Spherical harmonics: a color for every viewing direction.')+'</h3>'+
  P('先想象站在同一个 Gaussian 周围，从上、下、左、右看它。它的形状可以不变，颜色却可以随视角变化。SH 用一组固定的“方向图案”，加上每个 Gaussian 自己学到的混合系数，保存这种变化。','Imagine viewing the same Gaussian from above, below, left, and right. Its shape can stay fixed while its color changes with your viewpoint. SH represents that change with fixed directional patterns and a set of mixture coefficients learned for each Gaussian.')+
  '<nav class="sh-jumps">'+[['#sh-lab','先玩图案和颜色','Explore patterns and colors'],['#sh-derivation','再一步步推导','Derive it step by step'],['#sh-reconstruction','看低阶近似的极限','See the limits of low degrees'],['#sh-code','接到 Rust / WGSL','Connect to Rust / WGSL']].map(([href,zh,en])=>'<a href="'+href+'">'+B(zh+' →',en+' →')+'</a>').join('')+'</nav></div>'+
  '<p class="sh-note"><a href="/?inspect=1#workbench">'+B('从真实 4D 场景选一颗 Gaussian，查看参数与 SH 实验 →','Pick a Gaussian in the real 4D scene: parameters and SH experiment →')+'</a></p>'+
  '<div class="sh-idea-grid">'+[
    ['01 · 图案 Y','01 · Pattern Y','像调音台里的固定音色。一个基函数输入方向，输出一个有正负的数；它本身不是 RGB。','Like a fixed tone on a mixing console. A basis function takes a direction and returns a signed number; it is not RGB by itself.'],
    ['02 · 系数 a','02 · Coefficient a','像每个音色的音量旋钮。每个图案有 R、G、B 三个系数，允许为负；它们是训练要学的参数。','Like a volume knob for each tone. Every pattern has three coefficients, R, G, and B. They may be negative; training learns them.'],
    ['03 · 求和 c','03 · Sum c','观察方向决定每个图案当前的数值。数值乘系数，再逐项相加，得到这颗 Gaussian 在这个视角下的颜色。','The viewing direction selects a value from each pattern. Multiply each value by its coefficients and add the contributions to get this Gaussian\'s color from that view.'],
  ].map(([zh,en,body,eng])=>'<article><h4>'+B(zh,en)+'</h4>'+P(body,eng)+'</article>').join('')+'</div>'+

  '<section class="sh-workshop" id="sh-lab" aria-labelledby="sh-lab-title"><h3 id="sh-lab-title">'+B('实验一 · 16 张图案，怎样调出颜色？','Experiment 1 · How do 16 patterns make a color?')+'</h3>'+
  P('先点击一个小图案，再拖动它的 RGB 系数。橙色表示基函数为正，蓝色表示为负，灰色接近零。切换到“球面着色”时，球的半径完全不变；“瓣状图”才用离中心的距离表示绝对值。','Click a small pattern, then adjust its RGB coefficients. Orange means a positive basis value, blue a negative value, and gray near zero. In sphere-color mode the radius stays fixed. In lobe mode the distance from the center encodes the absolute value.')+
  '<div class="sh-controls"><label>'+B('图案显示','Pattern display')+'<select id="sh-shape"><option value="lobes">'+B('瓣状图 · 半径 = |Y|','Lobes · radius = |Y|')+'</option><option value="sphere">'+B('球面着色 · 固定半径','Sphere colors · fixed radius')+'</option></select></label><label>'+B('最高阶 L','Maximum degree L')+'<select id="sh-degree">'+[0,1,2,3].map(l=>'<option value="'+l+'"'+(l===3?' selected':'')+'>L = '+l+' · '+(l+1)**2+' RGB</option>').join('')+'</select></label><label>'+B('载入一个例子','Load an example')+'<select id="sh-preset"><option value="mixed">'+B('混合：零阶到三阶','Mixed: degrees 0–3')+'</option><option value="dc">'+B('只有 DC：各方向同色','DC only: identical in every direction')+'</option><option value="first">'+B('一阶：两侧不同色','Degree 1: different colors on opposite sides')+'</option><option value="second">'+B('二阶：多一组明暗分区','Degree 2: additional light and dark regions')+'</option><option value="custom" disabled>'+B('手动调整','Custom coefficients')+'</option></select></label></div>'+
  '<div class="sh-gallery" id="sh-gallery">'+[0,1,2,3].map(l=>'<div class="sh-band"><div class="sh-band-label">'+inline('\\ell='+l)+' <span>'+(2*l+1)+'</span></div><div class="sh-band-cards">'+Array.from({length:2*l+1},(_,j)=>{const k=l*l+j,m=j-l;return '<button class="sh-basis-card" type="button" data-basis="'+k+'" aria-pressed="'+(k===6)+'" aria-label="'+B('选择球谐基 '+k,'Select SH basis '+k)+'"><canvas width="180" height="156" aria-hidden="true"></canvas><span>'+inline('Y_{'+l+','+m+'}')+'</span><small>k = '+k+'</small></button>';}).join('')+'</div></div>').join('')+'</div>'+
  '<p class="sh-legend"><span class="sh-positive">'+B('正值 +','Positive +')+'</span><span class="sh-negative">'+B('负值 −','Negative −')+'</span><span>'+B('每张图各自缩放以看清形状，不能用瓣的大小比较不同基函数的数值。','Each plot is scaled independently for legibility; lobe sizes do not compare magnitudes across basis functions.')+'</span></p>'+
  viewControls('sh')+
  '<p id="sh-orbit-help" class="sh-orbit-help">'+B('拖动基函数图或下方任一通道球，五张图会一起旋转。可观察背面、顶部与底部；聚焦图后也可用方向键旋转、+/− 缩放、Home 重置。','Drag the basis plot or any channel sphere below to rotate all five plots together. Inspect the back, top, and underside; with a plot focused, use arrow keys to rotate, +/− to zoom, and Home to reset.')+'</p>'+
  '<div class="sh-view-grid"><figure><canvas id="sh-selected-canvas" width="460" height="400" role="img" tabindex="0" aria-describedby="sh-orbit-help" aria-label="'+B('可旋转的三维球谐基；方向标记与数值见下方','Rotatable 3D SH basis; direction marker and values are described below')+'"></canvas><figcaption id="sh-selected-caption" data-i18n-dynamic></figcaption></figure><div class="sh-basis-explanation">'+H('01 · 一个方向图案，三个独立系数','01 · One directional pattern, three separate coefficients')+P('左图是选中的一个 Yₖ：橙色为正、蓝色为负，只用来标记数值的符号，与 RGB 通道无关。R、G、B 共用这个方向图案，但分别乘以自己的系数。','The left plot is one selected Yₖ: orange is positive and blue is negative. Those colors label the sign of a number, not RGB channels. R, G, and B share this directional pattern but multiply it by their own coefficients.')+
  '<div class="sh-selected-equation" id="sh-selected-equation">'+formulae.map((f,k)=>'<div data-formula="'+k+'"'+(k===6?'':' hidden')+'>'+formula('Y_{'+Math.floor(Math.sqrt(k))+','+(k-Math.floor(Math.sqrt(k))**2-Math.floor(Math.sqrt(k)))+'}(\\mathbf v)='+f)+'</div>').join('')+'</div>'+formula('\\Delta\\mathbf c_k(\\mathbf v)=Y_k(\\mathbf v)\\begin{bmatrix}a_{k,R}\\\\a_{k,G}\\\\a_{k,B}\\end{bmatrix}')+'<a class="sh-coefficient-jump" href="#sh-channel-coefficients">'+B('在通道球旁编辑这个基的 RGB 系数 ↓','Edit this basis\'s RGB coefficients beside the channel spheres ↓')+'</a></div></div>'+
  '<div class="sh-channel-section" id="sh-channels">'+H('02 · 三个通道分别求和，再组成 RGB','02 · Sum each channel separately, then combine RGB')+
  P('下面每颗球都累加当前最高阶以内的所有基函数。只改球下方的 R 系数：R 球和合成球会改变，G、B 球不变。选中一个基函数只是选择要编辑的系数，不会让其他项停止参与求和。','Each sphere below sums every basis function up to the selected degree. Change only the R coefficient beneath the spheres: the R sphere and the combined sphere change, while G and B stay fixed. Selecting a basis chooses which coefficients to edit; it does not remove other terms from the sum.')+
  formula('s_j(\\mathbf v)=\\sum_{k=0}^{(L+1)^2-1}a_{k,j}Y_k(\\mathbf v),\\qquad j\\in\\{R,G,B\\}')+
  formula('d_j(\\mathbf v)=\\operatorname{clip}_{[0,1]}\\!\\left(\\tfrac12+s_j(\\mathbf v)\\right),\\qquad \\mathbf c_{\\rm display}=(d_R,d_G,d_B)')+
  '<p id="sh-channel-count" class="sh-numeric" data-i18n-dynamic></p><div class="sh-controls sh-channel-display"><label for="sh-channel-mode">'+B('单通道的显示方式','Single-channel display')+'<select id="sh-channel-mode"><option value="tinted">'+B('通道本色：红 / 绿 / 蓝','Channel colors: red / green / blue')+'</option><option value="grayscale">'+B('统一灰度：比较通道数值','Shared grayscale: compare channel values')+'</option></select></label></div>'+
  '<p id="sh-channel-help" class="sh-small">'+B('通道本色模式只亮起对应的分量，例如 R 球显示 (dR,0,0)。灰度模式把同一个值复制到三个分量，例如 (dR,dR,dR)，便于比较。所有通道共用固定 0–1 范围，不单独归一化，也不附加光照；RGB 合成球始终显示完整颜色。','Channel-color mode lights only the corresponding component: the R sphere displays (dR,0,0). Grayscale copies that value into all three components, (dR,dR,dR), for comparison. All channels use the same fixed 0–1 range, with no per-channel normalization or added lighting; the RGB sphere always shows the full color.')+'</p>'+
  '<div class="sh-controls sh-angle-controls"><label for="sh-phi">'+B('方位角 φ：绕 z 轴','Azimuth φ: around the z axis')+'<output id="sh-phi-value">−45°</output><input id="sh-phi" type="range" min="-180" max="180" step="1" value="-45"></label><label for="sh-theta">'+B('极角 θ：从 +z 往下','Polar angle θ: down from +z')+'<output id="sh-theta-value">45°</output><input id="sh-theta" type="range" min="0" max="180" step="1" value="45"></label><button id="sh-reverse" type="button">'+B('方向取反 v → −v','Reverse direction v → −v')+'</button></div>'+
  '<p class="sh-numeric" id="sh-direction" data-i18n-dynamic></p>'+channelPlots+'<div id="sh-channel-coefficients">'+coefficientControls+'</div>'+
  '<p class="sh-small">'+B('球下方的读数对应同一个白色方向标记。SH 求和允许为负，加 0.5 是这里采用的 3DGS 约定；官方求值只截断负颜色，本页为屏幕显示再截断到 1。被截断后，系数继续变化也可能暂时看不出颜色变化。','Readouts below the spheres refer to the same white direction marker. The SH sum may be negative; +0.5 follows the 3DGS convention used here. The official evaluator clamps negative colors only; this page additionally clips at 1 for screen display. After clipping, further coefficient changes may temporarily produce no visible color change.')+'</p></div>'+
  '<p class="sh-small">'+B('这里旋转的是看图的视角：系数、输入方向 v 和颜色计算结果保持不变。正面、侧面、顶部表示图示相机位于 −Y、+X、+Z 轴；下方的 φ、θ 才会改变 SH 的求值方向。','These controls rotate only the plot camera: coefficients, input direction v, and evaluated color stay fixed. Front, side, and top place the plot camera on the −Y, +X, and +Z axes. The φ and θ controls below change the SH evaluation direction.')+'</p>'+
  '<p class="sh-small">'+B('白点代表当前输入方向；虚线圆代表它在背面。这里的坐标是“相机 → Gaussian”的单位向量，所以相机实际位于相反方向。图中的球与瓣都只是函数图，不是场景中的物体或 Gaussian 椭球。','The white marker is the current input direction; a dashed ring means it is on the back. Coordinates use the unit vector from camera to Gaussian, so the camera itself is in the opposite direction. These spheres and lobes are plots of functions, not scene objects or Gaussian ellipsoids.')+'</p>'+
  '<div class="sh-result"><i id="sh-swatch" aria-hidden="true"></i><div id="sh-result-text" data-i18n-dynamic></div></div>'+
  '<details class="sh-chapter" id="sh-contributions"><summary>'+B('逐项核对：基函数 × 系数 = RGB 贡献','Check every term: basis × coefficients = RGB contribution')+'</summary><div><div class="table-wrap"><table><thead><tr><th>k / (ℓ,m)</th><th>'+B('当前 Y 值','Current Y value')+'</th><th>'+B('RGB 系数 a','RGB coefficients a')+'</th><th>'+B('RGB 贡献 aY','RGB contribution aY')+'</th></tr></thead><tbody id="sh-contribution-body" data-i18n-dynamic></tbody></table></div>'+P('表格只累加最高阶以内的项。RGB 系数分别改变三个通道，基函数的方向图案对三个通道完全相同。','The table sums only terms up to the selected degree. RGB coefficients control the three channels separately; all three channels use the same directional basis pattern.')+'</div></details>'+
  '<aside class="note"><strong>'+B('照着做，立刻验证三个结论','Try these three quick checks')+'</strong><ol><li>'+B('载入“只有 DC”，拖动两个角度：颜色不变，因为常数不看方向。','Load DC only and move both angles: the color stays fixed because a constant ignores direction.')+'</li><li>'+B('把最高阶设为 1，选 k = 2，把 R 调到正数：+z 侧更红，−z 侧更少红。再让 R 变负，效果反过来。','Set the maximum degree to 1, select k = 2, and make R positive: the +z side gains red and the −z side loses red. A negative R reverses the effect.')+'</li><li>'+B('把最高阶设为 2，选 k = 6，点击“方向取反”：二阶 Y 值不变；改选 k = 2，同样操作，一阶 Y 值变号。','Set the maximum degree to 2, select k = 6, and reverse the direction: its degree-2 value is unchanged. Select k = 2 and repeat: its degree-1 value changes sign.')+'</li></ol></aside></section>'+

  '<section id="sh-derivation"><h3>'+B('从初中数学开始，推到能写进代码。','Start with school mathematics. Finish with code.')+'</h3>'+P('不需要先背积分和导数。下面先用长度、面积、对称性解释它们；每一步再给精确公式。积分符号可以先读作“把整颗球上所有小块的结果加起来”。','You do not need to memorize calculus first. We explain it through lengths, areas, and symmetry, then give the precise equations. Read an integral as “add the results from every small patch of the sphere.”')+
  chapter('sh-coordinates','01 · 方向：从一根箭头变成球上的一点','01 · Direction: an arrow becomes a point on a sphere',
    '<ol class="derivation-steps">'+
    S('先减位置，再把长度变成 1','Subtract positions, then make the length 1',P('设 Gaussian 中心是 μ，相机是 C。用中心减相机，得到箭头 d。用勾股定理算长度，再把三个分量都除以长度。距离变短了，指向不变。相机与中心重合时长度为零，代码必须处理这个特殊情况。','Let μ be the Gaussian center and C the camera. Subtract the camera position from the center to get d. Use Pythagoras to find its length, then divide every component by that length. This changes length, not direction. If the camera and center coincide, the length is zero and code must handle that case.')+formula('\\mathbf d=\\boldsymbol\\mu-\\mathbf C,\\quad r=\\sqrt{d_x^2+d_y^2+d_z^2},\\quad (x,y,z)=\\mathbf v=\\frac{\\mathbf d}{r},\\quad x^2+y^2+z^2=1')+formula('\\mathbf d=(2,-2,1)\\;\\Rightarrow\\;r=3\\;\\Rightarrow\\;\\mathbf v=\\left(\\frac23,-\\frac23,\\frac13\\right)'))+
    S('两个角度只是在描述同一个点','Two angles describe the same point',P('θ 是从北极 +z 往下量的角度。直角三角形给出高度 z = cosθ，水平圈半径是 sinθ。再在水平圆内用 φ 分出 x 和 y。θ 不是从赤道量的纬度；代码中的 sin、cos 使用弧度。','θ is measured down from the north pole, +z. A right triangle gives height z = cosθ and horizontal-circle radius sinθ. On that horizontal circle, φ splits the radius into x and y. θ is not latitude measured from the equator; code uses radians for sin and cos.')+formula('x=\\sin\\theta\\cos\\varphi,\\qquad y=\\sin\\theta\\sin\\varphi,\\qquad z=\\cos\\theta,\\qquad \\theta_{\\rm rad}=\\theta_{\\rm deg}\\frac{\\pi}{180}'))+'</ol>',true)+
  chapter('sh-inner-product','02 · “不重复的图案”：加权求和与正交','02 · Nonredundant patterns: weighted sums and orthogonality',
    '<ol class="derivation-steps">'+S('先从三格表格的点积说起','Start with the dot product of three entries',P('两张图案如果总是一起变亮，就有重复信息。把对应位置的值相乘再相加，可以测这种重合。比如 [1,1,1] 和 [−1,0,1] 的乘积和是 0：后者的正负抵消，不能冒充前者的整体亮度。把三格换成整个球面，就是函数的内积。','Patterns that always brighten together carry overlapping information. Multiply corresponding values and add them to measure that overlap. For [1,1,1] and [−1,0,1], the sum of products is zero: the second pattern cancels itself and cannot imitate uniform brightness. Replacing three entries with the whole sphere gives a function inner product.')+formula('[1,1,1]\\cdot[-1,0,1]=-1+0+1=0,\\qquad\\langle f,g\\rangle=\\int_{S^2}f(\\mathbf v)g(\\mathbf v)\\,d\\Omega'))+
    S('球面上的小格子，面积并不都一样','Small patches on a sphere do not all have the same area',P('经纬图中同样宽的一格，在北极附近会缩小。纬圈半径是 sinθ，所以球面小块面积约等于“横向 sinθΔφ × 纵向 Δθ”。把格子越分越细，就得到 sinθ dθ dφ。单位球总面积是 4π。正交归一的意思是：不同图案的乘积和为 0，同一图案的平方和为 1。','A fixed-width cell on a longitude–latitude map shrinks near a pole. The horizontal-circle radius is sinθ, so a patch has approximate area sinθΔφ × Δθ. Taking ever smaller cells gives sinθ dθ dφ. A unit sphere has total area 4π. Orthonormal means product-sum zero for different patterns and square-sum one for the same pattern.')+formula('d\\Omega=\\sin\\theta\\,d\\theta\\,d\\varphi,\\quad\\int_{S^2}1\\,d\\Omega=4\\pi,\\quad\\int_{S^2}Y_iY_j\\,d\\Omega=\\begin{cases}1&i=j\\\\0&i\\ne j\\end{cases}'))+'</ol>',true)+
  chapter('sh-low-degrees','03 · 零阶与一阶：为什么是 0.282 和 0.489？','03 · Degrees 0 and 1: why 0.282 and 0.489?',
    '<ol class="derivation-steps">'+S('零阶：所有方向都一样','Degree 0: the same in every direction',P('把基函数设成常数 k。整球的平方和就是“面积 × k²”。让它等于 1，取正根，便得到 DC 常数。它不是拍脑袋调出来的亮度。','Set the basis function to a constant k. Its square-sum over the sphere is area × k². Set that to one and take the positive root to get the DC constant. It is a normalization, not a hand-tuned brightness.')+formula('1=\\int_{S^2}k^2\\,d\\Omega=4\\pi k^2\\quad\\Rightarrow\\quad Y_{00}=k=\\frac1{\\sqrt{4\\pi}}\\approx0.28209479'))+
    S('一阶：先拿 x、y、z 当三张图案','Degree 1: use x, y, and z as three patterns',P('球的左右两半完全对称：x 的正负抵消，故它与常数正交；xy 也会在 x 取反时抵消，故 x 与 y 正交。三个方向地位相同，所以 x²、y²、z² 的球面积分相等。它们相加恒等于 1，因此每一个积分都是 4π/3。','The two halves of a sphere are symmetric: positive and negative x cancel, making x orthogonal to a constant. Likewise, xy cancels when x is reversed, making x orthogonal to y. The axes are equivalent, so the integrals of x², y², and z² are equal. Their sum is always one, so each integral is 4π/3.')+formula('\\int x^2d\\Omega=\\int y^2d\\Omega=\\int z^2d\\Omega,\\quad\\int(x^2+y^2+z^2)d\\Omega=4\\pi\\;\\Rightarrow\\;\\int z^2d\\Omega=\\frac{4\\pi}{3}')+formula('\\int(kz)^2d\\Omega=1\\;\\Rightarrow\\;k=\\sqrt{\\frac3{4\\pi}}\\approx0.48860251'))+
    S('正负号与排列：必须和模型文件一致','Signs and ordering must match the model file',P('正交性并不会规定哪个图案必须取负号。这里采用 Graphdeco 3DGS 的实球谐约定：一阶按 −y、z、−x 排列。若只看形状忽略这些负号，读入同一份系数就会得到错误颜色。方向从 μ−C 改成 C−μ，也会把奇数阶翻转。','Orthogonality does not force a particular sign for each pattern. We use Graphdeco 3DGS real SH: degree 1 is ordered −y, z, −x. Ignoring those signs changes the colors of an existing coefficient file. Replacing μ−C with C−μ also flips odd degrees.')+formula('(Y_{1,-1},Y_{1,0},Y_{1,1})=\\sqrt{\\frac3{4\\pi}}(-y,z,-x),\\qquad Y_{\\ell m}(-\\mathbf v)=(-1)^\\ell Y_{\\ell m}(\\mathbf v)'))+'</ol>')+
  chapter('sh-second-degree','04 · 二阶：从六个乘法式，得到五张新图案','04 · Degree 2: six products become five new patterns',
    '<ol class="derivation-steps">'+S('六个二次项里，有一个其实是旧图案','One of the six quadratic combinations repeats an old pattern',P('把 x、y、z 两两相乘，得到 x²、y²、z²、xy、yz、xz 六种。但 x²+y²+z²=1 已经是零阶常数。扣掉这个重复方向，剩下五种独立变化。注意“扣掉一个”是五维空间，不是随便删掉一个多项式。','Pairwise products of x, y, and z give six terms: x², y², z², xy, yz, xz. But x²+y²+z²=1 already belongs to degree 0. Removing this redundant direction leaves five independent variations. This means a five-dimensional space, not arbitrarily deleting any polynomial.')+formula('xy,\\quad yz,\\quad xz,\\quad x^2-y^2,\\quad 3z^2-1'))+
    S('为什么会出现 3z²−1？','Why does 3z²−1 appear?',P('z² 从不为负，会夹带一层“整体亮度”。上一节算过 z² 在球上的平均值是 1/3，所以先减掉 1/3，再乘 3 去分母。这样正负面积抵消，保证不再重复 DC。x²−y² 也因为对称性而平均为零。','Because z² is never negative, it contains uniform brightness. We found that its average over the sphere is 1/3. Subtract 1/3, then multiply by three to remove the fraction. Positive and negative contributions now cancel, so the pattern no longer duplicates DC. Symmetry also gives x²−y² zero mean.')+formula('z^2-\\frac13\\quad\\longrightarrow\\quad3z^2-1=2z^2-x^2-y^2,\\qquad\\int(3z^2-1)d\\Omega=0'))+
    S('先算两个面积和：z⁴ 与 x²y²','Compute two area sums: z⁴ and x²y²',P('把球切成薄薄的水平带。在单位球上，每条带的面积是 2π × 高度差 Δz；纬圈变短与斜坡变陡刚好抵消。因此 z⁴ 的球面积分变成 2π 乘上 −1 到 1 的 z⁴ 面积。幂函数的面积规则是：指数加一，再除以新的指数。再展开 (x²+y²+z²)²，利用三轴对称，就能求交叉项。','Cut the unit sphere into thin horizontal bands. Each has area 2π × height difference Δz: a shorter latitude circle and a steeper slope cancel exactly. The sphere integral of z⁴ becomes 2π times its area from −1 to 1. The power-area rule increases the exponent by one and divides by that new exponent. Expand (x²+y²+z²)² and use symmetry to find the cross terms.')+formula('\\int_{S^2}z^4d\\Omega=2\\pi\\int_{-1}^1z^4dz=2\\pi\\left[\\frac{z^5}{5}\\right]_{-1}^1=\\frac{4\\pi}{5}')+formula('4\\pi=\\int(x^2+y^2+z^2)^2d\\Omega=3\\cdot\\frac{4\\pi}{5}+6\\int x^2y^2d\\Omega\\;\\Rightarrow\\;\\int x^2y^2d\\Omega=\\frac{4\\pi}{15}'))+
    S('平方和变成 1，常数就自己出现了','Make the square-sums one and the constants follow',P('xy 的平方和已经有了。对 3z²−1 和 x²−y²，先展开平方，再代入刚才的面积和。每个图案乘上“平方和的倒数开根号”，就全部归一化。最后按约定给 yz、xz 加负号。','We already know the square-sum of xy. For 3z²−1 and x²−y², expand each square and substitute the area sums above. Multiply every pattern by the reciprocal square root of its square-sum to normalize it. Finally use the chosen negative signs for yz and xz.')+formula('\\int(3z^2-1)^2d\\Omega=9\\frac{4\\pi}{5}-6\\frac{4\\pi}{3}+4\\pi=\\frac{16\\pi}{5}')+formula('\\int(x^2-y^2)^2d\\Omega=2\\frac{4\\pi}{5}-2\\frac{4\\pi}{15}=\\frac{16\\pi}{15}')+formula('\\begin{aligned}Y_{2,-2}&=\\sqrt{\\frac{15}{4\\pi}}xy,&Y_{2,-1}&=-\\sqrt{\\frac{15}{4\\pi}}yz,\\\\Y_{2,0}&=\\sqrt{\\frac{5}{16\\pi}}(3z^2-1),&Y_{2,1}&=-\\sqrt{\\frac{15}{4\\pi}}xz,\\\\Y_{2,2}&=\\sqrt{\\frac{15}{16\\pi}}(x^2-y^2).&&\\end{aligned}'))+'</ol>')+
  chapter('sh-general','05 · 更高阶：Legendre 规则从哪里接上来？','05 · Higher degrees: how does the Legendre rule connect?',
    '<ol class="derivation-steps">'+S('“球谐”里的“谐”：一种特殊的多项式','The harmonic in spherical harmonics: a special polynomial',P('不是把任意多项式归一化就能叫标准球谐。三维齐次调和多项式限制在单位球上，才给出这一族图案。“齐次”指每项总次数相同；“调和”指三个二阶偏导数相加为零。二阶例子 2z²−x²−y² 的结果是 4−2−2=0。单位球上可把它写成 3z²−1，但检查调和性时应使用前面的三维多项式。','Normalizing an arbitrary polynomial does not make it a standard spherical harmonic. This family comes from homogeneous harmonic polynomials in 3D restricted to the unit sphere. Homogeneous means all terms have the same total degree. Harmonic means the three second partial derivatives sum to zero. For 2z²−x²−y², that sum is 4−2−2=0. On the sphere it equals 3z²−1; test harmonicity using the original 3D polynomial.')+formula('\\nabla^2H=\\frac{\\partial^2H}{\\partial x^2}+\\frac{\\partial^2H}{\\partial y^2}+\\frac{\\partial^2H}{\\partial z^2}=0,\\qquad H(\\lambda x,\\lambda y,\\lambda z)=\\lambda^\\ell H(x,y,z)'))+
    S('先只沿南北变化：逐项算出 P₂ 与 P₃','Start with north–south variation: calculate P₂ and P₃',P('Legendre 多项式提供不依赖方位角的那一个图案。下面是生成它的 Rodrigues 规则。d/dz 表示“求斜率”：zⁿ 的斜率是 nzⁿ⁻¹；连续做两次就是二阶导。按规则先展开、再逐项求导，不需要记住答案。','Legendre polynomials provide the pattern with no azimuth dependence. The Rodrigues rule generates them. Here d/dz means “take the slope”: the slope of zⁿ is nzⁿ⁻¹. Doing this twice gives a second derivative. Expand first and differentiate term by term; there is no need to memorize the result.')+formula('P_\\ell(z)=\\frac{1}{2^\\ell\\ell!}\\frac{d^\\ell}{dz^\\ell}(z^2-1)^\\ell')+formula('P_2(z)=\\frac18\\frac{d^2}{dz^2}(z^4-2z^2+1)=\\frac18\\frac{d}{dz}(4z^3-4z)=\\frac{12z^2-4}{8}=\\frac{3z^2-1}{2}')+formula('P_3(z)=\\frac1{48}\\frac{d^3}{dz^3}(z^6-3z^4+3z^2-1)=\\frac{120z^3-72z}{48}=\\frac{5z^3-3z}{2}'))+
    S('再加入绕圈变化：sin 与 cos 两个搭档','Add variation around the sphere: sine and cosine pairs',P('对每个正整数 m，有一张 cos(mφ) 图和一张 sin(mφ) 图。m=0 只需一张，因为 sin0=0。关联 Legendre 函数把南北方向的形状补齐。这里的 (−1)ᵐ 是 Condon–Shortley 相位，必须和前面的一阶符号一致。阶乘 ! 就是从该整数一路乘到 1，0!=1。','Each positive integer m gives a cos(mφ) pattern and a sin(mφ) pattern. For m=0, only one is needed because sin0=0. Associated Legendre functions supply the north–south shape. The factor (−1)ᵐ is the Condon–Shortley phase, consistent with our degree-1 signs. A factorial, !, multiplies integers down to one; 0!=1.')+formula('P_\\ell^m(z)=(-1)^m(1-z^2)^{m/2}\\frac{d^mP_\\ell(z)}{dz^m},\\qquad N_{\\ell m}=\\sqrt{\\frac{2\\ell+1}{4\\pi}\\frac{(\\ell-m)!}{(\\ell+m)!}}')+formula('\\begin{aligned}Y_{\\ell,0}&=N_{\\ell0}P_\\ell(z),&&\\\\Y_{\\ell,m}&=\\sqrt2N_{\\ell m}P_\\ell^m(z)\\cos(m\\varphi)&& (m>0),\\\\Y_{\\ell,-m}&=\\sqrt2N_{\\ell m}P_\\ell^m(z)\\sin(m\\varphi)&& (m>0).\\end{aligned}'))+
    S('把通用规则亲手化成代码中的 xy','Turn the general rule into the xy in code',P('以 ℓ=2、m=2 为例：P₂ 求两次导得到 3，所以 P₂²=3(1−z²)。再用 sin2φ=2sinφcosφ，以及 x=sinθcosφ、y=sinθsinφ，根号和三角函数会合并成 xy。代码使用这些化简后的多项式，所以渲染时不必再求阶乘、积分或三角函数。','For ℓ=2 and m=2, differentiating P₂ twice gives 3, so P₂²=3(1−z²). Use sin2φ=2sinφcosφ with x=sinθcosφ and y=sinθsinφ. The factors collapse to xy. Rendering uses these simplified polynomials; it does not need factorials, integrals, or trigonometric functions for SH evaluation.')+formula('\\begin{aligned}Y_{2,-2}&=\\sqrt2\\sqrt{\\frac5{4\\pi}\\frac{0!}{4!}}\\,3(1-z^2)\\sin(2\\varphi)\\\\&=6\\sqrt{\\frac5{48\\pi}}(1-z^2)\\sin\\varphi\\cos\\varphi=\\sqrt{\\frac{15}{4\\pi}}xy.\\end{aligned}'))+
    S('为何每阶 2ℓ+1 个，L=3 总共 16 个？','Why 2ℓ+1 per degree and 16 through L=3?',P('m=0 给一张，m=1 到 ℓ 各给 sin、cos 两张，所以是 1+2ℓ。从零阶加到 L 阶，是连续奇数相加；正好拼成边长 L+1 的正方形。每个图案有三个颜色系数，所以 L=3 是 16 个 RGB 向量、48 个标量。','There is one pattern at m=0 and a sine/cosine pair for each m from 1 to ℓ, giving 1+2ℓ. Summing degrees 0 through L adds consecutive odd numbers, which build a square of side L+1. Each pattern has three color coefficients, so L=3 uses 16 RGB vectors, or 48 scalars.')+formula('1+3+5+\\cdots+(2L+1)=(L+1)^2,\\qquad k=\\ell^2+\\ell+m'))+'</ol>')+
  chapter('sh-projection','06 · 从颜色求系数，再把系数还原成颜色','06 · Find coefficients from colors, then reconstruct the colors',
    '<ol class="derivation-steps">'+S('正交像一把筛子：只留下想要的那项','Orthogonality acts as a sieve for one coefficient',P('先看单个颜色通道 f。假设它能由这些基函数的和表达，等式两边都乘 Yⱼ，再对球面求和。因为不同图案乘积的积分全是 0，只有第 j 项留下，而且它的平方积分是 1。于是得到求系数的公式。若只保留有限阶，得到的是在整个球面上的最小平方误差近似。','Consider one color channel f. If it can be expanded in the basis, multiply both sides by Yⱼ and integrate over the sphere. Every other pattern has zero product integral; only term j remains, with square integral one. This gives the coefficient formula. Keeping finitely many degrees gives a least-squares approximation over the whole sphere.')+formula('f(\\mathbf v)=\\sum_k a_kY_k(\\mathbf v)\\quad\\Rightarrow\\quad\\int fY_jd\\Omega=\\sum_k a_k\\int Y_kY_jd\\Omega=a_j'))+
    S('计算机怎样“把所有方向加起来”？','How does a computer add up all directions?',P('用 N 个近似等面积分布的方向，每个代表球面面积 4π/N，就把积分变成普通循环。如果用等间隔的经纬网格，各点代表的面积不同，需要 sinθ 权重。下面的重建实验采用等面积高度带和黄金角方向，共 4096 个样本；它是数值积分近似，不是精确符号积分。','Use N approximately equal-area directions, each representing area 4π/N, to turn the integral into an ordinary loop. A regularly spaced longitude–latitude grid needs sinθ weights because its cells have different areas. The reconstruction experiment below uses 4096 samples on equal-area height bands with golden-angle azimuths. This is numerical quadrature, not exact symbolic integration.')+formula('a_k\\approx\\frac{4\\pi}{N}\\sum_{n=1}^N f(\\mathbf v_n)Y_k(\\mathbf v_n),\\qquad f(\\mathbf v)=c_{\\rm target}(\\mathbf v)-0.5'))+
    S('算一个真实颜色：把四项全部代进去','Calculate a color by substituting all four terms',P('取方向 v=(0,0,1)，使用一阶，红通道系数为 [0.4,0,0.6,0]。只有 DC 和 z 那项不为零。把它们乘系数、相加，再按 Graphdeco 的约定加 0.5。这说明系数既不是最终颜色，也不需要限制在 0 到 1。','Take v=(0,0,1), degree 1, and red coefficients [0.4,0,0.6,0]. Only DC and the z term are nonzero. Multiply by coefficients, add, then apply Graphdeco\'s +0.5 convention. The coefficients are not final colors and need not lie between zero and one.')+formula('c_R^{\\rm raw}=0.4(0.28209479)+0.6(0.48860251)=0.40599942,\\qquad c_R=\\max(0,c_R^{\\rm raw}+0.5)=0.90599942')+P('官方 CUDA 的这一阶段只截掉负值；高于 1 的值仍可能保留。实验的普通屏幕色块另外截到 0–1，属于显示步骤，不能和前面的 SH 求值混为一谈。','At this stage the official CUDA implementation clamps only negative values; values above one may remain. The demo clips its screen swatches to 0–1 in a separate display step. That is distinct from evaluating SH.'))+'</ol>')+'</section>'+

  '<section id="sh-reconstruction"><h3>'+B('实验二 · 同一束“小亮斑”，低阶 SH 能记住多少？','Experiment 2 · How much of a small bright spot can low-degree SH retain?')+'</h3>'+
  P('左边是人为定义的方向颜色函数，不是测量材质。右边用相同的投影系数逐级增加阶数。零阶只能记住平均色；一阶出现宽渐变；二、三阶逐渐聚拢。尖锐亮斑仍会被抹宽，附近还可能出现过冲和振铃。','The left plot is a synthetic directional color function, not a measured material. The others use the same projected coefficients with increasing degree. Degree 0 stores only the mean; degree 1 gives a broad gradient; degrees 2 and 3 concentrate it. Sharp spots remain blurred and may produce overshoot or ringing nearby.')+
  formula('\\mathbf b=\\frac{(1,-1,1)}{\\sqrt3},\\quad h(\\mathbf v)=e^{(\\mathbf v\\cdot\\mathbf b-1)/0.14},\\quad\\mathbf c_{\\rm target}=(0.12,0.16,0.24)+(0.84,0.65,0.28)h')+
  viewControls('sh-fit')+'<p id="sh-fit-orbit-help" class="sh-orbit-help">'+B('拖动任意一个球，五张图会同步旋转，便于从同一角度比较。只改变观察视角，拟合系数与整个球面上的 RMSE 不变。也支持方向键、+/− 和 Home。','Drag any sphere to rotate all five together and compare them from the same angle. Only the viewing angle changes; fitted coefficients and full-sphere RMSE stay fixed. Arrow keys, +/−, and Home also work.')+'</p>'+
  '<div class="sh-reconstruction-grid">'+[-1,0,1,2,3].map(l=>'<figure><canvas id="sh-reconstruction-'+(l<0?'target':l)+'" width="260" height="228" role="img" tabindex="0" aria-describedby="sh-fit-orbit-help" aria-label="'+B(l<0?'原始方向颜色亮斑':'最高阶 '+l+' 的颜色重建',l<0?'Original directional color spot':'Color reconstruction through degree '+l)+'"></canvas><figcaption>'+(l<0?B('目标颜色','Target color'):'L = '+l+' · '+(l+1)**2+' RGB')+'</figcaption><small id="sh-error-'+l+'"></small></figure>').join('')+'</div>'+
  P('RMSE 使用另外 2048 个方向，比较“加 0.5 后、截断前”的重建 RGB 与目标 RGB。它不是图像 PSNR，也不是训练结果。彩色图只负责展示，显示截断会隐藏负值与过冲。低阶 SH 适合平滑方向变化，不能保证逼真地表示镜面尖峰；增加阶数也不会自动获得可重光照的材质。','RMSE uses 2048 separate directions and compares reconstructed RGB after +0.5 but before clipping with target RGB. It is not image PSNR or a training result. Display clipping can hide negative values and overshoot. Low-degree SH suits smooth directional variation; it cannot reliably represent sharp specular peaks. Increasing the degree does not create a relightable material.')+'</section>'+

  '<section id="sh-code"><h3>'+B('最后一公里 · 公式怎样走到 GS 训练和 wgpu？','The final connection · From equations to GS training and wgpu')+'</h3>'+
  '<ol class="sh-pipeline"><li>μ(t), C → v</li><li>v → Y₀…Y₁₅</li><li>Σ aₖYₖ + 0.5 → RGB</li><li>projection → α</li><li>Σ Tᵢαᵢ RGBᵢ → pixel</li></ol>'+
  P('通常先为每个 Gaussian、每个相机求一次视角颜色，再让所有被它覆盖的像素使用同一个 RGB。像素之间变化的是高斯核权重与合成顺序，不必在每个 fragment 里重复算 16 项 SH。对动态场景，用当前时刻 μ(t) 算方向；即使系数没变，运动也可能改变观察方向与颜色。','Typically, compute one view-dependent color per Gaussian per camera, then reuse that RGB for all pixels covered by the splat. Gaussian weights and compositing vary by pixel; there is no need to reevaluate 16 SH terms per fragment. For a dynamic scene, use μ(t) for the current time. Motion can change the viewing direction and color even when coefficients stay fixed.')+
  '<div class="code-bridge">'+H('可以直接检查的运行代码','Runnable code you can inspect')+P('本页实验直接调用 shBasis、sampleSH 与 projectColor。源码页按本次构建生成，可以从符号一路跟到每个中间量。sampleSH 保留了 raw、shifted、shaderColor、display 四层结果，便于定位“为什么颜色不一样”。','This experiment directly calls shBasis, sampleSH, and projectColor. The source snapshot is generated with this build, so you can follow each symbol into the intermediate values. sampleSH keeps raw, shifted, shaderColor, and display separately to help diagnose color mismatches.')+'<a class="source-location" href="/math/code/public-math-sh.mjs.html">public/math/sh.mjs ↗</a><pre tabindex="0"><code>'+esc('const direction = mean.map((v, i) => v - camera[i]);\nconst { basis, contributions, raw, shaderColor } =\n  sampleSH(coefficients, direction, 3);\n// For each pixel: RGB += transmittance * alpha * shaderColor;')+'</code></pre></div>'+
  chapter('sh-gradient','训练：怎么知道该拧哪一个系数？','Training: how do we know which coefficient to turn?',
    P('先固定一个方向，只动一个红通道系数 a。颜色对它是一条直线，斜率就是该方向的 Y 值。如果 Y=0，该方向对这个系数没有直接颜色梯度；要从其他方向获得信息。下面用半平方误差，让斜率可以直接看清。','Fix the direction and change one red coefficient a. Color is a straight-line function of a, with slope equal to the basis value Y at that direction. If Y=0, this view supplies no direct color gradient for that coefficient; other directions are needed. A half-squared error makes the slope easy to see.')+
    formula('c_R^{\\rm raw}=\\sum_k a_{kR}Y_k,\\quad\\frac{\\partial c_R^{\\rm raw}}{\\partial a_{kR}}=Y_k,\\quad E=\\frac12(c_R-c_R^*)^2,\\quad\\frac{\\partial E}{\\partial a_{kR}}=(c_R-c_R^*)Y_k')+
    P('例如 Y=0.4886，预测红色 0.7，目标 0.8，梯度为 −0.04886。学习率 0.1 时，a 要增加 0.004886，颜色约增加 0.002387。预测向目标靠近，说明正负号合理。这是单通道、单方向、未触发 clamp 的局部例子。','For Y=0.4886, predicted red 0.7, and target 0.8, the gradient is −0.04886. With learning rate 0.1, a increases by 0.004886 and color increases by about 0.002387. Moving toward the target checks the sign. This local example uses one channel and one direction with no active clamp.')+
    formula('a^{\\rm new}=a-\\eta\\frac{\\partial E}{\\partial a},\\qquad\\Delta c_R=Y\\Delta a=0.4886\\cdot0.004886\\approx0.002387')+
    P('真正的 GS 训练从渲染像素的损失反传，链条还要乘本层合成权重 Tᵢαᵢ，再把所有像素、相机的贡献加起来。下式假设只改 SH 系数、alpha 和顺序固定且颜色没有被下界截断。若 shifted 小于 0，官方 clamp 分支的颜色梯度为 0；恰好等于 0 的导数按实现约定。','Real GS training backpropagates image loss, multiplying by this splat\'s compositing weight Tᵢαᵢ and summing over pixels and cameras. The expression below holds for SH coefficient changes with alpha and order fixed and the color unclamped. If shifted is below zero, the official clamp branch has zero color gradient; the derivative exactly at zero follows the implementation convention.')+
    formula('\\frac{\\partial\\mathcal L}{\\partial a_{ikR}}=\\sum_{\\text{views},\\mathbf p}\\frac{\\partial\\mathcal L}{\\partial C_R(\\mathbf p)}\\,T_i(\\mathbf p)\\alpha_i(\\mathbf p)\\,Y_k(\\mathbf v_i)')+
    P('球面积分的投影只是本页的教学拟合方法。真实 GS 通常通过图像损失联合优化位置、尺度、不透明度和 SH 系数，训练视角也不一定均匀覆盖球面。因此不能把本页的积分循环当成完整 GS 训练器。','Sphere projection is the educational fitting method used here. Actual GS typically optimizes positions, scales, opacities, and SH coefficients jointly through image loss, and training views may not cover the sphere uniformly. The integral loop here is not a complete GS trainer.'))+
  chapter('sh-wgpu','存储与接口：Rust / WGSL 接入时核对什么？','Storage and interfaces: what to verify in Rust / WGSL',
    P('L=3 的 16 个 RGB 系数在紧密排列的 float32 文件中占 16×3×4=192 字节。但 WGSL 的 array<vec3<f32>,16> 元素步长是 16 字节，占 256 字节。最容易核对的上传格式是 16 个 vec4，每个 w 填 0，Rust 对应 [[f32;4];16]。这是系数块，不含位置和其他参数；混合结构仍要单独核对每个字段的 offset。','Sixteen RGB coefficients at L=3 occupy 16×3×4=192 bytes in a tightly packed float32 file. A WGSL array<vec3<f32>,16> has a 16-byte stride and occupies 256 bytes. A straightforward upload layout uses 16 vec4 values with w=0, corresponding to [[f32;4];16] in Rust. That is only the coefficient block; mixed structs still require checking every field offset.')+
    '<pre class="sh-code-block" tabindex="0"><code>'+esc('// Rust: upload layout for the coefficient block\n#[repr(C)]\nstruct ShBlock { coefficients: [[f32; 4]; 16] }\n\n// WGSL: sketch of the accumulation, once basis[] is computed\n// coeff: array<vec4<f32>, 16>; basis: array<f32, 16>;\nvar rgb = vec3<f32>(0.5);\nfor (var k = 0u; k < count; k += 1u) {\n    rgb += coeff[k].xyz * basis[k];\n}\nrgb = max(rgb, vec3<f32>(0.0));')+'</code></pre>'+
    P('还要核对：阶数是否表示“最高阶”还是“阶数数量”、RGB 通道排列、DC 与其余项的文件布局、基函数符号、方向朝向、是否已经加过 0.5、颜色空间与曝光。上面是接口示意，不是已经接入本项目的 SH shader。','Also verify whether the degree field means maximum degree or number of degrees, RGB channel ordering, the file layout of DC and remaining terms, basis signs, direction orientation, whether +0.5 has already been applied, color space, and exposure. The snippet illustrates the interface; it is not an SH shader already integrated into this project.')+
    '<aside class="note"><strong>'+B('当前 STG-Lite 的关键差别','The key difference in the current STG-Lite renderer')+'</strong>'+P('本项目当前 f_dc_0..2 是直接 RGB，shader 再 clamp 到 0–1。它不是 Graphdeco 的 SH DC，不能直接套 RGB2SH 或加 0.5。未来接 SH 要扩展文件解码、GPU buffer 和着色器，并保留现有 RGB 路径的格式区分。SH 也不是所有 4DGS 方法都使用的外观模型；特征解码器是另一条路线。','This project currently treats f_dc_0..2 as direct RGB, then clamps to 0–1 in the shader. Those values are not Graphdeco SH DC: do not apply RGB2SH or add 0.5 blindly. Integrating SH would require file decoding, GPU buffers, and shader changes, while retaining an explicit distinction from the existing RGB format. SH is not the appearance model of every 4DGS method; feature decoders are another approach.')+'<a class="source-location" href="/math/code/src-splat.wgsl.html">src/splat.wgsl ↗</a></aside>')+
  chapter('sh-reference','查表：零阶到三阶的完整 16 项','Reference: all 16 terms through degree 3',
    P('以下均假设 x²+y²+z²=1，使用本页和 Graphdeco 相同的实球谐符号与索引。三阶公式里的 5z²−1 可以用 4z²−x²−y² 替换，5z²−3 可以用 2z²−3x²−3y² 替换；单位球上完全相等。','All expressions assume x²+y²+z²=1 and use the real-SH signs and indices shared by this page and Graphdeco. At degree 3, 5z²−1 equals 4z²−x²−y², and 5z²−3 equals 2z²−3x²−3y² on the unit sphere.')+'<div class="table-wrap"><table><thead><tr><th>k</th><th>(ℓ,m)</th><th>Yℓm(x,y,z)</th></tr></thead><tbody>'+rows+'</tbody></table></div>')+
  '<details class="checkpoint"><summary>'+B('面试自测：一句话解释 SH 在 GS 里做什么？','Interview check: what does SH do in GS, in one sentence?')+'</summary>'+P('对每个 Gaussian，SH 用一组固定的球面方向基和学习到的 RGB 系数表示随视角变化的颜色；渲染时将相机到中心的方向归一化，求基函数值并加权求和，再进入投影与 alpha 合成。它不直接改变 Gaussian 的位置或协方差，也不等价于可重光照的 BRDF。','For each Gaussian, SH represents view-dependent color with fixed directional basis functions and learned RGB coefficients; rendering normalizes the camera-to-center direction, evaluates the basis, and sums weighted values before projection and alpha compositing. It does not directly change the Gaussian\'s position or covariance, and it is not a relightable BRDF.')+'</details>'+
  '<div class="sh-sources"><span>'+B('推导与实现的一手依据','Primary references for the derivation and implementation')+'</span><a href="https://dlmf.nist.gov/14.30" target="_blank" rel="noreferrer">NIST · Spherical harmonics ↗</a><a href="https://dlmf.nist.gov/14.7" target="_blank" rel="noreferrer">NIST · Legendre / Rodrigues ↗</a><a href="https://github.com/graphdeco-inria/gaussian-splatting/blob/main/utils/sh_utils.py" target="_blank" rel="noreferrer">Graphdeco · SH conventions ↗</a><a href="https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/cuda_rasterizer/forward.cu" target="_blank" rel="noreferrer">Graphdeco · CUDA forward ↗</a><a href="https://www.w3.org/TR/WGSL/#alignment-and-size" target="_blank" rel="noreferrer">W3C · WGSL alignment ↗</a></div></section></div>';

// Dynamic messages used by sh-ui.mjs. Keep placeholders identical in both editions.
[
  ['球谐图案与颜色', 'SH patterns and colors'],
  ['图示视角：方位 {yaw}° · 仰角 {pitch}° · 缩放 {zoom}×', 'Plot camera: azimuth {yaw}° · elevation {pitch}° · zoom {zoom}×'],
  ['选中 k = {k} · ℓ = {l}, m = {m} · Y(v) = {value}', 'Selected k = {k} · ℓ = {l}, m = {m} · Y(v) = {value}'],
  ['编辑 k = {k} 的三个系数', 'Edit the three coefficients of k = {k}'],
  ['该项高于当前最高阶，保留系数但暂不参与颜色求和。', 'This term is above the maximum degree. Its coefficients are retained but do not contribute to the color.'],
  ['该项正在参与求和。试着只改变一个通道，再观察贡献表。', 'This term is active. Try changing only one channel, then inspect the contribution table.'],
  ['单位方向 v = {direction}；长度 = {length}', 'Unit direction v = {direction}; length = {length}'],
  ['L = {degree}：{count} 个共享基函数 × 3 个通道 = {total} 个独立系数。', 'L = {degree}: {count} shared basis functions × 3 channels = {total} separate coefficients.'],
  ['SH 求和 {raw}；加 0.5 → {shifted}；显示 → {display}', 'SH sum {raw}; +0.5 → {shifted}; display → {display}'],
  ['纯 SH 求和', 'Raw SH sum'], ['加 0.5 后', 'After +0.5'], ['仅下界 clamp', 'Lower clamp only'], ['屏幕显示 0–1', 'Screen display 0–1'],
].forEach(([zh,en]) => { shTranslations[zh]=en; });
