import { formula } from './lesson-format.mjs';
import { esc } from './notation.mjs';
export const trainingTranslations={};
const B=(zh,en)=>{trainingTranslations[zh]=en;return esc(zh);};
const stages=[
  ['读取训练样本','Read the training batch','目标是固定的三帧合成图，时间分别为 0.25、0.5、0.75。每帧取 12×10 个像素，三帧一起组成这次更新的 batch。迭代次数增加不会改变目标图。','The targets are three fixed synthetic frames at times 0.25, 0.5, and 0.75. Each contributes a 12×10 pixel crop. All three frames form the batch for this update; targets stay fixed across iterations.', 'N=3\\times12\\times10=360,\\qquad (t_n,\\mathbf p_n,\\mathbf y_n)_{n=1}^{N}','training-data'],
  ['把参数变成当前时刻的 Gaussian','Evaluate the Gaussian at each time','同一套参数生成三个时刻的形状。μ₀x 是基准位置，m₁x 是水平方向的一阶运动系数；β 经 sigmoid 变成基础不透明度。本实验只学习这三个参数，其他字段和 Gaussian B 固定。','One parameter set generates all three times. μ₀x is the base position, m₁x is its linear horizontal motion, and sigmoid turns β into base opacity. Only these three parameters of A are learned; all other fields and Gaussian B stay fixed.', '\\Delta t=t-\\tau,\\quad\\boldsymbol\\mu(t)=\\boldsymbol\\mu_0+\\mathbf m_1\\Delta t+\\mathbf m_2\\Delta t^2+\\mathbf m_3\\Delta t^3,\\quad o=\\sigma(\\beta)','trace-decode'],
  ['投影到屏幕','Project onto the screen','位置经相机变换得到屏幕中心；协方差经 Jacobian 变成屏幕椭圆。中间图现在只画椭圆轮廓。这里的相机固定，学习者改变的是 Gaussian 参数。','The camera maps the center to screen coordinates; the Jacobian maps covariance to a screen ellipse. The middle image now shows ellipse outlines. The camera is fixed: training changes Gaussian parameters.', '\\mathbf u=\\pi(\\boldsymbol\\mu(t)),\\qquad C=J\\Sigma J^T+0.3I','trace-project'],
  ['覆盖、排序、合成像素','Cover, sort, and composite pixels','先算原始 alpha，再设 0.99 上限；quad 外或 alpha 小于 1/255 的贡献归零。按近到远累积颜色，每层乘以前面剩余的透射率，最后加背景。预测图由当前参数真正计算出来。','Compute raw alpha and cap it at 0.99; outside the quad or below 1/255, its contribution is zero. Accumulate front to back, weighting each layer by remaining transmittance, then add background. The prediction is actually rendered from current parameters.', '\\widetilde\\alpha_i=o_iw_i(t)e^{-\\frac12\\mathbf d_i^TC_i^{-1}\\mathbf d_i},\\quad T_i=\\prod_{j<i}(1-\\alpha_j),\\quad\\widehat{\\mathbf y}=\\sum_iT_i\\alpha_i\\mathbf c_i+T_{\\rm bg}\\mathbf c_{\\rm bg}','trace-forward'],
  ['计算误差','Measure the error','逐像素、逐 RGB 通道比较预测和目标，再对全部 360 个像素取平均。右图亮的地方误差较大。点击任一图可以追踪一个像素，但不会改变训练 batch。','Compare prediction with target in each RGB channel and average over all 360 pixels. Brighter regions on the right have larger errors. Click any image to inspect a pixel; the training batch stays unchanged.', '\\mathcal L=\\frac1{3N}\\sum_{n=1}^{N}\\sum_{j\\in\\{R,G,B\\}}(\\widehat y_{n,j}-y_{n,j})^2','trace-loss'],
  ['反向传播并累积梯度','Backpropagate and accumulate gradients','从误差倒着走：RGB → alpha → 位置或不透明度。位置还会通过投影 Jacobian 影响椭圆，因此需要两条路径。运动系数的梯度再乘 Δt；将所有像素、三个时间的贡献平均，得到下表的 batch 梯度。','Follow the error backward: RGB → alpha → position or opacity. Position also changes the ellipse through the projection Jacobian, so both paths matter. The motion gradient includes Δt. Average contributions from every pixel and all three times to obtain the batch gradients below.', '\\frac{\\partial\\mathcal L_n}{\\partial\\theta}=\\frac{\\partial\\mathcal L_n}{\\partial\\alpha_A}\\frac{\\partial\\alpha_A}{\\partial\\theta},\\quad\\frac{\\partial\\mathcal L_n}{\\partial m_{1x}}=\\Delta t\\frac{\\partial\\mathcal L_n}{\\partial\\mu_{0x}}','trace-gradient'],
  ['准备一次 SGD 更新','Prepare one SGD update','此刻梯度已经算完，参数还没有修改。三个参数使用同一份旧参数求得的梯度，同时执行 θ−ηg。学习率越大，移动越远，但不保证损失下降。','Gradients are ready, but parameters have not changed yet. All three updates use gradients from the same old parameter set and apply θ−ηg simultaneously. A larger learning rate moves farther and does not guarantee a lower loss.', '\\theta_j^{\\rm next}=\\theta_j-\\eta g_j,\\qquad g_j=\\frac1N\\sum_n\\frac{\\partial\\mathcal L_n}{\\partial\\theta_j}','training-step'],
  ['应用更新，再渲染核对','Apply the update and render again','参数在进入这一步时只更新一次。重新渲染同一批三帧，比较前后损失，向曲线追加一个实测点。上一小步会撤销这次更新，便于核对；下一轮重新计算梯度，不会复用旧梯度。','Entering this step applies the update exactly once. Render the same three frames again, compare losses, and append one measured point to the curve. Going back undoes this update for inspection; the next iteration recomputes gradients.', '\\mathcal L_{\\rm before}=\\mathcal L(\\theta),\\qquad\\mathcal L_{\\rm after}=\\mathcal L(\\theta-\\eta g)','training-step'],
];

export function buildTrainingContent(excerpts) {
  return '<section class="training-lab" id="training-lab" aria-labelledby="training-lab-title"><p class="eyebrow">WATCH A TRAINING ITERATION</p><h3 id="training-lab-title">'+B('把训练慢放：从三帧图像到一次参数更新','Training in slow motion: three frames, one parameter update')+'</h3><p class="training-intro">'+B('这是在浏览器里实际运行的双精度 CPU 教学训练器：2 颗 STG-Lite Gaussian、3 个时间、1 台相机。目标图固定，只优化 A 的位置 μ₀x、运动 m₁x 和不透明度 β；没有密度控制或完整场景重建。','This is a real double-precision CPU teaching trainer in your browser: 2 STG-Lite Gaussians, 3 times, 1 camera. Targets are fixed. Only A’s position μ₀x, motion m₁x, and opacity β are optimized; it does not perform density control or full-scene reconstruction.')+'</p>'+
  '<div class="training-toolbar"><button id="train-prev" type="button">'+B('← 上一小步','← Previous stage')+'</button><button id="train-next" type="button" class="training-primary" data-i18n-dynamic></button><button id="train-play" type="button" data-i18n-dynamic></button><button id="train-fast" type="button">'+B('训练 50 轮','Train 50 iterations')+'</button><button id="train-reset" type="button">'+B('重置训练','Reset training')+'</button><label for="train-rate">'+B('学习率 η','Learning rate η')+'<select id="train-rate"><option value="1">1</option><option value="5" selected>5</option><option value="10">10</option><option value="50">50</option></select></label><button id="train-focus" type="button" aria-pressed="false" data-i18n-dynamic></button></div><p id="train-status" class="training-status" role="status" aria-live="polite" data-i18n-dynamic></p>'+
  '<ol class="training-stages">'+stages.map((s,i)=>'<li><span data-stage-chip="'+i+'">'+B((i+1)+'. '+s[0],(i+1)+'. '+s[1])+'</span></li>').join('')+'</ol>'+
  '<div class="training-workspace"><div class="training-lesson">'+stages.map((s,i)=>{
    const ref=excerpts[s[5]];
    return '<article data-training-stage="'+i+'"'+(i?' hidden':'')+'><h4>'+B(s[0],s[1])+'</h4><p>'+B(s[2],s[3])+'</p>'+formula(s[4])+'<details class="training-code"><summary>'+B('这一步的实际 JavaScript 源码','Actual JavaScript for this stage')+'</summary><a href="'+ref.href+'" target="_blank" rel="noreferrer">'+esc(ref.path)+' · L'+ref.first+'–'+ref.last+' ↗</a><pre tabindex="0"><code>'+esc(ref.text)+'</code></pre></details></article>';
  }).join('')+'</div>'+
  '<div class="training-visuals"><div class="training-view-controls"><label for="train-frame">'+B('查看哪一帧（全部三帧都参与训练）','Inspect a frame (all three are trained)')+'<select id="train-frame"><option value="0">t = 0.25</option><option value="1" selected>t = 0.50</option><option value="2">t = 0.75</option></select></label><label for="train-pixel">'+B('追踪像素 0–119','Inspect pixel 0–119')+'<input id="train-pixel" type="number" min="0" max="119" step="1" value="66"></label><p>'+B('场景时间 t 选择画面；训练轮数记录参数更新了几次。','Scene time t selects a frame; the iteration count tracks parameter updates.')+'</p></div>'+
  '<div class="training-images">'+[['target','固定目标','Fixed target'],['prediction','当前预测','Current prediction'],['error','逐像素误差','Per-pixel error']].map(([id,zh,en])=>'<figure><figcaption>'+B(zh,en)+'</figcaption><div class="training-image-wrap"><canvas id="train-'+id+'" width="360" height="300" role="img" aria-label="'+B(zh+'，点击选择像素',en+'; click to select a pixel')+'"></canvas>'+(id==='target'?'':'<span id="train-'+id+'-note" class="training-image-note" data-i18n-dynamic></span>')+'</div></figure>').join('')+'</div><p class="training-small">'+B('三图共享白色像素标记。误差图显示每像素 RGB 均方根误差，固定 0–0.25 映射为暗到亮，超过 0.25 饱和；下方数值始终是未缩放的 MSE。','All images share the white pixel marker. Error brightness maps per-pixel RGB RMSE from 0 to 0.25, saturating above 0.25. Numeric MSE values below remain unscaled.')+'</p>'+
  '<div class="training-metrics"><div>'+B('更新前 batch MSE','Batch MSE before')+'<output id="train-before"></output></div><div>'+B('更新后 batch MSE','Batch MSE after')+'<output id="train-after"></output></div><div>'+B('已完成参数更新','Completed updates')+'<output id="train-iteration">0</output></div></div><div class="table-wrap"><table class="training-parameters"><thead><tr>'+['参数','更新前 θ','batch 梯度 g','改变量 −ηg','候选 θ − ηg'].map((zh,i)=>'<th>'+B(zh,['Parameter','Before θ','Batch gradient g','Change −ηg','Candidate θ − ηg'][i])+'</th>').join('')+'</tr></thead><tbody id="train-parameters" data-i18n-dynamic></tbody></table></div></div></div>'+
  '<div class="training-bottom"><div><h4>'+B('跟踪这一个像素','Trace this pixel')+'</h4><div id="train-pixel-detail" data-i18n-dynamic></div></div><figure><figcaption>'+B('实际 batch 损失（初始值 + 每次已完成更新）','Measured batch loss (initial + each completed update)')+'</figcaption><canvas id="train-loss-chart" width="600" height="240" role="img" aria-label="'+B('训练损失曲线，数值摘要见下方','Training loss curve; numeric summary below')+'"></canvas><p id="train-loss-summary" data-i18n-dynamic></p></figure></div>'+
  '<details class="training-code"><summary>'+B('与 PyTorch、真实训练和引擎的对应关系','Connection to PyTorch, real training, and the engine')+'</summary><p>'+B('步骤 1–5 对应取 batch、render 和计算 loss；步骤 6 对应 loss.backward()；步骤 7–8 对应 optimizer.step() 和下一次前向。本页每轮重新累积梯度，等价于先清零；位置梯度包含中心与协方差两条路径。这里使用解析梯度与 SGD，下面链接的 PyTorch toy trainer 使用自动微分与 Adam。','Stages 1–5 select the batch, render, and compute loss; stage 6 corresponds to loss.backward(); stages 7–8 to optimizer.step() and another forward pass. Gradients are accumulated afresh each iteration, equivalent to clearing them first. Position gradients include both center and covariance paths. This lab uses analytic gradients and SGD; the linked PyTorch toy trainer uses autograd and Adam.')+'</p><p>'+B('可见性、alpha 阈值和排序有离散分支，梯度按当前分支计算；跨过边界或学习率过大时损失可能上升。单相机、少量参数的合成拟合不能证明真实多视角重建能力。RGB 在本 STG-Lite 格式中是直接颜色，当前实验不训练 SH。','Visibility, alpha thresholds, and sorting contain discrete branches; gradients follow the current branch. Crossing a boundary or taking a large step can increase loss. A small single-camera synthetic fit does not establish real multi-view reconstruction quality. STG-Lite stores direct RGB here; this experiment does not train SH.')+'</p><a href="'+excerpts['train-loop'].href+'">PyTorch · train_toy_stg.py ↗</a> · <a href="'+excerpts['training-step'].href+'">JavaScript · training.mjs ↗</a></details></section>';
}

[
 ['展开原有单像素实验与完整数值表','Open the original single-pixel lab and full numeric tables'],
 ['下一小步 →','Next stage →'],['开始下一轮 →','Start next iteration →'],['播放本轮','Play this iteration'],['暂停','Pause'],
 ['全宽训练视图','Expand training view'],['返回手册布局','Return to handbook layout'],
 ['第 {iteration} 轮 · 小步 {stage}/8 · {state}','Iteration {iteration} · stage {stage}/8 · {state}'],
 ['参数尚未更新','Parameters not updated yet'],['本轮已更新一次','This iteration was applied once'],
 ['自动训练中；可随时暂停','Training automatically; pause at any time'],['已暂停','Paused'],
 ['已达到 500 轮；重置可重新观察','Reached 500 iterations; reset to start again'],
 ['这一步损失上升，可回退或降低学习率。','Loss rose on this step; go back or lower the learning rate.'],
 ['第 3 小步显示屏幕椭圆','Screen ellipses appear at stage 3'],['第 5 小步显示误差','Errors appear at stage 5'],
 ['像素 p = {pixel}，t = {time}','Pixel p = {pixel}, t = {time}'],
 ['A 的 Δt = {dt}；μ(t) = {mean}；基础 opacity = {opacity}','A: Δt = {dt}; μ(t) = {mean}; base opacity = {opacity}'],
 ['A 的屏幕中心 = {uv}；C = {covariance}','A: screen center = {uv}; C = {covariance}'],
 ['近→远 {order}；A 的 alpha = {alpha}，T = {transmittance}','Near→far {order}; A: alpha = {alpha}, T = {transmittance}'],
 ['预测 {prediction}；目标 {target}；本像素 MSE = {loss}','Prediction {prediction}; target {target}; pixel MSE = {loss}'],
 ['此像素更新前：∂Lₙ/∂α = {lossAlpha}；∂α/∂μ₀x = {alphaMean}；相乘 = {meanGradient}','Before update, this pixel: ∂Lₙ/∂α = {lossAlpha}; ∂α/∂μ₀x = {alphaMean}; product = {meanGradient}'],
 ['均值路径 {meanPath} + 协方差路径 {covariancePath} = {alphaMean}','Center path {meanPath} + covariance path {covariancePath} = {alphaMean}'],
 ['运动梯度再乘 Δt = {dt}；表格是全部 360 像素的平均，不是只用这个像素。','Motion gradient also multiplies by Δt = {dt}; the table averages all 360 pixels, not just this pixel.'],
 ['初始 {initial} → 当前 {current}；共 {count} 次更新','Initial {initial} → current {current}; {count} updates'],
 ['计算遇到问题；已暂停。请重置训练。','Calculation failed; paused. Please reset training.'],
].forEach(([zh,en])=>{trainingTranslations[zh]=en;});
