export const B=(en,zh)=>({en,zh});
const p=B;
const S=(title,paragraphs,formula)=>({title,paragraphs,formula});
// § is expanded to a LaTeX backslash by the builder.
export const chapters=[
{id:'01-light-and-color',title:B('A color is not a material','颜色不等于材质'),goal:B('Separate camera motion, light motion and material changes.','分清转相机、转光源与改材质。'),code:['src/relight.rs','asset'],sections:[
S(B('Start with a painted orange','从一个涂成橙色的球开始'),[
p('A photo records light that reached the camera. An orange patch may look dark because its paint is dark, its normal faces away, or another object blocks the light. One RGB value cannot tell you which explanation is correct.','照片记录的是到达相机的光。一块橙色区域可能因为颜料暗、表面背着光，或被其他物体挡住而变暗。单个 RGB 无法告诉你是哪一种原因。'),
p('Base color is a material parameter in linear RGB. For a dielectric it controls diffuse reflectance; for a metal it sets colored specular reflectance in our metallic workflow. Observed RGB already mixes material, illumination, visibility and camera response.','Base color 是线性 RGB 材质参数。对非金属，它控制漫反射反射率；在这里的金属度工作流中，对金属它控制有色镜面反射。观察到的 RGB 已混合材质、光照、遮挡与相机响应。')]),
S(B('Why appearance SH cannot simply accept a new light','为什么外观 SH 不能直接接收一盏新灯'),[
p('Ordinary appearance SH stores a function of viewing direction v. Its RGB coefficients were fitted under the capture lighting. Moving the camera changes v; moving a light does not change those stored coefficients. A new light is a new input the original model was never asked to explain.','普通外观 SH 存的是观察方向 v 的函数。RGB 系数在拍摄光照下拟合得到。移动相机改变 v；移动光源不会改变已存系数。新光照是原模型没有被要求解释的新输入。'),
p('The current STG-Lite loader uses direct RGB, not a general SH material. Its normal-named slots are not a verified surface-normal field. This lab therefore uses an analytic surface with authored normals and materials. It does not recover materials from that research asset.','当前 STG-Lite 加载器使用直接 RGB，而非通用 SH 材质。名字像法线的槽位也不是已验证的表面法线。因此本实验使用解析曲面与明确设置的法线、材质，并没有从原研究资产恢复材质。')],'c(§mathbf v)=§sum_k §mathbf c_kY_k(§mathbf v)§qquad§text{versus}§qquad L_o=R(§text{geometry},§text{material},§text{light},§mathbf v)'),
S(B('Try one controlled change','一次只改一个变量'),[
p('Select Base color in the lab and move the light: the surface color must stay fixed. Switch to Combined: now the lit region moves. Finally rotate the camera: the specular response changes even though the light stays in world space.','在实验中选择 Base color 并移动光源：表面颜色应该保持不变。切到合成结果，亮区才跟着光源移动。最后转动相机：光源仍固定在世界空间，高光响应却改变了。')])
],task:B('Why is multiplying captured RGB by a new Lambert term usually wrong?','为什么把拍到的 RGB 再乘一次新的 Lambert 项通常不对？'),answer:B('The old shading is already baked into captured RGB. Multiplication adds new shading without removing old shadows or highlights.','旧光照已烘进 RGB。再乘新着色没有去掉旧光照，所以旧阴影和高光还会留下。')},

{id:'02-count-the-light',title:B('Count the light, one direction at a time','把每个方向的光加起来'),goal:B('Build the rendering equation from multiplication and addition.','从乘法与加法搭出渲染方程。'),code:['src/relight.wgsl','brdf'],sections:[
S(B('A tilted card catches less light','倾斜的卡片接到的光更少'),[
p('n is a unit arrow out of the surface; l points from the surface toward the light. Their dot product is cos θ: multiply matching x, y, z components and add. Straight toward the light gives 1; sideways gives 0. Negative means light is behind the surface, so clamp it to 0.','n 是朝向表面外侧的单位箭头，l 从表面指向光源。点积等于 cos θ：对应的 x、y、z 分量相乘再相加。正对光源为 1，侧对为 0，负数表示光源在背后，所以截断为 0。'),
p('For n=(0,0,1), l=(0.6,0,0.8), the dot product is 0×0.6+0×0+1×0.8=0.8. A fixed beam spreads over a larger tilted area; this projected-area factor gives the patch 80% of the perpendicular illumination.','n=(0,0,1)，l=(0.6,0,0.8) 时，点积是 0×0.6+0×0+1×0.8=0.8。同一束光落在倾斜表面会铺得更开；投影面积因子使它接到正对光源时 80% 的照明。')],'q=§max(0,§mathbf n§cdot§mathbf l)=§max(0,n_xl_x+n_yl_y+n_zl_z)'),
S(B('Why divide by π?','为什么要除以 π？'),[
p('Reflectance ρ is the fraction of incident power reflected by a diffuse surface. Its Lambert BRDF is ρ/π. Outgoing directions share the reflected energy: integrating the cosine over a hemisphere gives π, so division by π makes the total reflected fraction exactly ρ.','漫反射反射率 ρ 是入射功率中被反射的比例，Lambert BRDF 是 ρ/π。反射能量要分配给所有出射方向：半球上余弦的积分为 π，所以除以 π 才能让总反射比例恰好为 ρ。'),
p('Here is the integral in small steps. Integrating azimuth φ from 0 to 2π gives 2π. For the angle from the normal θ, substitute u=sin θ in ∫cos θ sin θ dθ. Between 0 and π/2 it becomes [u²/2]₀¹=1/2. Multiply: 2π×1/2=π.','积分可拆成小步：方位角 φ 从 0 到 2π 积分得到 2π；对与法线的夹角 θ，在 ∫cos θ sin θ dθ 中令 u=sin θ，从 0 到 π/2 得到 [u²/2]₀¹=1/2。两者相乘就是 2π×1/2=π。')],'§int_0^{2§pi}§int_0^{§pi/2}§cos§theta§sin§theta§,d§theta§,d§phi=§pi,§qquad f_d=§frac{§rho}{§pi}'),
S(B('From one light to the hemisphere','从一盏灯到整个半球'),[
p('For our ideal distant directional light, E⊥ is irradiance on a patch facing the light. Pure Lambert radiance is (ρ/π)E⊥q. With ρ=0.6, E⊥=2, q=0.8, it is 0.6×2×0.8/π≈0.3056. This is linear radiance, not a display byte. Our GGX lab additionally reserves Fresnel energy, multiplying diffuse by (1−F).','对理想远处平行光，E⊥ 是正对光线的小面片所受辐照度。纯 Lambert 辐亮度为 (ρ/π)E⊥q。ρ=0.6、E⊥=2、q=0.8 时，得到 0.6×2×0.8/π≈0.3056。这是线性辐亮度，不是显示字节。GGX 实验还为 Fresnel 反射保留能量，漫反射另乘 (1−F)。'),
p('Split the sky into small solid-angle patches Δω. Each contributes BRDF × incident radiance × visibility × cosine × patch size. Add them all; shrinking patches turns the sum into an integral. Visibility V is 0 for a blocked direction and 1 for a clear one.','把天空分成小立体角块 Δω。每块贡献为 BRDF × 入射辐亮度 × 可见性 × 余弦 × 块大小。全部加起来；把块越分越小，加法就变成积分。方向被挡住时可见性 V=0，畅通时 V=1。')],'L_o(§mathbf x,§mathbf v)=L_e+§int_{§Omega^+}f_r(§mathbf x,§mathbf l,§mathbf v)L_i(§mathbf x,§mathbf l)V(§mathbf x,§mathbf l)§max(0,§mathbf n§cdot§mathbf l)§,d§omega')
],task:B('What happens to pure Lambert radiance when q changes from 0.8 to 0.4?','q 从 0.8 变为 0.4，纯 Lambert 辐亮度怎样变化？'),answer:B('With material and light fixed, it halves. This applies before nonlinear tone mapping.','材质与光照固定时，辐亮度减半。这在非线性色调映射之前成立。')},

{id:'03-a-moving-highlight',title:B('Build a moving highlight','做出会移动的高光'),goal:B('Read every factor in the actual GGX shader.','读懂实际 GGX shader 的每一个因子。'),code:['src/relight.wgsl','brdf'],sections:[
S(B('Imagine tiny mirrors','想象表面有很多小镜子'),[
p('A rough surface has tiny facets pointing in different directions. Facets facing the halfway vector h between light l and viewer v reflect that light toward the viewer. Normalize l+v to get h. D describes their orientation density; G discounts tiny facets hidden by others; F describes angle-dependent reflectance.','粗糙表面可想象成朝向各异的小镜面。朝向光线 l 和观察方向 v 之间半程向量 h 的小镜面，能把光反到观察者。把 l+v 归一化得到 h。D 描述朝向密度，G 扣除被其他小镜面挡住的部分，F 描述随角度变化的反射率。'),
p('These are model choices, not consequences of Gaussian density. We use single-scattering GGX, separable Smith masking and Schlick Fresnel. PBRT explains the full statistical derivation; here we unpack the exact shader model.','这些是着色模型选择，不是从高斯密度推出来的。这里使用单次散射 GGX、可分离 Smith 遮蔽和 Schlick Fresnel。完整统计推导见 PBRT；这里拆解实际 shader 模型。')],'§mathbf h=§frac{§mathbf l+§mathbf v}{§|§mathbf l+§mathbf v§|},§qquad f_s=§frac{DFG}{4(§mathbf n§cdot§mathbf l)(§mathbf n§cdot§mathbf v)}'),
S(B('Roughness controls the spread','粗糙度控制高光分布'),[
p('The slider is perceptual roughness r. Square it to get a=r², then use a²=r⁴ in D. Let nh=max(n·h,0). Compute nh², multiply by (a²−1), add 1, square, multiply by π, then divide a² by that result. Lower roughness makes a narrower, taller highlight.','滑块是感知粗糙度 r。先平方得到 a=r²，D 中使用的 a² 就是 r⁴。令 nh=max(n·h,0)：计算 nh²，乘以 (a²−1)，加 1，再平方、乘 π，最后用 a² 除以结果。更低的粗糙度使高光更窄、更高。'),
p('At r=0.5 and nh=1, a=0.25, a²=0.0625, D=1/(π×0.0625)≈5.093. D is a density, not a color, so values above 1 are valid. We clamp r to at least 0.12 because this coarse surfel scene cannot resolve near-perfect mirror highlights.','r=0.5、nh=1 时，a=0.25、a²=0.0625，D=1/(π×0.0625)≈5.093。D 是密度，不是颜色，大于 1 合法。这个粗粒度 surfel 场景无法稳定表达近乎完美镜面的高光，所以 r 最小取 0.12。')],'a=r^2,§quad D=§frac{a^2}{§pi[(§mathbf n§cdot§mathbf h)^2(a^2-1)+1]^2},§quad G_1(q)=§frac{2q}{q+§sqrt{a^2+(1-a^2)q^2}},§quad G=G_1(nl)G_1(nv)'),
S(B('Split diffuse and specular energy','分开漫反射与镜面反射'),[
p('For a typical dielectric choose normal-incidence reflectance F₀=0.04. The metallic workflow interpolates it toward base color b as metallic m approaches 1. Schlick adds a grazing-angle increase using (1−v·h)⁵. This is an approximation; 0.04 is not universal.','典型非金属取垂直入射反射率 F₀=0.04。金属度 m 接近 1 时，将它插值到 base color b。Schlick 用 (1−v·h)⁵ 增加掠射角反射。这是近似，0.04 并非普适常数。'),
p('The diffuse factor (1−F)(1−m) removes diffuse reflection at m=1. The lab isolates Diffuse and Specular before display mapping. It includes no subsurface scattering, transmission or microfacet multiple-scattering compensation.','漫反射因子 (1−F)(1−m) 使 m=1 时漫反射为零。实验在显示映射前分离 Diffuse 和 Specular，没有次表面散射、透射或微表面多次散射补偿。')],'F_0=(1-m)0.04+m§mathbf b,§quad F=F_0+(1-F_0)(1-§mathbf v§cdot§mathbf h)^5,§quad f_d=§frac{(1-F)(1-m)§mathbf b}{§pi}'),
S(B('Work through one numerical example','完整代入一次'),[
p('Take n=l=v=(0,0,1), r=0.5, m=0, red base color bᵣ=0.55, E⊥=3. Then h=n, G=1, F=0.04. Specular BRDF =5.093×0.04/4≈0.05093; diffuse BRDF =0.96×0.55/π≈0.16807. Red outgoing radiance =(0.05093+0.16807)×1×3≈0.6570.','取 n=l=v=(0,0,1)、r=0.5、m=0、红通道 bᵣ=0.55、E⊥=3。此时 h=n、G=1、F=0.04。镜面 BRDF=5.093×0.04/4≈0.05093；漫反射 BRDF=0.96×0.55/π≈0.16807。出射红通道辐亮度=(0.05093+0.16807)×1×3≈0.6570。')])
],task:B('Why can metal have colored highlights and zero diffuse response here?','为什么这里的金属会有彩色高光而漫反射为零？'),answer:B('Base color becomes F₀, while (1−metallic) removes the diffuse lobe. A colored dielectric instead has colored diffuse and mostly neutral specular reflection under white light.','Base color 进入 F₀，而 (1−metallic) 去掉漫反射瓣。有色非金属在白光下则是有色漫反射和大体中性的镜面反射。')},

{id:'04-shading-to-splats',title:B('Send light through the splat pipeline','让反射光走完 splat 管线'),goal:B('Follow two GPU passes and their color spaces.','走通两个 GPU pass 与颜色空间。'),code:['src/relight.rs','render'],sections:[
S(B('Shade the surfel, project the footprint','着色 surfel，投影覆盖区域'),[
p('The asset has 1,536 thin Gaussian ellipsoids on an analytic sphere. Each stores a center, three covariance axes, an outward normal and linear base color. Roughness and metallic are uniform across this object. WGSL shades each center, holding that radiance constant across its footprint.','资产由解析球面上的 1,536 个薄高斯椭球组成。每个有中心、三个协方差轴、朝外法线和线性 base color。粗糙度与金属度在整个物体上统一。WGSL 在中心着色，辐亮度在该点的覆盖区域内保持不变。'),
p('This approximates a surface using 3D Gaussian footprints; it is not the perspective-correct 2DGS algorithm. CPU code transforms and sorts centers far-to-near. WGSL projects covariance, expands a three-sigma quad and evaluates Gaussian weight. Overlap makes it nearly opaque, with soft silhouettes.','这里用 3D Gaussian 足迹近似表面，并不是透视正确的 2DGS 算法。CPU 变换中心并由远及近排序；WGSL 投影协方差，展开三倍标准差的四边形，求高斯权重。叠加使它接近不透明，但轮廓柔软。')],'§Sigma=UU^T,§quad U=[§mathbf u§ §mathbf v§ §mathbf w],§quad §Sigma_{2D}=J§Sigma J^T+0.3I,§quad §alpha=o§exp(-§tfrac12§|§mathbf q§|^2)'),
S(B('Add linear light, then tone-map','先在线性空间合光，再做色调映射'),[
p('Fragments write (αL,α) into RGBA16Float. In far-to-near order, premultiplied blending computes new=αL+(1−α)old. Because α is already included, the source blend factor is One. Using SourceAlpha again would incorrectly square α.','片元向 RGBA16Float 写入 (αL,α)。由远及近绘制时，预乘透明合成是 new=αL+(1−α)old。由于已经乘过 α，源混合因子是 One；再次用 SourceAlpha 会错误地把 α 平方。'),
p('A fullscreen pass adds visible background, applies per-channel Reinhard x/(1+x), then encodes to sRGB once. sRGB attachments encode automatically; a UNORM canvas needs explicit encoding. Normal/base-color debug modes skip Reinhard.','全屏 pass 加入未被遮住的背景，逐通道应用 Reinhard x/(1+x)，最后只编码一次 sRGB。sRGB 附件自动编码，UNORM 画布需显式编码。法线与 base-color 调试模式跳过 Reinhard。')],'C_{§rm new}=§alpha L+(1-§alpha)C_{§rm old},§quad T(x)=§frac{x}{1+x},§quad s(x)=§begin{cases}12.92x&x§le0.0031308§§1.055x^{1/2.4}-0.055&x>0.0031308§end{cases}'),
S(B('What is and is not implemented','哪些已经实现'),[
p('The convex shape has one distant white light. There is no cast-shadow pass, environment map, indirect light, inverse-material estimator or training optimizer. Backface rejection is not a general light-visibility solution. Concave scenes need visibility data or ray/shadow queries.','凸形状受一盏远处白色平行光照射。没有投射阴影 pass、环境贴图、间接光、逆材质估计器或训练优化器。背面剔除不能替代一般光照可见性求解。凹陷场景需要可见性数据或光线／阴影查询。'),
p('Native offscreen checks verify light/material response, roughness, deformation and camera changes. Windows/DX12 and browser behavior are tested here; sharing WGSL does not certify untested Metal/Vulkan devices.','原生离屏检查验证光照／材质响应、粗糙度、形变与相机变化。这里测试 Windows/DX12 和浏览器行为；共享 WGSL 不代表已验证未测试的 Metal／Vulkan 设备。')])
],task:B('Why not tone-map every Gaussian before blending?','为什么不先对每颗 Gaussian 做色调映射再合成？'),answer:B('Tone mapping is nonlinear: T(αa+(1−α)b) generally differs from αT(a)+(1−α)T(b). Add light in linear HDR first.','色调映射是非线性的，T(αa+(1−α)b) 通常不等于 αT(a)+(1−α)T(b)。应先在线性 HDR 中合光。')},

{id:'05-sh-lighting',title:B('Use SH for light, not just appearance','SH 不只表达外观，也能表达光照'),goal:B('Understand lighting coefficients, transfer and TranSplat.','理解光照系数、传输与 TranSplat。'),code:['src/relight.wgsl','brdf'],sections:[
S(B('Same basis, different functions','同一套基底，不同的函数'),[
p('Appearance SH maps outgoing viewing direction to captured RGB. Lighting SH maps incoming direction to environment radiance. Both can use Yₖ, but coefficients represent different functions. Each RGB channel is evaluated separately, then combined for display.','外观 SH 把出射观察方向映射到捕获 RGB；光照 SH 把入射方向映射到环境辐亮度。两者可用相同 Yₖ，但系数代表不同函数。RGB 各通道独立求值，最后合成显示。'),
p('Our BRDF v points from surface to camera. Some GS appearance code uses camera-to-Gaussian instead. Negating a direction changes odd SH band signs: never copy coefficients without checking direction, normalization and basis ordering.','这里 BRDF 的 v 从表面指向相机。有些 GS 外观代码使用相机指向 Gaussian。方向取反会改变奇数阶 SH 符号，所以复制系数前必须核对方向、归一化与基函数顺序。')],'L_{§rm env}(§boldsymbol§omega)§approx§sum_k§boldsymbol§ell_kY_k(§boldsymbol§omega),§qquad §boldsymbol§ell_k=§int_{§mathbb S^2}L_{§rm env}(§boldsymbol§omega)Y_k(§boldsymbol§omega)§,d§omega'),
S(B('Turn the integral into a dot product','把积分变成点积'),[
p('Define transfer K(ω)=V(ω)max(n·ω,0). Expand light and transfer in the same orthonormal real SH basis. Multiply their sums and integrate. Different basis pairs integrate to zero, matching pairs to one. Only matching coefficient products remain.','定义传输 K(ω)=V(ω)max(n·ω,0)。将光照与传输展开到同一组标准正交实 SH 基底。两个求和相乘再积分，不同基函数对积分为 0，相同基函数对为 1，只剩对应系数相乘再相加。'),
p('For unoccluded diffuse light the cosine kernel is smooth. Bands l=0,1,2 give 1+3+5=9 coefficients per channel, often a good approximation of irradiance. Sharp shadows and mirror reflections need more directional detail. Moving geometry changes K even with a fixed environment.','无遮挡漫反射的余弦核很平滑。l=0、1、2 阶每通道共 1+3+5=9 个系数，往往能较好近似辐照度。锐利阴影与镜面反射需要更多方向细节。即使环境固定，运动几何也会改变 K。')],'E=§int L_{§rm env}K§,d§omega§approx§sum_{i,j}§boldsymbol§ell_iK_j§underbrace{§int Y_iY_j§,d§omega}_{§delta_{ij}}=§sum_k§boldsymbol§ell_kK_k,§quad L_d=§frac{§rho}{§pi}E'),
S(B('Why an irradiance ratio can help','为什么辐照度比率能派上用场'),[
p('In a purely diffuse thought experiment, with unchanged normals and visibility, old color is proportional to ρEold and new color to ρEnew. Dividing cancels ρ. The ratio fails when old irradiance is tiny, shadows change, or specularity violates the assumption. A denominator floor prevents numerical explosion; it does not recover missing information.','在法线与可见性不变的纯漫反射思想实验中，旧颜色正比于 ρEold，新颜色正比于 ρEnew，相除可以消去 ρ。当旧辐照度很小、阴影改变或存在镜面反射时，假设会失效。分母下限能防止数值爆炸，却不能恢复缺失信息。'),
p('TranSplat (ICCP 2026) transfers trained oriented 2D Gaussian surfels using source/target environment maps, with separate specular treatment. Its official code was released in July 2026. It is a useful reproduction target, not a direct conversion of this STG-Lite asset. This simple ratio explains an intuition, not the complete method.','TranSplat（ICCP 2026）使用源／目标环境贴图转移已训练的有方向 2D Gaussian surfel，并单独处理镜面反射。官方代码于 2026 年 7 月发布。它适合后续复现，但不能直接转换当前 STG-Lite 资产。这个简单比率只解释直觉，不是完整方法。')],'§mathbf c_{§rm new}§approx§mathbf c_{§rm old}§odot§frac{§mathbf E_{§rm new}}{§max(§mathbf E_{§rm old},§varepsilon)}')
],task:B('Can nine lighting SH coefficients accurately reproduce a tiny sharp highlight?','九个光照 SH 系数能准确复现很小很锐利的高光吗？'),answer:B('Usually no. Low-order SH loses high-frequency detail. Specular IBL commonly uses prefiltered environment maps and a BRDF lookup, or more expensive integration.','通常不能。低阶 SH 丢失高频细节。镜面 IBL 常用预过滤环境贴图和 BRDF 查表，或更昂贵的积分。')},

{id:'06-learn-the-material',title:B('Learn materials without learning the wrong thing','怎样学习材质，避免把光学错'),goal:B('Trace inverse rendering from observations to a relightable asset.','从观测数据走到可重打光资产。'),code:['src/relight.rs','asset'],sections:[
S(B('One pixel has many explanations','一个像素有很多种解释'),[
p('Diffuse observations contain the product ρE. Doubling reflectance and halving illumination leaves a pixel unchanged, within valid material ranges. More camera views constrain geometry but do not automatically resolve all material-light ambiguity under the same illumination.','漫反射观测包含乘积 ρE。在合法材质范围内，反射率加倍、光照减半，像素保持不变。更多相机视角约束几何，但在同一光照下不会自动消除全部材质与光照歧义。'),
p('At cosine 1, Lambert radiance 0.24 can come from ρ=0.3 and E=0.8π, or ρ=0.6 and E=0.4π. Zero loss on that pixel proves neither material estimate correct.','余弦为 1 时，Lambert 辐亮度 0.24 可以来自 ρ=0.3、E=0.8π，也可以来自 ρ=0.6、E=0.4π。单个像素损失为零，不能证明材质估计正确。')],'§frac{§rho E}{§pi}=§frac{(k§rho)(E/k)}{§pi}'),
S(B('One training iteration, end to end','一轮训练从头到尾'),[
p('1. Pick a calibrated camera, time and reference image; linearize the image with a known or modeled camera response. 2. Evaluate canonical Gaussians and deformation. 3. Project geometry and obtain normals/visibility. 4. Evaluate BRDF under estimated light and composite the image.','1. 选标定相机、时间与参考图，用已知或建模的相机响应线性化图像。2. 求值 canonical Gaussians 与形变。3. 投影几何并取得法线／可见性。4. 在估计光照下计算 BRDF 并合成图像。'),
p('5. Compare predicted pixels to observations; add geometry, material and temporal constraints. 6. Backpropagate through differentiable projection, shading and compositing; update selected parameters. 7. Repeat across views/lights; test held-out lighting. Densification must initialize new material attributes consistently.','5. 比较预测与观测，加入几何、材质和时间约束。6. 沿可微投影、着色和合成反向传播，更新选定参数。7. 跨视角／光照重复，在未用于训练的光照下评估。增密时必须一致地初始化新点的材质属性。')],'§min_{§Theta_g,§Theta_m,§Theta_L,§Theta_d}§sum_{c,t}§|R(§Theta_g,§Theta_m,§Theta_L,§Theta_d;c,t)-I_{c,t}§|_1+§lambda_n§mathcal L_n+§lambda_m§mathcal L_m+§lambda_t§mathcal L_t'),
S(B('Constrain the problem before scaling it up','先约束问题，再扩大规模'),[
p('Known lights, calibrated exposure, multiple illumination conditions, reliable geometry/normals and material priors constrain different ambiguities. Begin with a synthetic object whose cameras, lights and materials are known. Then try real scenes.','已知光源、曝光标定、多光照条件、可靠几何／法线与材质先验，分别约束不同歧义。先从相机、光照、材质都已知的合成物体开始，再尝试真实场景。'),
p('GS-IR and Relightable 3D Gaussian provide released training code. Their CUDA rasterizers, datasets, checkpoints and exports are separate from this viewer. This site links them but does not claim a reproduced training run. Our implementation is the known-material forward renderer.','GS-IR 与 Relightable 3D Gaussian 提供训练代码。它们的 CUDA rasterizer、数据、checkpoint 和导出独立于当前 Viewer。本站提供链接，但不声称复现了训练。我们实现的是已知材质的前向渲染器。')])
],task:B('Why is high novel-view PSNR insufficient evidence of successful relighting?','为什么新视角 PSNR 很高仍不足以证明重打光成功？'),answer:B('The model may reproduce old lighting with baked shadows. Validate unseen lights, material/normal consistency and temporal stability, not only new cameras under the old light.','模型可能仅用烘焙阴影复现旧光照。需验证未见光照、材质／法线一致性和时间稳定性，不能只在旧光照下换相机。')},

{id:'07-moving-normals',title:B('Add time without breaking the light','加入时间，别让光照出错'),goal:B('Derive inverse-transpose normals and dynamic visibility.','推导逆转置法线与动态可见性。'),code:['src/relight.rs','deformation'],sections:[
S(B('Keep the normal perpendicular','让法线始终垂直'),[
p('A tangent t lies along a surface and its normal n is perpendicular: nᵀt=0. A local linear deformation A turns the tangent into At. We need a new normal whose dot product with At is still zero.','切线 t 沿着表面，法线 n 与它垂直，即 nᵀt=0。局部线性形变 A 把切线变成 At。我们需要新法线与 At 的点积仍为零。'),
p('Choose n′=A⁻ᵀn. Transpose it: n′ᵀ=nᵀA⁻¹. Then n′ᵀAt=nᵀA⁻¹At=nᵀt=0. The inverse cancels the deformation. Normalize the result because the BRDF needs unit directions.','取 n′=A⁻ᵀn，转置后 n′ᵀ=nᵀA⁻¹。于是 n′ᵀAt=nᵀA⁻¹At=nᵀt=0，逆矩阵抵消形变。最后归一化，因为 BRDF 需要单位方向。')],'(A^{-T}§mathbf n)^T(A§mathbf t)=§mathbf n^TA^{-1}A§mathbf t=0,§qquad §mathbf n^{§prime}=§frac{A^{-T}§mathbf n}{§|A^{-T}§mathbf n§|}'),
S(B('Stretch a diagonal surface by hand','手算倾斜表面的拉伸'),[
p('In 2D take n=(1,1)/√2 and t=(1,−1). Stretch x by 2: A=diag(2,1), so t′=(2,−1). Correct n′ is proportional to (1/2,1), giving dot product 1−1=0. The tempting An is proportional to (2,1), giving 4−1=3 instead.','二维中取 n=(1,1)/√2，t=(1,−1)。令 A=diag(2,1) 将 x 拉伸两倍，新切线 t′=(2,−1)。正确 n′ 正比于 (1/2,1)，点积 1−1=0。容易误用的 An 正比于 (2,1)，点积却是 4−1=3。'),
p('For pure rotation R, R⁻ᵀ=R; rotating positions and normals alike works. Nonuniform scale or shear breaks this shortcut. Set time to 0.25 in the lab and toggle the intentionally wrong transform to see the shading error.','纯旋转 R 满足 R⁻ᵀ=R，位置与法线用同样的旋转没问题。非均匀缩放或剪切会让捷径失效。在实验里把时间设为 0.25，再切换故意错误的变换，观察着色错误。')]),
S(B('Time also changes visibility','时间也会改变可见性'),[
p('For nonlinear motion x′=f(x,t), use local A=∂f/∂x. Transport covariance by AΣAᵀ, normals by A⁻ᵀ, and material identity with the canonical point. Degenerate A needs rejection or a defined fallback. A separately learned normal field needs supervision or consistency constraints.','非线性运动 x′=f(x,t) 应使用局部 A=∂f/∂x。协方差按 AΣAᵀ 传输，法线按 A⁻ᵀ 传输，材质身份跟随 canonical 点。退化 A 需要拒绝或明确回退。独立学习的法线场则需要监督或一致性约束。'),
p('Moving geometry changes light visibility V(x,l,t); a static occlusion bake cannot follow a moving blocker. BEAM studies volumetric video, BecomingLit specializes in heads, and DR-GS drives reconstructed assets with simulation/animation. These are different dynamic settings, not interchangeable 4DGS loaders.','运动几何改变光照可见性 V(x,l,t)，静态遮挡烘焙无法跟随运动遮挡物。BEAM 研究体积视频，BecomingLit 专注头部，DR-GS 用模拟／动画驱动重建资产。这些是不同动态设定，不是可互换的 4DGS 加载器。')])
],task:B('Can a moving object change shading and shadows even with a fixed light and camera?','光源和相机不动，运动物体能改变着色与阴影吗？'),answer:B('Yes. Its normal changes the BRDF/cosine and its geometry changes light visibility. The material can stay the same while both effects vary.','能。法线改变 BRDF／余弦，几何改变光照可见性。材质可以不变，而两种效果都会变化。')},

{id:'08-engine-roadmap',title:B('Bring relighting into the engine','把重打光接进引擎'),goal:B('Separate working capabilities from the next implementation milestones.','区分已实现能力与后续实现里程碑。'),code:['src/relight.rs','render'],sections:[
S(B('Define the asset contract first','先定义资产契约'),[
p('Declare version, units, coordinates, center/covariance/opacity, oriented normals, linear material fields, time/deformation binding and visibility convention. State whether color means base color, captured radiance or a learned residual. Never silently reinterpret an old RGB field.','声明版本、单位、坐标、中心／协方差／不透明度、有方向法线、线性材质字段、时间／形变绑定与可见性约定。明确颜色代表 base color、捕获辐亮度还是学习残差。绝不能默默改变旧 RGB 字段的含义。'),
p('The teaching layout is 96 bytes: six vec4 values. Roughness and metallic are frame uniforms for our single-material object. A real importer validates material attributes, rejects nonfinite values and declares missing capabilities.','教学布局是六个 vec4，共 96 字节。单材质物体的粗糙度与金属度存为逐帧 uniform。真实导入器应验证材质属性、拒绝非有限数并声明缺失能力。')]),
S(B('Choose where shading happens','选择着色阶段'),[
p('Here we shade each Gaussian then blend radiance. Deferred shading instead splats a G-buffer and shades pixels later. It may reduce repeated BRDF work, but averaging normals/roughness before nonlinear shading is not equivalent to blending shaded surfaces.','这里先着色每颗 Gaussian，再合成辐亮度。Deferred 着色先 splat 到 G-buffer，再逐像素着色，可减少重复 BRDF 计算；但非线性着色前先平均法线／粗糙度，不等于合成已经着色的表面。'),
p('The host owns the surface, clock and input. RelightPass owns GPU resources and records commands into a host-provided encoder. It runs in browser WebGPU and native offscreen DX12. Separate passes can later handle shadows and environment prefiltering.','宿主拥有 surface、时钟和输入。RelightPass 管理 GPU 资源，向宿主 encoder 记录命令，可用于浏览器 WebGPU 与原生离屏 DX12。后续可用独立 pass 处理阴影和环境预过滤。')]),
S(B('Five verifiable milestones','五个能验收的里程碑'),[
p('A, implemented: synthetic known materials/normals, direct light, five inspection modes, deformation and HDR composition. B, next: reproduce a released static method, build an explicit asset converter and match its reference renderer under a fixed light.','A，已实现：已知合成材质／法线、直射光、五种观察模式、形变与 HDR 合成。B，下一步：复现已发布静态方法，编写明确资产转换器，在固定光照下对齐参考渲染器。'),
p('C: environment diffuse SH and specular IBL; compare a white Lambert sphere to numerical integration. D: visibility with a moving blocker. E: deform an imported asset with consistent material/normal binding; measure flicker under a fixed light. B–E are planned, not features of this lab.','C：环境漫反射 SH 与镜面 IBL，用白色 Lambert 球对比数值积分。D：加入可见性并测试运动遮挡物。E：对导入资产做一致的材质／法线绑定和形变，测量固定光照下的闪烁。B–E 是计划，不是当前实验已有功能。')]),
S(B('Prepare a convincing explanation before the 28th','28 日前准备能讲透的闭环'),[
p('First reproduce the viewer: covariance, sorting and alpha. Then use one session for Lambert/GGX, one for this lab and its two passes, and one comparing inverse rendering with SH transfer. Be ready to explain material-light ambiguity and dynamic normal/visibility updates.','先复现 Viewer，讲清协方差、排序与 alpha。再用一次学习 Lambert／GGX，一次解释本实验两个 pass，一次比较逆渲染与 SH 转移。要能说明材质光照歧义，以及动态法线／可见性更新。'),
p('Reproducing every recent paper is a much larger project. For this deadline, build evidence: a running core, pixel checks, accurate capability boundaries and a concrete next step.','完整复现所有近期论文是更大的项目。面对截止日期，先建立可验证成果：可运行核心、像素检查、准确能力边界与具体下一步。')])
],task:B('What if an imported model has only appearance SH and no materials?','导入模型只有外观 SH，没有材质，该怎么办？'),answer:B('Use its original appearance renderer and declare relighting unavailable, or run an explicitly identified offline estimation/transfer pipeline. Arbitrary RGB multiplication is not recovered physical relighting.','使用原外观渲染并声明不可重打光，或运行明确的离线估计／转移管线。随意乘 RGB 不等于恢复了物理重打光。')}
];

export const papers=[
{name:'GS-IR · CVPR 2024',url:'https://github.com/lzhnb/GS-IR',kind:B('Static inverse rendering','静态逆渲染'),summary:B('Geometry reconstruction, occlusion baking, then material/lighting estimation. A staged training baseline.','几何重建、遮挡烘焙，再估计材质／光照，适合学习分阶段训练。'),status:B('Official code available','官方代码已发布')},
{name:'Relightable 3D Gaussian · ECCV 2024',url:'https://github.com/NJU-3DV/Relightable3DGaussian',kind:B('Materials + visibility','材质与可见性'),summary:B('Material/lighting decomposition and ray-based visibility in Gaussian reconstruction.','在 Gaussian 重建中进行材质／光照分解，并用光线处理可见性。'),status:B('Official code available','官方代码已发布')},
{name:'GS-ID · ICCV 2025',url:'https://github.com/dukang/gs-id',kind:B('Illumination decomposition','光照分解'),summary:B('Material priors plus environment/local illumination modeling: lighting need not be distant.','材质先验结合环境／局部光照建模，光照不一定来自无限远。'),status:B('Code release pending per repository; README/assets observed','仓库说明代码待发布，目前核对到 README／素材')},
{name:'BEAM · ACM MM 2025',url:'https://arxiv.org/abs/2502.08297',kind:B('Volumetric video','体积视频'),summary:B('Tracked Gaussians with PBR attributes, material estimation and visibility for dynamic relighting.','将跟踪 Gaussian 与 PBR 属性结合，包含动态重打光的材质估计与可见性。'),status:B('Paper verified; runnable official release not verified here','已核对论文；本站未核实可运行官方发布')},
{name:'BecomingLit · NeurIPS 2025',url:'https://github.com/jonathsch/becominglit',kind:B('Head avatars','头部 Avatar'),summary:B('Hybrid neural shading with FLAME and light-stage capture. Specialized data/model assumptions matter.','结合 FLAME 与 light-stage 采集的混合神经着色，需注意其专门的数据／模型假设。'),status:B('Official code; separate model/data access requirements','官方代码已发布；模型／数据另有访问要求')},
{name:'TranSplat · ICCP 2026',url:'https://github.com/tonyyu0822/TranSplat',kind:B('SH radiance transfer','SH 辐亮度转移'),summary:B('Transfers trained 2D Gaussian surfels using source/target HDR lighting and normal-dependent irradiance ratios, with separate specular treatment.','利用源／目标 HDR 光照与随法线变化的辐照度比率，转移已训练 2D Gaussian surfel，并单独处理镜面反射。'),status:B('Official code released July 2026','官方代码于 2026 年 7 月发布')},
{name:'DR-GS · ECCV 2026',url:'https://jiaxinlia.github.io/DR-GS/',kind:B('Deformable assets','可形变资产'),summary:B('Decoupled materials/light on 2D Gaussians, driven by simulation/animation deformation; distinct from learning arbitrary video motion.','在 2D Gaussians 上分离材质／光照，再由模拟／动画驱动形变，不等于从视频学习任意运动。'),status:B('Paper/project available; no code link observed on project page','论文／项目页可用；项目页未见代码链接')}
];
export const resources=[
['https://sites.cs.ucsb.edu/~lingqi/teaching/games101.html',B('GAMES101 · foundations and radiometry','GAMES101 · 基础与辐射度量'),B('Chinese lectures, English slides. Review shading, ray tracing and radiometry; the official page links recordings.','中文讲授、英文课件。复习着色、光线追踪与辐射度量，官方页有录像入口。')],
['https://sites.cs.ucsb.edu/~lingqi/teaching/games202.html',B('GAMES202 · environment lighting, PRT, microfacets','GAMES202 · 环境光照、PRT、微表面'),B('Prioritize environment lighting 1–2 and high-quality shading 1, then shadows. A rendering course, not a GS certificate program.','优先看环境光照 1–2、高质量着色 1，再补阴影。这是渲染课程，不是 GS 专属证书课。')],
['https://pbr-book.org/4ed/Light_Transport_I_Surface_Reflection/The_Light_Transport_Equation',B('PBRT 4 · light transport equation','PBRT 第四版 · 光传输方程'),B('Read after chapter 2; identify the physical quantity behind every symbol. A free online book, not a video course.','第 2 篇后阅读，把符号对应到物理量。免费在线教材，不是视频课程。')],
['https://pbr-book.org/4ed/Reflection_Models/Roughness_Using_Microfacet_Theory',B('PBRT 4 · microfacet derivation','PBRT 第四版 · 微表面推导'),B('The complete distribution, masking and geometry behind the compact shader.','阅读简短 shader 背后的完整分布、遮蔽与几何推导。')],
['https://google.github.io/filament/main/filament.html',B('Filament · PBR engineering notes','Filament · PBR 工程说明'),B('Implementation reference for roughness, Fresnel, IBL and linear color; richer than this teaching subset.','粗糙度、Fresnel、IBL 与线性颜色的实现参考，比这里的教学子集更丰富。')]
];
