// Curated rendering contracts. A public implementation is not a locally verified port.
export const audited = '2026-10-07';
const b = (en, zh) => ({ en, zh });
const gh = (repo, path = '') => `https://github.com/${repo}${path}`;
export const appearanceViewer = 'https://fhahlbohm.github.io/efficient-gaussian-appearance/viewer/';
export const modelBase = 'https://huggingface.co/datasets/fhahlbohm/ngsplat/resolve/main';
export const scenes = ['chair', 'bonsai', 'garden'];
export const groups = {
  geometry: b('Geometry', '几何'), appearance: b('Appearance', '外观'),
  time: b('Time', '时间'), structure: b('Structure', '组织'), material: b('Materials', '材质'),
};
export const access = {
  web: b('Web viewer published', '已有网页 viewer'),
  specialist: b('Dedicated viewer / runtime', '专用 viewer／运行时'),
  code: b('Research code · asset needed', '研究代码 · 需准备模型'),
};
const geometry = b('3D anisotropic ellipsoid', '三维各向异性椭球');
const fixed = b('Static', '静态');
const noPort = b('Not implemented in our Rust viewer', '尚未接入我们的 Rust viewer');
const appearanceRepo = 'nerficg-project/efficient-gaussian-appearance';
const refs = (...items) => items.map(([label, url]) => ({ label, url }));
const commonAppearance = {
  group: 'appearance', maturity: b('Research extension', '研究扩展'), availability: 'web',
  geometry, time: fixed, support: noPort,
  asset: b('Author gallery lists SH, SV, NASG, NASGabor and Neural checkpoints for matching scenes. Use a separately trained file for each mode.', '作者图库列出了同一批场景的 SH、SV、NASG、NASGabor 和 Neural checkpoint。每种模式使用各自训练的文件。'),
  contract: b('Keep the trained direction convention, base/residual activations and output range. A .ngsplat file needs this renderer; a generic PLY loader cannot decode it.', '保留训练时的方向约定、基础色／残差激活和输出范围。.ngsplat 需要对应渲染器，普通 PLY loader 无法解码。'),
};
export const models = [
  {
    id: 'sh', title: b('3DGS · RGB / SH', '3DGS · RGB／SH'), group: 'geometry',
    maturity: b('Established baseline', '成熟基础路线'), availability: 'web', geometry, time: fixed,
    summary: b('Explicit ellipsoids with constant RGB or a direction-dependent color function.', '显式椭球，搭配固定 RGB 或随观察方向变化的颜色函数。'),
    appearance: b('RGB or spherical harmonics', 'RGB 或球谐函数'),
    parameters: b('Center μ; scales s; rotation q; opacity; RGB or per-channel SH coefficients.', '中心 μ、尺度 s、旋转 q、透明度，以及 RGB 或各通道 SH 系数。'),
    learn: b('Optimize geometry, opacity and color coefficients from calibrated images.', '用标定图像优化几何、透明度和颜色系数。'),
    exported: b('Explicit splats. A chosen container may quantize parameters and reduce SH degree.', '显式 splat 参数；所选容器可能量化参数或降低 SH 阶数。'),
    runtime: b('Decode → cull / project → evaluate RGB or SH → sort → rasterize and composite.', '解码 → 剔除／投影 → RGB 或 SH 求值 → 排序 → 光栅化与合成。'),
    contract: b('PLY is a container: inspect its fields, SH order, scale/opacity activations and quaternion order. Point-cloud PLY and STG PLY are not interchangeable with static 3DGS.', 'PLY 是容器：需检查字段、SH 顺序、尺度／透明度激活和四元数顺序。点云 PLY、STG PLY 与静态 3DGS 不能混用。'),
    asset: b('The appearance workbench below links a trained SH model. Spark and PlayCanvas support standard 3DGS in their documented formats.', '下方外观工作台提供训练好的 SH 模型入口。Spark 与 PlayCanvas 支持其文档中列出的标准 3DGS 格式。'),
    support: noPort, labAppearance: 'sh',
    equation: String.raw`\mathbf c_i(\mathbf d)=A\!\left(\mathbf b_i+\sum_k\mathbf a_{ik}Y_k(\mathbf d)\right)`,
    links: refs(['3DGS', 'https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/'], ['Spark formats', 'https://sparkjs.dev/docs/splat-mesh/'], ['PlayCanvas formats', 'https://developer.playcanvas.com/user-manual/gaussian-splatting/formats/']),
  },
  {
    id: '2dgs', title: b('2DGS · oriented surfels', '2DGS · 有方向的面元'), group: 'geometry',
    maturity: b('Established research baseline', '成熟研究基线'), availability: 'web',
    geometry: b('2D elliptical disk in 3D space', '三维空间中的二维椭圆盘'), appearance: b('Usually SH', '通常为 SH'), time: fixed,
    summary: b('Surface elements with two in-plane scales and a normal. The scene is still three-dimensional.', '用面内两轴尺度和法线描述表面元素；整个场景仍然是三维的。'),
    parameters: b('3D center; orientation / tangent frame; two scales; opacity; appearance.', '三维中心、朝向／切线坐标架、两个尺度、透明度和外观。'),
    learn: b('Optimize surfels with image supervision and surface-oriented regularization.', '通过图像监督和面向表面的正则项优化面元。'),
    exported: b('Surfel parameters in the implementation’s schema. A mesh extracted afterward is a different asset.', '按实现约定导出的面元参数。后续提取的 mesh 是另一种资产。'),
    runtime: b('Perspective-correct ray–surfel evaluation → Gaussian weight → ordered compositing.', '透视正确的射线／面元求值 → Gaussian 权重 → 有序合成。'),
    contract: b('Use the 2D rendering mode. Adding a tiny third scale and using ordinary 3D projection is an approximation, not the reference 2DGS renderer.', '使用二维面元渲染模式。补一个很小的第三轴尺度再做普通 3D 投影只是近似，并非参考 2DGS 渲染器。'),
    asset: b('Official code links SIBR and GaussianSplats3D. The web viewer has a “2D scene” file option; bring a matching trained 2DGS file. A public bundled checkpoint has not been verified here.', '官方列出了 SIBR 与 GaussianSplats3D。网页 viewer 的文件选项有“2D scene”，需要匹配的训练文件；此处尚未验证可直接下载的配套 checkpoint。'),
    support: noPort,
    links: refs(['Official 2DGS', gh('hbb1/2d-gaussian-splatting')], ['Web viewer · bring a 2DGS file', 'https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php'], ['Surfel rasterizer', gh('hbb1/diff-surfel-rasterization')]),
  },
  ...[
    {
      id: 'sv', title: b('Spherical Voronoi', '球面 Voronoi'),
      summary: b('Learned directional color sites, blended smoothly for the current view.', '学习一组方向与颜色站点，按当前视角平滑混合。'),
      appearance: b('Soft directional color mixture', '柔和的方向颜色混合'),
      parameters: b('Per-splat unit direction sites, temperatures and RGB values, plus base color.', '每点的单位方向站点、温度参数、RGB 数值与基础色。'),
      learn: b('Learn the sites, their sharpness and colors together with the splats.', '与 splat 一起学习方向站点、过渡锐度和颜色。'),
      exported: b('Normalized sites, activated temperatures / colors, stored in .ngsplat.', '归一化站点及激活后的温度／颜色，存入 .ngsplat。'),
      runtime: b('Direction → site distances → stable softmax → RGB → splatting.', '方向 → 站点距离 → 稳定 softmax → RGB → splatting。'),
      equation: String.raw`w_j={e^{-\tau_j\|\mathbf s_j-\mathbf d\|}\over\sum_k e^{-\tau_k\|\mathbf s_k-\mathbf d\|}},\quad\mathbf r=\sum_j w_j\mathbf c_j`,
    },
    {
      id: 'nasg', title: b('NASG · spherical lobes', 'NASG · 球面波瓣'),
      summary: b('Learned anisotropic lobes concentrate appearance changes in chosen directions.', '可学习的各向异性波瓣把外观变化集中在特定方向。'),
      appearance: b('Normalized anisotropic spherical Gaussians', '归一化各向异性球面 Gaussian'),
      parameters: b('Lobe coordinate frames, concentration, anisotropy and RGB weights.', '波瓣坐标架、集中程度、各向异性参数与 RGB 权重。'),
      learn: b('Optimize lobe shape, orientation and contribution to each channel.', '优化波瓣形状、朝向及其在各通道中的贡献。'),
      exported: b('Precomputed frames, activated shape parameters, normalization and weights.', '预计算坐标架、激活后的形状参数、归一化常量与权重。'),
      runtime: b('Evaluate each lobe using dot products, pow and exp; combine to RGB before splatting.', '用点积、pow 和 exp 对每个波瓣求值，先合成 RGB 再 splatting。'),
      equation: String.raw`\mathbf r_i(\mathbf d)=\sum_j\mathbf w_{ij}L(\mathbf d;\boldsymbol\theta_{ij})`,
    },
    {
      id: 'nasgabor', title: b('NASGabor · oscillating lobes', 'NASGabor · 振荡波瓣'),
      summary: b('Adds an angular oscillation to a lobe to represent finer directional variation.', '在波瓣中加入角度振荡，表达更细的方向变化。'),
      appearance: b('NASG with a Gabor term', 'NASG 与 Gabor 项'),
      parameters: b('NASG parameters plus a learned oscillation frequency per lobe.', 'NASG 参数，以及每个波瓣学习到的振荡频率。'),
      learn: b('Jointly fit the lobe parameters and oscillation frequency.', '联合拟合波瓣参数与振荡频率。'),
      exported: b('Baked lobe frames and constants, frequency and RGB weights.', '烘焙的波瓣坐标架与常量、频率及 RGB 权重。'),
      runtime: b('Directional lobe response × cosine modulation → weighted RGB → splatting.', '方向波瓣响应 × 余弦调制 → 加权 RGB → splatting。'),
      equation: String.raw`G(\mathbf d)=\tfrac12\!\left(1+\cos(k\,\mathbf d\cdot\mathbf x)\right)`,
    },
    {
      id: 'neural', title: b('Neural appearance · per splat', '神经外观 · 逐点解码'),
      summary: b('A compact feature per Gaussian and a small decoder shared by the whole scene.', '每个 Gaussian 保存紧凑特征，整个场景共享一个小解码器。'),
      appearance: b('Features + shared residual MLP', '特征 + 共享残差 MLP'),
      parameters: b('Per-splat features / base color; shared weights; encoding and activation metadata.', '每点特征／基础色，共享权重，编码和激活元数据。'),
      learn: b('Optimize features and shared MLP weights with the Gaussian parameters.', '与 Gaussian 参数一起优化特征和共享 MLP 权重。'),
      exported: b('Features or baked first-layer static terms, plus remaining network weights.', '特征或第一层烘焙后的静态项，以及其余网络权重。'),
      runtime: b('Per-splat feature + view encoding → tiny MLP → cached RGB → splatting.', '逐点特征 + 方向编码 → 小 MLP → RGB 缓存 → splatting。'),
      equation: String.raw`\mathbf h_i(\mathbf d)=\operatorname{ReLU}(\underbrace{W_f\mathbf f_i}_{\text{baked}}+W_d E(\mathbf d))`,
    },
  ].map(m => ({ ...commonAppearance, ...m, labAppearance: m.id, links: refs(['Renderer + export', gh(appearanceRepo, '/tree/main/viewer')], [`eval_${m.id}.glsl`, gh(appearanceRepo, `/blob/main/viewer/shaders/eval_${m.id}.glsl`)], ['Trained-model manifest', gh(appearanceRepo, '/blob/main/viewer/models.json')]) })),
  {
    id: 'stg-lite', title: b('STG-Lite · explicit motion', 'STG-Lite · 显式运动'), group: 'time',
    maturity: b('Integrated here', '本站已接入'), availability: 'web', geometry,
    appearance: b('Base RGB', '基础 RGB'), time: b('Polynomial motion + temporal opacity', '多项式运动 + 时间透明度'),
    summary: b('A compact moving scene, evaluated directly from time. This is our working Rust/wgpu fixture.', '直接输入时间求值的紧凑动态场景；这是本站已运行的 Rust/wgpu 真实模型。'),
    parameters: b('Center, scales, quaternion, RGB, opacity; temporal center / scale; motion and rotation coefficients.', '中心、尺度、四元数、RGB、透明度，时间中心／尺度，以及运动和旋转系数。'),
    learn: b('Fit geometry, lifespan, motion and base color to synchronized multi-view video.', '用同步多视角视频拟合几何、生命周期、运动和基础色。'),
    exported: b('The checked STG-Lite PLY schema, or our time-addressed streaming chunks.', '已核对的 STG-Lite PLY 字段，或本站支持时间寻址的 streaming 分块。'),
    runtime: b('Time evaluation → GPU culling → depth sorting → indirect splat draw.', '时间求值 → GPU 剔除 → 深度排序 → 间接 splat 绘制。'),
    contract: b('Follow the model’s time normalization, quaternion evolution and opacity activation. These released fixtures cover 50 frames, not a long trained sequence.', '遵循模型的时间归一化、四元数演化与透明度激活。当前发布模型覆盖 50 帧，不是已训练的长序列。'),
    asset: b('Sear Steak: 108,317 Gaussians; Flames: 332,865. Research/evaluation assets; source notices are linked in the viewer.', 'Sear Steak：108,317 个 Gaussian；Flames：332,865 个。研究／评估资产，viewer 中附来源和许可。'),
    support: b('Implemented · Rust / wgpu / WGSL', '已实现 · Rust／wgpu／WGSL'),
    equation: String.raw`\boldsymbol\mu_i(t)=\sum_{k=0}^3\mathbf b_{ik}(t-\tau_i)^k`,
    links: refs(['Play in our viewer', '/streaming/'], ['Inspect one Gaussian', '/?inspect=1#workbench'], ['Rendering contract', gh('pajama-studio/4dgaussian', '/blob/main/STG_LITE_FORMAT.md')], ['Official STG', gh('oppo-us-research/SpacetimeGaussians')]),
  },
  {
    id: 'stg-full', title: b('STG · feature splatting', 'STG · 特征合成'), group: 'time',
    maturity: b('Research baseline', '研究基线'), availability: 'specialist', geometry,
    appearance: b('Feature buffer + per-pixel MLP', '特征缓冲 + 逐像素 MLP'), time: b('Polynomial motion + temporal features', '多项式运动 + 时间特征'),
    summary: b('Composite features first, then decode the image. It requires a different path from STG-Lite.', '先合成特征，再解码图像；需要与 STG-Lite 不同的渲染路径。'),
    parameters: b('STG motion / opacity plus base, direction and time features and a shared decoder.', 'STG 运动／透明度参数，加基础色、方向与时间特征，以及共享解码器。'),
    learn: b('Jointly optimize spacetime Gaussians, features and the screen-space decoder.', '联合优化时空 Gaussian、特征与屏幕空间解码器。'),
    exported: b('Complete checkpoint including the MLP. Check the release variant before loading.', '包含 MLP 的完整 checkpoint；加载前确认发布模型的变体。'),
    runtime: b('Evaluate time → project / sort → composite features → decode each pixel.', '时间求值 → 投影／排序 → 合成特征 → 逐像素解码。'),
    contract: b('Decoding after blending is not equivalent to decoding each splat before blending. Dropping the full model’s decoder is not a faithful Lite conversion.', '先混合后解码与每点先解码后混合并不等价。直接删掉完整模型的解码器不能得到等价的 Lite 模型。'),
    asset: b('Official implementation and model/viewer links exist. This atlas does not yet provide a verified Full checkpoint in our engine.', '官方提供实现及模型／viewer 入口；本目录尚未在自研引擎中验证 Full checkpoint。'),
    support: noPort,
    equation: String.raw`\mathbf C(p)=\mathbf F^{base}(p)+D_\theta(\mathbf F^{dir}(p),\mathbf F^{time}(p),\mathbf r_p)`,
    links: refs(['Official implementation', gh('oppo-us-research/SpacetimeGaussians')], ['Feature rendering · §4.2', 'https://arxiv.org/html/2312.16812v2#S4.SS2']),
  },
  {
    id: 'scaffold', title: b('Scaffold-GS · anchors', 'Scaffold-GS · 锚点'), group: 'structure',
    maturity: b('Research baseline', '研究基线'), availability: 'specialist', geometry,
    appearance: b('View-conditioned neural attributes', '按视角生成的神经属性'), time: fixed,
    summary: b('Anchors and features generate local Gaussian attributes for the current view.', '锚点与特征为当前视角生成局部 Gaussian 属性。'),
    parameters: b('Anchors, offsets, scales and features; color, covariance and opacity networks.', '锚点、偏移、尺度与特征，以及颜色、协方差和透明度网络。'),
    learn: b('Learn the scaffold and shared networks from images.', '通过图像学习锚点结构与共享网络。'),
    exported: b('Anchor PLY plus color_mlp.pt, cov_mlp.pt, opacity_mlp.pt and configuration.', '锚点 PLY、color_mlp.pt、cov_mlp.pt、opacity_mlp.pt 及配置。'),
    runtime: b('Cull anchors → generate view-conditioned Gaussians → rasterize.', '剔除锚点 → 生成依赖视角的 Gaussian → 光栅化。'),
    contract: b('A PLY alone is insufficient. A single baked viewpoint does not retain the original view-adaptive representation.', '单个 PLY 不足以还原模型。只烘焙一个视角不能保留原始的视角自适应表征。'),
    asset: b('Official SIBR viewer and checkpoint layout are documented. A downloadable matching checkpoint is not verified here.', '官方有 SIBR viewer 和 checkpoint 结构说明；此处尚未验证可下载的配套 checkpoint。'),
    support: noPort, links: refs(['Scaffold-GS + viewer', gh('city-super/Scaffold-GS')]),
  },
  {
    id: 'deformation', title: b('4DGS · deformation field', '4DGS · 形变场'), group: 'time',
    maturity: b('Research baseline', '研究基线'), availability: 'specialist', geometry,
    appearance: b('Implementation-dependent Gaussian attributes', '按实现定义的 Gaussian 属性'), time: b('Canonical scene + learned deformation', '标准空间场景 + 学习到的形变'),
    summary: b('A canonical set of Gaussians is deformed to the requested timestamp.', '将标准空间的一组 Gaussian 变形到指定时间。'),
    parameters: b('Canonical Gaussian parameters; spatiotemporal feature planes and deformation decoder.', '标准空间 Gaussian 参数、时空特征平面和形变解码器。'),
    learn: b('Fit the canonical scene and time-conditioned deformation from video.', '从视频拟合标准空间场景与依赖时间的形变。'),
    exported: b('Canonical scene + field / network, or separately baked per-timestamp 3DGS files.', '标准场景 + 场／网络，或单独烘焙的逐时刻 3DGS 文件。'),
    runtime: b('Evaluate deformation at t → obtain 3D Gaussians → render using a compatible splatter.', '在 t 时刻求形变 → 得到 3D Gaussian → 使用兼容的 splatter 渲染。'),
    contract: b('Retaining the field and playing baked frames are different deployment modes. Baking trades inference for storage, sampling and delivery costs.', '保留形变场与播放烘焙帧是两种部署方式。烘焙用存储、时间采样和传输开销换取更少的推理。'),
    asset: b('HUST 4DGaussians documents a viewer and export_perframe_3DGS.py. Bring a trained checkpoint; no compatible fixture is included here.', 'HUST 4DGaussians 提供 viewer 和 export_perframe_3DGS.py。需要训练好的 checkpoint；本站尚无匹配示例。'),
    support: noPort, links: refs(['HUST 4DGaussians', gh('hustvl/4DGaussians')]),
  },
  {
    id: 'native-4d', title: b('Native 4D Gaussians', '原生四维 Gaussian'), group: 'time',
    maturity: b('Research baseline', '研究基线'), availability: 'code',
    geometry: b('Joint space–time Gaussian primitive', '联合空间与时间的 Gaussian primitive'),
    appearance: b('Directional / temporal appearance', '方向／时间外观'), time: b('Native 4D covariance', '原生四维协方差'),
    summary: b('Space and time belong to the primitive itself, rather than an external deformation field.', '空间和时间直接属于 primitive 本身，由四维参数共同表达。'),
    parameters: b('4D mean / covariance parameterization, opacity and the method’s appearance coefficients.', '四维均值／协方差参数化、透明度及该方法的外观系数。'),
    learn: b('Optimize joint spacetime primitives from dynamic observations.', '通过动态观测优化联合时空 primitive。'),
    exported: b('The method’s complete 4D checkpoint, with its time and appearance conventions.', '该方法完整的四维 checkpoint，以及时间和外观约定。'),
    runtime: b('Condition / evaluate the 4D primitive at t → obtain spatial contributions → render.', '在 t 时刻对四维 primitive 做条件化／求值 → 获得空间贡献 → 渲染。'),
    contract: b('“4DGS” is used by several incompatible methods. Identify the paper and checkpoint schema, not just the name.', '多个不兼容的方法都使用“4DGS”名称。必须识别论文与 checkpoint 结构，不能只看名字。'),
    asset: b('Fudan’s official implementation is public. An immediately usable checkpoint / web viewer is not verified here.', 'Fudan 的官方实现已公开；此处尚未确认可直接使用的 checkpoint／网页 viewer。'),
    support: noPort, links: refs(['Fudan native 4DGS', gh('fudan-zvg/4d-gaussian-splatting')]),
  },
  {
    id: 'nts', title: b('NTS · local RGBA fields', 'NTS · 局部 RGBA 场'), group: 'appearance',
    maturity: b('Research extension', '研究扩展'), availability: 'code', geometry,
    appearance: b('Per-primitive local RGBA texture fields', '每个 primitive 的局部 RGBA 纹理场'), time: b('Static or time-conditioned', '静态或依赖时间'),
    summary: b('Different positions inside one splat can contribute different colors and opacities.', '同一个 splat 内的不同位置可以贡献不同的颜色与透明度。'),
    parameters: b('Gaussian attributes, global feature planes and shared local-texture decoders.', 'Gaussian 属性、全局特征平面和共享局部纹理解码器。'),
    learn: b('Jointly optimize the splats and neural local texture representation.', '联合优化 splat 与神经局部纹理表示。'),
    exported: b('Gaussian parameters, global fields and decoders; preserve view/time dependencies.', 'Gaussian 参数、全局场与解码器，保留方向／时间依赖。'),
    runtime: b('Generate local texture factors → find ray–Gaussian contribution point → sample RGBA → composite.', '生成局部纹理因子 → 求射线／Gaussian 贡献位置 → 采样 RGBA → 合成。'),
    contract: b('One RGB per splat cannot preserve this representation. It can augment the base Gaussian appearance rather than replace every SH term.', '每点一个 RGB 无法保留这种表征。它可以扩展原有 Gaussian 外观，并不必然替换全部 SH。'),
    asset: b('Official training/rendering code is public. No ready-to-load checkpoint or interactive web player has been verified for this atlas.', '官方训练／渲染代码已公开。本目录尚未验证开箱即用的 checkpoint 或交互网页播放器。'),
    support: noPort, links: refs(['NTS implementation', gh('19reborn/neural-texture-splatting')], ['NTS method', 'https://arxiv.org/html/2511.18873v1']),
  },
  {
    id: 'relightable', title: b('Relightable GS · materials', '可重光照 GS · 材质'), group: 'material',
    maturity: b('Research family', '研究方法家族'), availability: 'code', geometry,
    appearance: b('Material / lighting decomposition', '材质／光照分解'), time: b('Method-dependent', '取决于具体方法'),
    summary: b('Store enough information to recompute appearance under a changed light.', '保存足够的信息，以便在更换光源后重新计算外观。'),
    parameters: b('Geometry, normals / material attributes, learned features and any visibility / shading networks.', '几何、法线／材质属性、学习特征，以及需要的可见性／着色网络。'),
    learn: b('Recover geometry and lighting response with the method’s supervision. SSD-GS uses varying-light observations.', '通过方法对应的监督恢复几何和光照响应。SSD-GS 使用变化光照下的观测。'),
    exported: b('Material and network checkpoint, not only the RGB observed during training.', '材质及网络 checkpoint，不能只保留训练时观测到的 RGB。'),
    runtime: b('Current view + light → visibility / reflectance / scattering → Gaussian contributions → composite.', '当前视角 + 光源 → 可见性／反射／散射 → Gaussian 贡献 → 合成。'),
    contract: b('Different relighting papers have different contracts. A normal and a GGX shader alone do not reproduce a learned inverse-rendering model.', '不同重光照论文有不同的约定。仅增加法线和 GGX shader 无法复现学习到的逆渲染模型。'),
    asset: b('SSD-GS publishes training/rendering code. Our separate material lab uses synthetic surfels with known materials; it is not an SSD-GS reconstruction.', 'SSD-GS 公开了训练／渲染代码。本站独立材质实验使用已知材质的合成面元，并非 SSD-GS 重建结果。'),
    support: b('Synthetic PBR lab only; research checkpoint not integrated', '仅有合成 PBR 实验；尚未接入研究 checkpoint'),
    links: refs(['SSD-GS implementation', gh('irisfreesiri/SSD-GS')], ['Our synthetic material lab', '/relight/lab/']),
  },
];
